### ISSUE TITLE
Vertex precision issues

### ISSUE THREAD

**Issue by wahfl2** [GTNewHorizons/Angelica#100]
### Your GTNH Discord Username

beljihnwahfl

### Mod Version

1.0.0-alpha10

### Java Version

Java 21

### Bug Report

Vertices are very misaligned even to the untrained eye, on models as simple as a torch.

![image](https://github.com/GTNewHorizons/Angelica/assets/59855656/9f1d37d6-b436-4d52-9f8f-a3b86cde4238)

Sodium 0.5.5 as a baseline:

![image](https://github.com/GTNewHorizons/Angelica/assets/59855656/23b0e56e-08cf-4770-a894-351038ea8e01)

I believe there were fairly severe precision issues in early versions of sodium, and they're popping up here as well.

### Mod List or GTNH Pack Version

GTNH 2.5.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by wahfl2** [comment]
It looks like [this commit](https://github.com/CaffeineMC/sodium-fabric/commit/547c41cf0694fa1b3af5b047eb5f42b1916d3c33) is where the issues were mostly fixed

**Comment by mitchej123** [comment]
Should likely be fixed by https://github.com/embeddedt/embeddium/commit/a82950cf8e77ce78d9c3dacbfa509900f3a224ca
