### ISSUE TITLE
Beacon get randomly cut off&performance degradation

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/Angelica#102]
### Your GTNH Discord Username

Hiakri1nVoid#9527

### Mod Version

1.0.0-Alpha9

### Java Version

Java 20

### Bug Report

![2023-12-30_22 14 18](https://github.com/GTNewHorizons/Angelica/assets/24840795/9ea60a5d-45f4-49d0-8aa3-eefd91f2ce2f)

As the screenshot the beacon get ramdomly cutoff.
Also the fps drops significantly comparing to without angelica.
GPU profiler data from radeontop:
![image](https://github.com/GTNewHorizons/Angelica/assets/24840795/147d0b12-ba81-4876-8218-791c42a3507d)

[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/13798286/fml-client-latest.log)

### Mod List or GTNH Pack Version

Pack version:Nightly-285.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try with the latest alpha (28+) and reopen if still an issue.
