### ISSUE TITLE
It crashes because of an item

### ISSUE THREAD

**Issue by alonegreen** [GTNewHorizons/Angelica#104]
### Your GTNH Discord Username

alonegreen

### Mod Version

angelica-1.0.0-alpha10

### Java Version

Java 8

### Bug Report

Add angelica all was fine until i found a wrong item. It crashes because of openblocks id: 135 item.
[crash-2023-12-30_20.20.23-client.txt](https://github.com/GTNewHorizons/Angelica/files/13799014/crash-2023-12-30_20.20.23-client.txt)

### Mod List or GTNH Pack Version

Crash shows all mods

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by bombcar** [comment]
What is the name of the item (disable Angelica and pick it up and try

 /mt hand

**Comment by alonegreen** [comment]
If i look in crash its OpenBlocks:tank

**Comment by mitchej123** [comment]
Duplicate, openblocks are a known issue and being looked into
