### ISSUE TITLE
Checking the "better questing" tab in NEI breaks rendering.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#110]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

1.0.0-alpha11

### Java Version

Java 21

### Bug Report

![image](https://github.com/GTNewHorizons/Angelica/assets/3158887/48c63c10-1fc0-443b-a2d3-424d64770cfa)

This was me looking at the iron oreberry page for reference.

### Mod List or GTNH Pack Version

GTNH 2.5.1
Matmos v36
DynamicSurroundings v1.0.6.4
ItemPhysicLite 1.1.5
FPSReducer 1.10.3
Angelica 1.0.0-alpha11

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try with the latest alpha (28+) and reopen if still an issue.

**Comment by PlayfulPiano** [comment]
Rendering seems fixed as of latest.
