### ISSUE TITLE
Space Elevator Render can cause stuttering

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/Angelica#114]
### Your GTNH Discord Username

alongstringofnumbers

### Mod Version

alpha 11

### Java Version

Java 19

### Bug Report

The Space Elevator Cable block seems to cause a lot of stutters, or maybe it is the Space Elevator render in general.

When disabling the Space Elevator, and breaking the cable to stop the render, I notice that the amount of stuttering I am seeing is reduced.

Attached are two sample profiles, both on alpha 11, one with the SE elevator enabled, one with it disabled. (Had to zip them because Github doesn't allow the file extension in its uploads)

SE Render Enabled:
[alpha-11-SE.nps.zip](https://github.com/GTNewHorizons/Angelica/files/13800129/alpha-11-SE.nps.zip)

SE Render Disabled:
[alpha-11-No-SE.nps.zip](https://github.com/GTNewHorizons/Angelica/files/13800131/alpha-11-No-SE.nps.zip)

The CPU is an AMD 5600X, the GPU is an NVIDIA RTX 3080, on Linux

### Mod List or GTNH Pack Version

GT:NH 2.4.0, with updated required deps and some backported fixes from GT5U, Lanth, and Twilight Forest

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by embeddedt** [comment]
Is "Always Defer Chunk Updates" enabled? If not, can you try enabling it?

**Comment by ALongStringOfNumbers** [comment]
The above was with that config option disabled. When enabling it, everything is visibly smoother, although there is still a little bit of choppiness.

I have attached a sampler of alpha 11, with this config option enabled, and with the Space Elevator renderer being active.
[alpha-11-Defer.nps.zip](https://github.com/GTNewHorizons/Angelica/files/13824364/alpha-11-Defer.nps.zip)
