### ISSUE TITLE
Rendering difference in EIO Travel Anchors

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/Angelica#115]
### Your GTNH Discord Username

alongstringofnumbers

### Mod Version

alpha 11

### Java Version

Java 19

### Bug Report

EIO Travel Anchors are not rendering their nameplates in the usual purple backplate

This is a screenshot without Angelica Enabled:
![2023-12-30_21 24 01](https://github.com/GTNewHorizons/Angelica/assets/31759736/5f10bfce-c8f3-436c-802e-113e39190705)

And here is a screenshot with Angelica Enabled:
![2023-12-30_21 28 33](https://github.com/GTNewHorizons/Angelica/assets/31759736/0bbaa2fc-23bc-42ed-9ffe-42a8ae6c4a01)

I should also note that the rendering cutoff is a bit more extreme with Angelica. In the first image, Travel Anchors that are on the edge of render distance, but in the "fog" still render (although they blend in a bit with the fog). With Angelica, those travel anchors are not shown at all. This is even the case when I have the Fog Occlusion config option disabled.

### Mod List or GTNH Pack Version

GTNH 2.4.0 with update minimum mods and some backported GT5u, Lanth, and Twilight Forest Fixes

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by AnrDaemon** [comment]
> Travel Anchors that are on the edge of render distance, but in the "fog" still render (although they blend in a bit with the fog). With Angelica, those travel anchors are not shown at all. This is even the case when I have the Fog Occlusion config option disabled.

This could be caused by a difference in calculating of "chunk render distance" between OF and Angelica. Try increasing rendering distance.

**Comment by ALongStringOfNumbers** [comment]
> > Travel Anchors that are on the edge of render distance, but in the "fog" still render (although they blend in a bit with the fog). With Angelica, those travel anchors are not shown at all. This is even the case when I have the Fog Occlusion config option disabled.
> 
> This could be caused by a difference in calculating of "chunk render distance" between OF and Angelica. Try increasing rendering distance.

Optifine was never involved, but I can try increasing then rendering distance and see what happens

**Comment by ALongStringOfNumbers** [comment]
I have not tried increasing the render distance yet, but I have a feeling this may be caused by the "Staff of Teleportation".

I am thinking this because when I am holding the staff, the interface highlight in world from AE2 is also grey, like the travel anchor nameplates, and when not holding the staff, the highlight is the correct red. You can see here, the grey highlight right next to the controller

![2024-01-17_09 41 23](https://github.com/GTNewHorizons/Angelica/assets/31759736/dde6d527-10e2-4a57-ae2a-8d5708942a51)

**Comment by mitchej123** [comment]
Is this still an issue on alpha 28+?

**Comment by Dynamiczbee** [comment]
In Alpha 29 with Java20 in GTNH 2.5.1 I'm not getting any text rendering issues that I can determine, but I am still getting the harsh cut-off of the anchors when in the fog. Sent a video in the GTNH discord.
