### ISSUE TITLE
NEI search bar text position issue

### ISSUE THREAD

**Issue by Tree-er233** [GTNewHorizons/Angelica#117]
### Your GTNH Discord Username

tree_er

### Mod Version

1.0.0-Alpha11

### Java Version

Java 21

### Bug Report

![image](https://github.com/GTNewHorizons/Angelica/assets/110247896/e398a7a8-677b-4ffe-a6b4-f4ed6b8c2e98)
Switching dimensions can cause this problem.

### Mod List or GTNH Pack Version

GTNH 2.5.1 with
LWJGL3ify 1.5.7
Hodgepodge 2.4.4
CodeChickenCore/Lib 1.2.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by ALongStringOfNumbers** [comment]
See #42
