### ISSUE TITLE
Hovering over AE2 search field darkens the game screen

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/Angelica#118]
### Your GTNH Discord Username

SKProCH

### Mod Version

angelica-1.0.0-alpha11-master.4+0c9ec5b23a (testing with fixed #95)

### Java Version

Java 21

### Bug Report

Actually same effect as in #95 

https://github.com/GTNewHorizons/Angelica/assets/29896317/37f75f74-23f7-4798-985a-7f67d23481f9

### Mod List or GTNH Pack Version

GTNH 2.5.1, with updated required mods.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by SKProCH** [comment]
Also, some issues with items when hovering over crafting grid:  

https://github.com/GTNewHorizons/Angelica/assets/29896317/5d198a38-791f-417c-87b1-e5e045e5fad8

**Comment by SKProCH** [comment]
Update: still actual in [1.0.0-alpha12](https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-alpha12)

**Comment by Marvun** [comment]
Btw that not only happens when you hover over the search bar, instead it happens when you hover over everything that is part of the menu and shows a tooltip.

**Comment by Cleptomania** [comment]
This is fixed in master, should be in alpha13 release once that’s ready.

**Comment by Cleptomania** [comment]
Gonna re-open this for the moment. The first fix only worked if batched font rendering was disabled, #174 also fixes this with batched font rendering enabled, so I'll close this again when that is merged or we have a different solution for it.
