### ISSUE TITLE
Continuous frametime spikes

### ISSUE THREAD

**Issue by seitenca** [GTNewHorizons/Angelica#119]
### Mod Version

1.0.0-alpha11

### Java Version

Java 17

### Bug Report

Frametime fluctuates between 1 ms and 70 ms, giving a sensation of continuous FPS drops, which is very annoying.

Happens with vsync (60 fps) and without (~1000fps)

![image](https://github.com/GTNewHorizons/Angelica/assets/55158851/8d8e8388-16eb-43b1-a545-5677dcdeff5a)

### Mod List or GTNH Pack Version

GTNH 2.5.1 with latest deps

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Enable "always defer chunk updates" for now; frametimes are a known issue and slowly being profiled and fixed along with other issues.
