### ISSUE TITLE
Most ChromatiCraft blocks / Satisforestry "Power Slugs" cause horrible flashing

### ISSUE THREAD

**Issue by unilock** [GTNewHorizons/Angelica#121]
### Your GTNH Discord Username

mgpdoll

### Mod Version

1.0.0-alpha11 / 1.0.0-alpha20 (which I can't get running without LWJGL3ify)

### Java Version

Java 8 / Java 17

### Bug Report

When placed, or sometimes just when being held, [Satisforestry's](https://www.curseforge.com/minecraft/mc-mods/satisforestry) "Power Slugs" cause the entire screen to flash rapidly, among other issues.

https://github.com/GTNewHorizons/Angelica/assets/11802133/a295e163-4456-4722-a4b2-87c1c32a28e9

(they're not supposed to be grey)

EDIT: Most blocks from [ChromatiCraft](https://www.curseforge.com/minecraft/mc-mods/chromaticraft) have similar, if not identical effects.

`fml-client-latest.log`: https://gist.github.com/unilock/65ff53b4b342fb653819c6e78d055092

### Mod List or GTNH Pack Version

- `+unimixins-all-1.7.10-0.1.15.jar`
- `angelica-1.0.0-alpha20.jar`
- `CoFHCore-[1.7.10]3.1.4-329.jar` (dependency of Satisforestry, for some reason)
- `DragonAPI+1.7.10+V33b.jar`
- `Satisforestry+1.7.10+V33a.jar`

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Milii20** [comment]
Greetings!, i have the same issue but i wanted to add this issue did not exist in alpha 9 of angelica, this means the following:

Chromaticraft (or satisforestry) + angelica alpha9 = works
Chromaticraft (or satisforestry) + angelica alpha11= has this issue

I hope this helps narrow the issue down

**Comment by charagarlnad** [comment]
Does not happen on angelica-1.0.0-alpha7, seems to be related to changes in alpha8/9.

**Comment by ReikaKalseki** [comment]
Maybe it has something to do with the TESRs' shaders? Slugs have a mild shader, and much of CC does too, but then CC also has many non-TESR shaders (and many shaderless TESRs) which is not quite what you described. Aside from that, I have *no* clue what could be doing this.

**Comment by unilock** [comment]
#260 appears to have fixed it; thanks!

Unfortunately, while a small test instance works fine, my much larger modpack does not fare as well: the entire world is now invisible. [fml-client-latest.log](https://gist.github.com/unilock/0606b5a70418a33ba90ba5565e7f0b60)

I'll have to do more testing to see whether this occurs with older versions of Angelica.
