### ISSUE TITLE
Tool Grid Rendering Issues

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/Angelica#131]
### Your GTNH Discord Username

alongstringofnumbers

### Mod Version

alpha 12

### Java Version

Java 19

### Bug Report

The Tool Grid for interacting with cables, which is displayed when holding GT Tools, has some rendering issues.

First off, when not looking directly at the cable, the tool grid is not rendered at all, but the block outline is still rendered:
![2024-01-04_09 56 21](https://github.com/GTNewHorizons/Angelica/assets/31759736/aa8b396a-ee1a-41ec-82a6-be59f05759d9)

Secondly, when looking at the cable, the grid outline is rendered, but is very fuzzy, and parts of the outline disappear depending on where on the cable you are looking:
![2024-01-04_09 56 19](https://github.com/GTNewHorizons/Angelica/assets/31759736/60a47d14-7c1a-4f84-aeed-0c43bddfe5e9)

### Mod List or GTNH Pack Version

2.4.0 with some backported GT5U, Lanth, and Twilight Forest Fixes. Plus all required upgraded mods

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Cleptomania** [comment]
I'm unable to re-produce this with GTNH 2.5.1 and latest master branch of Angelica.

**Comment by ALongStringOfNumbers** [comment]
Hm, I tested this in a new instance that I updated to 2.5.1 with alpha 14 and was unable to reproduce this as well, so I am going to close this.

**Comment by Willshaper** [comment]
I can reproduce this on my fresh 2.5.1 instance with Angelica + NEI updated.

Java 21
Angelica Alpha 14
Hodgepodge 2.4.9
CodeChickenCore 1.2.1
UniMixins 0.1.15
NotEnoughItems 2.5.6-GTNH-PRE


![image](https://github.com/GTNewHorizons/Angelica/assets/22663971/598c11c1-c4b3-4f99-81a6-42314603020c)
![image](https://github.com/GTNewHorizons/Angelica/assets/22663971/d0a7007b-41b4-414b-86a3-4c34a0298939)
![image](https://github.com/GTNewHorizons/Angelica/assets/22663971/1beb2ad0-f311-4836-8276-3ad9943dca13)
![image](https://github.com/GTNewHorizons/Angelica/assets/22663971/5f6810c2-07f5-4064-9975-bf778599175a)
