### ISSUE TITLE
Occasional ConcurrentModificationException on server join

### ISSUE THREAD

**Issue by wahfl2** [GTNewHorizons/Angelica#134]
### Your GTNH Discord Username

beljihnwahfl

### Mod Version

1.0.0-alpha12

### Java Version

Java 21

### Bug Report

I occasionally (maybe 1 in 15 times) get this crash when joining my server.

https://mclo.gs/nwwScxm

### Mod List or GTNH Pack Version

GTNH 2.5.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by embeddedt** [comment]
Nice catch; looks like `TileEntityRendererDispatcher#mapSpecialRenderers` should be changed to a `ConcurrentHashMap` as it's populated lazily.
