### ISSUE TITLE
Black Screen when in world, game did not crash, can open inventory and look at NEI

### ISSUE THREAD

**Issue by AetherLegacyPro** [GTNewHorizons/Angelica#141]
### Mod Version

1.0.0-alpha12

### Java Version

Java 8

### Bug Report

[latest.log](https://github.com/GTNewHorizons/Angelica/files/13848290/latest.log)
This is the latest log, the game did not crash but everything was just a black screen. Walia was still working and I could open up the inventory and look through NEI with no issues. I could move around but I could not see anything in world.

### Mod List or GTNH Pack Version

![image(29)](https://github.com/GTNewHorizons/Angelica/assets/102751411/4fc34559-7c57-42ea-8345-d60a2bc8f2b7)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by AetherLegacyPro** [comment]
[Uploading fml-client-latest.log…]()

**Comment by AetherLegacyPro** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/13848352/fml-client-latest.log)

**Comment by AetherLegacyPro** [comment]
Future Commands is the mod causing the crash

**Comment by AnrDaemon** [comment]
Try resizing your Minecraft window.
I've seen a similar effect with DragonAPI.

**Comment by VivianRen6545** [comment]
i meet the same bug,it appears when TC4 curse happends, F1 could make it disappear.
![image](https://github.com/GTNewHorizons/Angelica/assets/28915625/9414f548-bba5-4b7e-8103-29444ce7ed56)

F1 
![image](https://github.com/GTNewHorizons/Angelica/assets/28915625/cd069c6b-a589-4b97-abd9-d93eb271de07)

**Comment by VivianRen6545** [comment]
> i meet the same bug,it appears when TC4 curse happends, F1 could make it disappear. ![image](https://private-user-images.githubusercontent.com/28915625/294741514-9414f548-bba5-4b7e-8103-29444ce7ed56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MDg4NzIsIm5iZiI6MTcwNDYwODU3MiwicGF0aCI6Ii8yODkxNTYyNS8yOTQ3NDE1MTQtOTQxNGY1NDgtYmJhNS00YjdlLTgxMDMtMjk0NDRjZTdlZDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA2MjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MWI4ZTQyNDc4NjljZTg1MDlkNmNhNzIwY2JmOTM2MzU5ZTk5NDMyNTg3NTcxZDNiZWJjZDE0YWJlMzBmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A2LGyZmUY8KPWyzCtwUQK7krbXwQWGtXlisnKAc9AR0)
> 
> F1 ![image](https://private-user-images.githubusercontent.com/28915625/294741518-cd069c6b-a589-4b97-abd9-d93eb271de07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MDg4NzIsIm5iZiI6MTcwNDYwODU3MiwicGF0aCI6Ii8yODkxNTYyNS8yOTQ3NDE1MTgtY2QwNjljNmItYTU4OS00Yjk3LWFiZDktZDkzZWIyNzFkZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA2MjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOTI2NDYxZmMwMjg4NTA0MGIwYzI3NTNiZDZhMjBlNGFmNzFkYzllZjQ2NGIwZTZmMTkyZmVkYWQ0Yjk3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KU6VXRLKTbrgdbbqEHocBs5pdpWJ1tpSf1pteK4SEnk)

i must completely close the game to make it normal again,back to startscreen is useless

**Comment by Pistonight** [comment]
@AetherLegacyPro @AnrDaemon Can you check if this issue still exists in alpha17?
The TC4 issue should be fixed

**Comment by mitchej123** [comment]
Try with the latest alpha (28+) and reopen if still an issue.
