### ISSUE TITLE
enableVBO crash with Shatter mod (when a mob die)(with DEV BUILD not release build on the github)

### ISSUE THREAD

**Issue by quentin452** [GTNewHorizons/Angelica#142]
### Your GTNH Discord Username

imacatfr

### Mod Version

alpha12-master.16+369893cfa3-dirty (mean : https://github.com/quentin452/Angelica/commit/369893cfa36100e4f6412792123d8cb9d7b3372c)

### Java Version

Java 8

### Bug Report

[crash-2024-01-06_14.47.56-client.txt](https://github.com/GTNewHorizons/Angelica/files/13849895/crash-2024-01-06_14.47.56-client.txt)

### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.15
1.7.10.SecurityCraft.v1.8.15
angelica-1.0.0-alpha12-master.16+369893cfa3-dirty
falsepatternlib-mc1.7.10-1.0.0
iChunUtil-4.2.3
Shatter-4.0.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
I see, it's failing when trying to delete the display list, because it doesn't exist since we used a VBO instead....

**Comment by mitchej123** [comment]
@quentin452 please try https://github.com/GTNewHorizons/Angelica/pull/151

**Comment by quentin452** [comment]
Now when i try launching world : 
[crash-2024-01-07_03.16.29-client.txt](https://github.com/GTNewHorizons/Angelica/files/13852013/crash-2024-01-07_03.16.29-client.txt)

**Comment by mitchej123** [comment]
ah, my bad

**Comment by mitchej123** [comment]
Try again, just pushed a fix and verified it works locally

**Comment by quentin452** [comment]
its weird for me its doesn't work ,it crash at 3/7 of loading
[crash-2024-01-07_03.25.25-client.txt](https://github.com/GTNewHorizons/Angelica/files/13852025/crash-2024-01-07_03.25.25-client.txt)

**Comment by mitchej123** [comment]
Did you pull the latest commit from the branch?

I offset the list when registering it now....

**Comment by quentin452** [comment]
i compiled this : https://github.com/GTNewHorizons/Angelica/pull/151/commits/fb1f0e1b2f02ef0e806a00044f8d74f4938d6c64

**Comment by mitchej123** [comment]
hmm, ok, let me try another approach...

**Comment by mitchej123** [comment]
Are you sure you replaced it with that one?  I just debugged it locally...
```
starGLCallLIst = -2147483648
-2147483648 -= -2147483648 = 0
vertexBuffers.set(0, vertexBuffer);
```

**Comment by quentin452** [comment]
yep sure i decompiled the VBOManager with Fernflower and it contain the new commit
