### ISSUE TITLE
ChromatiCraft CloudRenderEvent crash on main menu

### ISSUE THREAD

**Issue by charagarlnad** [GTNewHorizons/Angelica#145]
### Your GTNH Discord Username

222317

### Mod Version

angelica-1.0.0-alpha12-master.17+b0828fb96a-dirty

### Java Version

Java 17

### Bug Report

https://mclo.gs/97HfrFC

### Mod List or GTNH Pack Version

unimixins-all-1.7.10-0.1.14
angelica-1.0.0-alpha12-master.17+b0828fb96a-dirty
ChromatiCraft 1.7.10 V33a
DragonAPI 1.7.10 V33b
lwjgl3ify-1.5.7

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
The VBO clouds have not officially been released.  

Please don't submit issues against master/self compiled unless you're planning to fix it yourself.

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/Angelica/pull/151 might fix this
