### ISSUE TITLE
Vbo startup crash 

### ISSUE THREAD

**Issue by quentin452** [GTNewHorizons/Angelica#152]
### Your GTNH Discord Username

imacatfr

### Mod Version

https://github.com/GTNewHorizons/Angelica/commit/b100652a7dded922cf82fda8e74b0d4609673d48

### Java Version

Java 8

### Bug Report

[crash-2024-01-07_04.37.03-client.txt](https://github.com/GTNewHorizons/Angelica/files/13852137/crash-2024-01-07_04.37.03-client.txt)

The crash appaer only outside of dev and appear at 3/7 of loading
### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.15
1.7.10.SecurityCraft.v1.8.15
angelica-NO-GIT-TAG-SET
falsepatternlib-mc1.7.10-1.0.0
iChunUtil-4.2.3
Shatter-4.0.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Where did you get `1.7.10.SecurityCraft.v1.8.15` from?

**Comment by mitchej123** [comment]
Ok, it seems that something's messing with `starGLCallList` (`field_72772_v `)the value I see is `55490` and if it was generated by the VBO functions it would be closer to Integer.MIN_INT

**Comment by mitchej123** [comment]
Ah... so it was a remap issue... might have a fix

**Comment by quentin452** [comment]
> Where did you get `1.7.10.SecurityCraft.v1.8.15` from?

https://github.com/quentin452/SecurityCraft

**Comment by quentin452** [comment]
> Ah... so it was a remap issue... might have a fix

yep the new one fixed the crash thx
