### ISSUE TITLE
HUD caching issue with FPS REDUCER

### ISSUE THREAD

**Issue by quentin452** [GTNewHorizons/Angelica#156]
### Your GTNH Discord Username

imacatfr

### Mod Version

https://github.com/GTNewHorizons/Angelica/commit/ad533bcae95633fcbc2e27809219a8d011c1d9f4

### Java Version

Java 8

### Bug Report

It say i have 20 fps ,but i have 1000

![image](https://github.com/GTNewHorizons/Angelica/assets/42176772/2094ad78-927a-4ba4-a757-70904a166adc)

### Mod List or GTNH Pack Version

![image](https://github.com/GTNewHorizons/Angelica/assets/42176772/95cc35d1-3f2b-41a4-99b9-961f853d27d5)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Where is the fps indicator from.  Also I've not looked at fps reducer at all so it'd be a low priority fix for me

**Comment by quentin452** [comment]
the fps indicator come from fps reducer

**Comment by ah-OOG-ah** [comment]
This is most likely because HUD caching effectively tenders that indicator at 20FPS. If [this](https://legacy.curseforge.com/minecraft/mc-mods/fps-reducer) is the mod it'd be best to disable FPSReducer's meter and add one in Angelica.
 Otherwise, you'd need to Mixin because that mod is ARR

**Comment by quentin452** [comment]
> This is most likely because HUD caching effectively tenders that indicator at 20FPS. If [this](https://legacy.curseforge.com/minecraft/mc-mods/fps-reducer) is the mod it'd be best to disable FPSReducer's meter and add one in Angelica. Otherwise, you'd need to Mixin because that mod is ARR

i use https://www.curseforge.com/minecraft/mc-mods/my-coordinates-mod (the FPS metter work with angelica)
