### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by LSK-LW** [GTNewHorizons/Angelica#161]
### Mod Version

1.0.0-alpha13

### Java Version

Java 8

### Bug Report

Can't start game after upgrading alpha12 to alpha13.

latest.log([https://mclo.gs/8aiyV1O](https://mclo.gs/8aiyV1O))
crash report([https://mclo.gs/3x5j9hl](https://mclo.gs/3x5j9hl))

### Mod List or GTNH Pack Version

![image](https://github.com/GTNewHorizons/Angelica/assets/12579533/f17f5d84-ceec-4523-86ce-e224db55f9ae)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try disabling `enableVBO` in the config, one of your mods isn't compatible with it.

**Comment by mitchej123** [comment]
Looks like a conflict with `noppes.npcs.mixin.MixinModelRenderer`

**Comment by LSK-LW** [comment]
> Try disabling `enableVBO` in the config, one of your mods isn't compatible with it.

After changing the configuration file, it can start normally.

**Comment by LSK-LW** [comment]
> Try disabling `enableVBO` in the config, one of your mods isn't compatible with it.

Game crashes when entering world. [https://mclo.gs/xN5xjuY](https://mclo.gs/xN5xjuY)

**Comment by mitchej123** [comment]
Try with the latest alpha (28+) and reopen if still an issue.
