### ISSUE TITLE
[alpha13] Crash related to NotFine Star Render

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#162]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

1.0.0-alpha13

### Java Version

Java 21

### Bug Report

Game freezes and never finishes to the main menu on the latest alpha.
```
[Client thread/ERROR] [FML]: Caught exception from notfine
--
at jss.notfine.render.RenderStars.reloadStarRenderList(RenderStars.java:15) ~[angelica-1.0.0-alpha13.jar:?]
at jss.notfine.core.Settings$12.applyChanges(Settings.java:111) ~[angelica-1.0.0-alpha13.jar:?]
...
```

![image](https://github.com/GTNewHorizons/Angelica/assets/3158887/387df77f-d2ce-444a-aa42-ccf31835fdaf)
This issue was also occurring for me in alpha8 but was fixed in alpha9.

### Mod List or GTNH Pack Version

GTNH 2.5.1
Matmos v36
DynamicSurroundings v1.0.6.4
ItemPhysicLite 1.1.5
FPSReducer 1.10.3
Angelica 1.0.0-alpha13

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by PlayfulPiano** [comment]
Update: tested this with just GTNH + angelica 13 and prereqs and same issue, so it isn't related to additional mods.
https://mclo.gs/NjoUJ25

**Comment by PlayfulPiano** [comment]
updating to 2.4.9 hodgepodge also did not work https://mclo.gs/vHmbbnl

**Comment by PlayfulPiano** [comment]
also to be clear, alpha12 works fine with the added mods, so i'm unsure what in alpha13 causes issues.

I am on java21 graalvm and i'm using a gtx 1650 ti, if that might help or not.

**Comment by makamys** [comment]
I can reproduce this with no mods other than Angelica (+deps) if I change the star density slider in the NotFine settings. It also happens on startup if `optionsnf.txt` already exists (my game actually crashes though rather than freezing).

It happens because Angelica attempts to expose a `@Redirect`-annotated method in an interface. The method gets renamed to something like `redirect$zzj000$angelica$startStarsVBO` at runtime once the mixin has been applied, hence the error. The implementation should be moved to a "naked" method instead.

**Comment by PlayfulPiano** [comment]
> I can reproduce this with no mods other than Angelica (+deps) if I change the star density slider in the NotFine settings. It also happens on startup if `optionsnf.txt` already exists (my game actually crashes though rather than freezing).
> 
> It happens because Angelica attempts to expose a `@Redirect`-annotated method in an interface. The method gets renamed to something like `redirect$zzj000$angelica$startStarsVBO` at runtime once the mixin has been applied, hence the error. The implementation should be moved to a "naked" method instead.

by any chance was there something similar in the alpha-8 version of angelica that got changed in alpha-9? because I had this same issue with alpha 8 but not alpha 9 for some reason. nor for any version btwn alpha 9 and 12.

**Comment by Roadhog360** [comment]
Getting the same issue, I'll also add this happens even if both NotFine config options are disabled too.
