### ISSUE TITLE
Crash on world join

### ISSUE THREAD

**Issue by Abalieno** [GTNewHorizons/Angelica#163]
### Your GTNH Discord Username

trysteros

### Mod Version

angelica-1.0.0-alpha13

### Java Version

Java 21

### Bug Report

[crash-2024-01-08_01.49.50-client.txt](https://github.com/GTNewHorizons/Angelica/files/13855768/crash-2024-01-08_01.49.50-client.txt)

### Mod List or GTNH Pack Version

https://github.com/enmumne/Grumpy-GregTech-6

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Abalieno** [comment]
Somewhat related? But not about EnderIO https://github.com/GTNewHorizons/Angelica/issues/154

**Comment by Valor760** [comment]
Having the same issue with alpha13 version on GTNH 2.5.0. The alpha12 works fine.
