### ISSUE TITLE
(the issue appaer if sodium is disabled)When watching the sky color get bugged (if HUD caching is enabled the bug is amplified)

### ISSUE THREAD

**Issue by quentin452** [GTNewHorizons/Angelica#166]
### Your GTNH Discord Username

imacatfr

### Mod Version

https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-alpha13

### Java Version

Java 8

### Bug Report

![image](https://github.com/quentin452/HUD-CACHING/assets/42176772/5deb3312-5668-4a1c-a319-dae70e6cbe51)

Angelica config : 

[angelica.zip](https://github.com/GTNewHorizons/Angelica/files/13856261/angelica.zip)

Video with hud caching enabled only : 

https://github.com/GTNewHorizons/Angelica/assets/42176772/2fa0a57c-2815-4724-bbea-ef9cd429e784

Can be tested on this world : 

[New World-------.zip](https://github.com/GTNewHorizons/Angelica/files/13856282/New.World-------.zip)

### Mod List or GTNH Pack Version

![image](https://github.com/GTNewHorizons/Angelica/assets/42176772/6a4907c4-fb96-432e-9152-82c5fd6a0e51)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by quentin452** [comment]
When disabling colors things in RedirectorTransformer it "fix" 50% of the issue , it fix the issue when watching the sky when hud caching is disabled
![image](https://github.com/GTNewHorizons/Angelica/assets/42176772/d4f5d30e-32b1-4782-96aa-21a766c6ae57)

but the issue when hud caching is enabled don't get fixed(and can't find which cause it,i just know this mixin made the issue : MixinEntityRenderer_HUDCaching) , the issue appear when you held a leave / enchant book/ chicken egg in hand and maybe other and watching the sky 
![image](https://github.com/GTNewHorizons/Angelica/assets/42176772/408c549b-b797-4ea1-a1f5-b4c4ffc10949)

so something in GLStateManager is broken????

**Comment by mitchej123** [comment]
Try with the latest alpha (28+) and reopen if still an issue.
