### ISSUE TITLE
Architect Sawbench Glass Invisibility

### ISSUE THREAD

**Issue by queeek180** [GTNewHorizons/Angelica#167]
### Your GTNH Discord Username

queeek180

### Mod Version

1.0.0-alpha13

### Java Version

Java 17

### Bug Report

Glass blocks will appear invisible when cut in the architect's sawbench from ArchitectureCraft. This seems to only affect partially-transparent blocks, blocks with fully transparent holes appear fine. The block is perfectly visible from the player's inventory
![2024-01-08_16 10 14](https://github.com/GTNewHorizons/Angelica/assets/63887374/6da0b690-c148-48f5-a5b1-a150edf16e35)
![2024-01-08_16 11 03](https://github.com/GTNewHorizons/Angelica/assets/63887374/82c5de9b-a3b8-4ecf-92be-790f106d7d48)

### Mod List or GTNH Pack Version

GTNH-2.5.1 w/ mods updated & removed as recommended by the README.md
I confirmed the issue to persist using Angelica's default config

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by queeek180** [comment]
All blocks made in the Malisis' Doors Block Mixer have the same issue, including non-transparent blocks

**Comment by mitchej123** [comment]
Try with the latest alpha (28+) and reopen if still an issue.

**Comment by MushroomDynamo** [comment]
I can't reopen this, but I can confirm this still happens with both ArchitectureCraft cut stained glass blocks and with the Block Mixer non-transparent blocks as described in the original ticket.

**Comment by mitchej123** [comment]
I'm actually working on making ArchitectureCraft less of a cluster fuck and thread safe so it can render off thread, noticed this myself and will probably fix it while I'm working on it.
