### ISSUE TITLE
Thaumcraft "Throb" Warp effect overlay turns the screen black, runic shield borked

### ISSUE THREAD

**Issue by divine-ray** [GTNewHorizons/Angelica#169]
### Your GTNH Discord Username

divine_ray

### Mod Version

1.0.0-alpha1

### Java Version

Java 8

### Bug Report

https://mclo.gs/eKEBGb1
Whenever a thaumcraft Warp event activates/occurs, my screen turns black until i restart the game. 
For reference, i'm on a server, and it persists across relogs, also when I open a singleplayer world. 
The UI/HUD still renders fine, i cannot see the world.

additionally, under certain circumstances i can't replicate rn, the runic shielding overlay over my HP bar turns into solid rectangles. 

### Mod List or GTNH Pack Version

GTNH-2.5.1 on a private Server. 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Cleptomania** [comment]
This is the same as #86, gonna close this to track it in one place.
