### ISSUE TITLE
Crash Loading into game

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/Angelica#172]
### Your GTNH Discord Username

alongstringofnumbers

### Mod Version

alpha 13

### Java Version

Java 19

### Bug Report

https://pastebin.com/Q6VV6w2T

I got this crash when trying to load into the world on alpha 13

### Mod List or GTNH Pack Version

GTNH 2.4.0, with some backported fixed from GT5U, Lanth, and Twilight Forest, plus all mandatory updated mods

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Pistonight** [comment]
I am seeing the same failure

**Comment by mitchej123** [comment]
Turn back on the animation speedup.   I'll add a fix so it can properly be disabled.

On another note it now works with water/sodium :)
