### ISSUE TITLE
Incompatible with emojicord

### ISSUE THREAD

**Issue by kang-png** [GTNewHorizons/Angelica#173]
### Mod Version

1.0.0-alpha13

### Java Version

Java 8

### Bug Report

I use a translator.
This is a mod that displays emoji.
Angelica makes the emojicord not display properly.
https://mclo.gs/wEwEy1M

### Mod List or GTNH Pack Version

angelica-1.0.0-alpha13.jar
Emojicord.jar
https://github.com/Team-Fruit/Emojicord/releases/tag/build%2Fb41

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try with the latest alpha (28+) and reopen if still an issue.

**Comment by kang-png** [comment]
angelica-1.0.0-alpha34 still have the same problem

> Try with the latest alpha (28+) and reopen if still an issue.
