### ISSUE TITLE
Mekanism hud issue

### ISSUE THREAD

**Issue by quentin452** [GTNewHorizons/Angelica#176]
### Your GTNH Discord Username

imacatfr

### Mod Version

alpha13

### Java Version

Java 8

### Bug Report

You need to held a jetpack from Mekanism
![image](https://github.com/GTNewHorizons/Angelica/assets/42176772/dab35ddf-99fe-4cdb-b844-53594b26623e)

### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.15
angelica-1.0.0-alpha13
Mekanism-Community-Edition-1.7.10-9.10.33-Core

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Pistonight** [comment]
Can you check if the issue still exists in alpha17?

**Comment by mitchej123** [comment]
Try with the latest alpha (28+) and reopen if still an issue.
