### ISSUE TITLE
org.lwjgl.opengl.OpenGLException: Cannot use offsets when Draw Indirect Object is disabled

### ISSUE THREAD

**Issue by AnrDaemon** [GTNewHorizons/Angelica#179]
### Your GTNH Discord Username

AnrDaemon

### Mod Version

alpha13

### Java Version

Java 8

### Bug Report

[crash-2024-01-09_04.26.08-client.txt](https://github.com/GTNewHorizons/Angelica/files/13889873/crash-2024-01-09_04.26.08-client.txt)

### Mod List or GTNH Pack Version

IDK about reproducibility dependent on mods loaded, this happens on my notebook with integrated GPU, but not on desktop.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Please post the full fml-client-latest.log

**Comment by AnrDaemon** [comment]
Still crashes on notebook with alpha15.
This SO question MAY BE related: https://stackoverflow.com/questions/27525323/openglexception-cannot-use-offsets-when-array-buffer-object-is-disabled-on-a (please forgive me if not).

Fresh log just in case: [latest.log](https://github.com/GTNewHorizons/Angelica/files/13989731/latest.log)

**Comment by mitchej123** [comment]
I'm not sure if it's a card issue, a driver issue, or what it is offhand.  Were you ever able to get multidraw to work?

The log seems to indicate it's reporting 4.6 availability, but the same code that works on other machines isn't... :thinking:

**Comment by AnrDaemon** [comment]
This is an Intel integrated GPU, so anything could be possible.
Intel is known to "freely" interpret the standards.
Same modpack works on desktop with nVidia GT-640.

Would a debug log helps narrowing down the issue?

**Comment by mitchej123** [comment]
Post whatever logs you can.  My going assumption is you'll have to use oneshot instead of multidraw, but will dig into it as time allows.

**Comment by AnrDaemon** [comment]
Yeah, as you predicted, I've had to disable `use_chunk_multidraw` to get it to run.
Here's a debug log for running without that option, and then enabling it.
[2024-02-11-Angelica-alpha24-debug.log](https://github.com/GTNewHorizons/Angelica/files/14233362/2024-02-11-Angelica-alpha24-debug.log)

**Comment by AnrDaemon** [comment]
Though, from 60 upward to 90 FPS in test world is impressive.

I'll have to check with my server world, but so far it looks very promising.

**Comment by mitchej123** [comment]
See https://github.com/GTNewHorizons/Angelica/issues/373
