### ISSUE TITLE
Crash while loading into world with a Bacterial Vat

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/Angelica#181]
### Your GTNH Discord Username

alongstringofnumbers

### Mod Version

alpha 13

### Java Version

Java 19

### Bug Report

After changing the animation speedup config as suggested in #180, I was able to join the world.

However, while the world was loading in around me (not all chunks displayed), I accessed the video settings menu and switched to the performance tab, which crashed me with the following error https://pastebin.com/TeDmrJGj (editted, wrong paste initially)

### Mod List or GTNH Pack Version

GTNH 2.4.0 plus backported fixes from GT5U, Lanth, and Twilight Forest, will all mandatory updated mods.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Hmm, this was already fixed, but I think it was done after alpha13... I'll push a new one soon :tm:

**Comment by ALongStringOfNumbers** [comment]
Update, this is related to the Bartworks Bacterial Vat multiblocks I believe, which change their color of fluid displayed in them when loading into the world

**Comment by ALongStringOfNumbers** [comment]
I just got a similar crash, but this time it was with AE2 https://pastebin.com/u3zJLzHB
