### ISSUE TITLE
Issues with Animated Items in AE crafting status

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/Angelica#182]
### Your GTNH Discord Username

alongstringofnumbers

### Mod Version

alpha 13

### Java Version

Java 19

### Bug Report

This error originally happen on alpha 13, but I also reproduced it on master (537eb06)

Attached is a video of the issue occurring:

https://github.com/GTNewHorizons/Angelica/assets/31759736/53a43220-ef9f-44ea-ad53-3bcd7fbd2873

Items displayed in the yellow "scheduled" tab or the green "crafting" tab are animated fine, but items in the white "stored" tab are not animated at all.

This issue is solved when the config option `speedupAnimations` is set to false.

Btw, I could not find this config option in the in game menu anywhere, where would it be located?

### Mod List or GTNH Pack Version

GTNH 2.4.0, with backported fixed from GT5U, Lanth, Twilight Forest. And all mandatory updated mods.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try with the latest alpha (28+) and reopen if still an issue.
