### ISSUE TITLE
UI rendering bug on Intel Arc & Iris Xe Graphics 

### ISSUE THREAD

**Issue by valiray** [GTNewHorizons/Angelica#185]
### Your GTNH Discord Username

valiray

### Mod Version

1.0.0-alpha14

### Java Version

Java 17

### Bug Report

some menus are not rendering right there for making them unusable 
![image](https://github.com/GTNewHorizons/Angelica/assets/133289098/83a8590f-b81e-4a04-b519-0c28573265ef)
here is also a list of setting menus that are broken
- snooper
- controls
- language
- resource packs
- the multiplayer server section screen
- the mod list

and a list of ones that are not

- music
- multiplayer settings
- broadcast settings 
- the singleplayer world section screen

i am also on intel arc so that may be why

[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/13929608/fml-client-latest.log)

### Mod List or GTNH Pack Version

2.5.1 + Angelica + hodgepodge-2.4.9 + CodeChickenCore-1.2.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Yuan-Hou** [comment]
In Java 8, using Intel Iris Xe (i5-1135G7) has the same problem. The window goes black after blindly clicking into the singleplayer save.
![image](https://github.com/GTNewHorizons/Angelica/assets/39647947/5a12bb76-dd1c-4b59-8947-db7008c5a7ef)

**Comment by paulzzh** [comment]
Java 17 + HD630 (i7-7700HQ) has the same problem.
<img width="960" alt="be0a27985c11cef55ce7aca752e17a34" src="https://github.com/GTNewHorizons/Angelica/assets/28055560/0bdaeac4-446f-4ee0-a99c-df5310cc7cf0">

**Comment by KAMKEEL** [comment]
Can also confirm this is happening to me!

**Comment by valiray** [comment]
After finally being able to test on a non intel gpu (my steamdeck) I can also confirm that if you try to go to a heavy area of a base the game will temporarily freeze (usually about half a second or so)

**Comment by fuckindumbfox** [comment]
Adoptium Java 21 + Intel UHD Graphics 620, also happening
![image](https://github.com/GTNewHorizons/Angelica/assets/130804352/d8458cb3-e6b7-4961-b6ac-233e06cab2ac)

**Comment by valiray** [comment]
after some more testing it looks like intel works on linux/mesa, the ui and all the other rendering bugs are gone? so it might just be something with intel drivers on windows?

**Comment by chochem** [comment]
did any of you try coretweaks? it has some fixes for intel driver rendering problems

**Comment by fuckindumbfox** [comment]
> did any of you try coretweaks? it has some fixes for intel driver rendering problems

I did, (just installed it, no further tweaking within it) but it didnt fix the screen melting

**Comment by makamys** [comment]
Can reproduce this on Windows with an intel iGPU, setting `enableFontRenderer` to false fixes it.

**Comment by Wacchi-Lorie** [comment]
in my side, intel latest graphics has issue with 1.7.10 itself, without anything. however, changed to jdk17 just mysteriously solved the issue. this is only according to my friend's laptop, im using a nvidia btw

**Comment by fuckindumbfox** [comment]
COMPLETED!_!_!_!???!!?!

**Comment by Kobeto** [comment]
Can someone explain the fix? I really don’t understand much other than the fact that the issue is caused by intel.

**Comment by Lyfts** [comment]
The fix is to update Angelica https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-alpha43 or turn off enableFontRenderer in Angelica config.

**Comment by FakeLook** [comment]
I have the same problem with 2.6, java 21. My rig: R5 5600, 16Gb ram allocated & Intel arc A770 LE  driver 31.0.101.552 released 12.5.2024
