### ISSUE TITLE
Signs change color rendering on certain chunks

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#188]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

1.0.0-alpha14

### Java Version

Java 21

### Bug Report

![image](https://github.com/GTNewHorizons/Angelica/assets/3158887/c58a0b77-50d2-4cc3-bd9a-52864904ff7d)
![image](https://github.com/GTNewHorizons/Angelica/assets/3158887/0db216d3-8a08-4c5b-ab32-3674ca25e762)

### Mod List or GTNH Pack Version

GTNH 2.5.1
Matmos v36
DynamicSurroundings v1.0.6.4
ItemPhysicLite 1.1.5
FPSReducer 1.10.3
Angelica 1.0.0-alpha14
Sound Physics 1.7.10
hodgepodge 2.4.9
justenoughcalculation 4.0
craftingtweaks 1.0.88
fullscreenwindowed 1.3.0b
fullscreenwhileinactive 1.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try with the latest alpha (28+) and reopen if still an issue.

**Comment by PlayfulPiano** [comment]
Rendering seems fixed as of latest.
