### ISSUE TITLE
Serious render problem with DragonAPI

### ISSUE THREAD

**Issue by M3MEMonster** [GTNewHorizons/Angelica#193]
### Mod Version

1.0.0-alpha14

### Java Version

Java 21

### Bug Report

When I installed angelica with Reika's mods(all his mods need DragonAPI to work), the text in command bar and f3 and WAILA will lose their color even become a piece of grey blank. And the render when GUI is opeded is also very weird. Here are some screenshots.
![2024-01-15_13 52 44](https://github.com/GTNewHorizons/Angelica/assets/110038164/fc70b87f-f634-4d3b-b5e4-0b05508c5422)
![2024-01-15_13 53 09](https://github.com/GTNewHorizons/Angelica/assets/110038164/95db5afc-3e16-41cb-b0af-e5b4e6c4a51a)
![2024-01-15_13 53 15](https://github.com/GTNewHorizons/Angelica/assets/110038164/cf0839cc-4bc8-4629-99c6-a090fede0aed)
![2024-01-15_13 53 19](https://github.com/GTNewHorizons/Angelica/assets/110038164/fb1dddbf-c711-46c3-8082-a38505553c3a)

### Mod List or GTNH Pack Version

angelica, CodeChickenCore+Lib-1.2.0, unimixins-0.1.15, gtnhlib-0.2.1, hodgepodge-2.4.9, LWJGL3ify-1.5.12, DragonAPI-v33b, ChromatiCraft-v33a, RotaryCraft-v33a, ReactorCraft-v33a, ElectriCraft-v33a, TreeClimbing-v33a. Actually there are many other mods but angelica has no problem with them. The problem only happened when I added Reika's mods.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by divine-ray** [comment]
reika's mods are, frankly put, horrendously incompatible with many mods due to some inner workings that angelica modified

**Comment by AnrDaemon** [comment]
> Actually there are many other mods

Actually, attach the full modlist (cause a debug crash F3+C) or even better - full log.

_After_ that, try disabling font rendering tweaks in Angelica.

**Comment by M3MEMonster** [comment]
Full log: [latest.log](https://github.com/GTNewHorizons/Angelica/files/13939757/latest.log)
F3+C crash:
[crash-2024-01-15_22.23.13-client.txt](https://github.com/GTNewHorizons/Angelica/files/13939880/crash-2024-01-15_22.23.13-client.txt)
And this phenomenon happens when I alredy set font rendering tweaks false.

> > Actually there are many other mods
> 
> Actually, attach the full modlist (cause a debug crash F3+C) or even better - full log.
> 
> _After_ that, try disabling font rendering tweaks in Angelica.

**Comment by AnrDaemon** [comment]
Can you try to run your pack with Java8?

**Comment by M3MEMonster** [comment]
> Can you try to run your pack with Java8?

I have tried. No effects.

**Comment by AnrDaemon** [comment]
Do you mean by "no effects" that the issue is not reproducible without lwjgl3ify?

**Comment by M3MEMonster** [comment]
> Do you mean by "no effects" that the issue is not reproducible without lwjgl3ify?

No, it still here.

**Comment by AnrDaemon** [comment]
IDK, I'm unable to reproduce. It's either not a DragonAPI itself, or not related to it at all.

**Comment by M3MEMonster** [comment]
> IDK, I'm unable to reproduce. It's either not a DragonAPI itself, or not related to it at all.

Yes, DragonAPI itself will not cause anything. But no one will use ONLY DragonAPI itself as well. Try to add any of Reika's mods(ChromatiCraft, ElectriCraft, ReactorCraft, RotaryCraft...) Once some mods require some methods from DragonAPI, this phenomenon will happen.

**Comment by AnrDaemon** [comment]
> But no one will use ONLY DragonAPI itself as well.

That's simply not true. I do. Because a server mod requires it.
