### ISSUE TITLE
Conflict with Dynamic Light kind mod and a little problem with Botania

### ISSUE THREAD

**Issue by M3MEMonster** [GTNewHorizons/Angelica#196]
### Mod Version

1.0.0-alpha14

### Java Version

Java 21

### Bug Report

When I use SmoothEntityLight-3.0.4-MC1.7.10 with angelica, it will crash when you into a world.
[crash-2024-01-16_11.10.21-client.txt](https://github.com/GTNewHorizons/Angelica/files/13944973/crash-2024-01-16_11.10.21-client.txt)
And angelica may cause Botania to refresh its config wholly every time when you startup game, so whatever you modified will refresh to default.

### Mod List or GTNH Pack Version

Already in crash report.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by PlayfulPiano** [comment]
ooh SEL looks really well done, definitely would hope to see that fixed or implemented in some capacity in the future as part of angelica

**Comment by mitchej123** [comment]
[SEL is using a parallel stream](https://github.com/LakMoore/Smooth-Entity-Light/blob/1.7.10/SmoothEntityLights/src/main/java/lakmoore/sel/client/FMLEventHandler.java#L82-L93) which is triggering chunk updates off of the main thread - which is going to cause troubles with Angelica. 

[Related notes here.](https://github.com/GTNewHorizons/Angelica/blob/9b6e781a7ceafc4da00e93ec025ed0b2ac03444e/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/ChunkRenderManager.java#L641-L655)
