### ISSUE TITLE
ChunkRenderRebuilder Errors

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/Angelica#197]
### Your GTNH Discord Username

alongstringofnumbers

### Mod Version

alpha 14

### Java Version

Java 19

### Bug Report

I saw the following errors in the log while using alpha 14, https://gist.github.com/ALongStringOfNumbers/c3faaa9e564fb13b8ded219229df11b3

This is somewhat similar to #181 maybe, but I did not crash this time, just had the log populated with the errors

### Mod List or GTNH Pack Version

2.4.0 with backlported 5u, Lanth, Twilight Forest, and all required updated mods.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
I haven't dug into the mjtjp relocation issues yet but my going assumption is thread safety issues
