### ISSUE TITLE
Space Station Rendering Issue

### ISSUE THREAD

**Issue by ege-eker** [GTNewHorizons/Angelica#199]
### Mod Version

1.0.0-alpha14

### Java Version

Java 21

### Bug Report

I have tried many different dimensions, it only occured on space stations

**while angelica is present**
![image](https://github.com/GTNewHorizons/Angelica/assets/109546570/2e9a4b75-fac0-4c6c-84cc-7a2fd258590d)
![image](https://github.com/GTNewHorizons/Angelica/assets/109546570/4a20af5e-17ce-42aa-9f4d-c56328eac22f)

**without angelica:**
![image](https://github.com/GTNewHorizons/Angelica/assets/109546570/3e307cc2-be6c-4348-9ccf-a946c975dd94)

### Mod List or GTNH Pack Version

GTNH 2.5.1 + Angelica 1.0.0-alpha14 + SU 2.0.9

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by JellyJones** [comment]
Disabling Use GL State Cache fixes the issue in Alpha18

**Comment by mitchej123** [comment]
Try again with the latest alpha (28+) and reopen if still an issue.

**Comment by NickBjurstrom** [comment]
I'm having this issue currently while using newest Angelica (alpha30)

Current mod versions:
+unimixins-all-1.7.10-0.1.16
angelica-1.0.0-alpha30
CodeChickenCore-1.2.0
gtnhlib-0.2.9
hodgepodge-2.4.6

Screenshot of issue:
![2024-02-28_07 33 53](https://github.com/GTNewHorizons/Angelica/assets/77812731/fd91ae8e-f443-4a28-8ee9-a4bb11be227c)
