### ISSUE TITLE
Game crash when using NEI (not enough items) 

### ISSUE THREAD

**Issue by Arne222** [GTNewHorizons/Angelica#201]
### Your GTNH Discord Username

Arne || arne_4345

### Mod Version

angelica-1.0.0-alpha13-sources

### Java Version

Java 8

### Bug Report

All of the mods listed below work but when i try to use NEI(not enough items) my game crahses. When it crashes there is nog log create, no crash report only these 2 "fml logs" Since nei was not listed in the list of Incompatibilities i thought i should make a crash report. If anyone sees/knows a fix feel free to dm me (discord name listed above)
[fml-junk-earlystartup.log](https://github.com/GTNewHorizons/Angelica/files/13950622/fml-junk-earlystartup.log)
[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/13950623/fml-client-latest.log)

### Mod List or GTNH Pack Version

CodeChickenlib 1.2.1
gtnhlib 0.2.1
angelica-1.0.0-alpha13-sources
Damage indicators mod 3.3.2
LOTRmod v36.15
LunatriusCore- 1.7.10-1.1.2.21
MousebindFix-1.0(1.7.10)
Mousetweaks-2.4.4-mc1.7.10
replaymod-1.7.10-2.5.2
Schematica-Mod-1.7.10
Worldedit-forgemc1.7.10-6.1.1
Xaeros_Minimap_FP21.10.16_Forge_1.7.10
XaerosWorldMap_1.14.1.12_Forge_1.7.10
Better+HUD+by+NukeDuck+[1.7.10][1.3.5]
Its-the-Little-Things-Mod-1.7.10
journeymap-1.7.10-5.1.4p2-unlimited

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Arne222** [comment]
Forgot to mention i am using NotEnoughItems-1.7.10-1.0.5.120-universal latest curseforge download.

**Comment by mitchej123** [comment]
I'd suggest using the gtnh nei fork https://github.com/GTNewHorizons/NotEnoughItems/releases. I doubt the original is compatible with our ccc/ccl.

Also it looks like you're using the sources in your mod list?  You want the normal jar for Angelica, not one of the ones with a qualifier.

**Comment by chochem** [comment]
doesnt look angelica related. you are just missing corechickencore it seems
