### ISSUE TITLE
Crash whilst rendering OpenBlocks Sky Block

### ISSUE THREAD

**Issue by divine-ray** [GTNewHorizons/Angelica#202]
### Your GTNH Discord Username

divine-ray

### Mod Version

2.5.1+Angelica

### Java Version

Java 8

### Bug Report

https://mclo.gs/fw07RVk
Game crashed at the attempt of rendering offscreen sky blocks (in pdim if that matters)
Game stayed open, presumably due to bettercrashes, but alternated between blackscreen and regular game at frame intervals.
Kinda surprised me that the txt crash log and the main issue tracker opened automatically lmao

### Mod List or GTNH Pack Version

GTNH 2.5.1, Angelica, updated NEI, worldedit. 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try again on a newer alpha
