### ISSUE TITLE
[EnderIO] Farming Station not rendering

### ISSUE THREAD

**Issue by Marvun** [GTNewHorizons/Angelica#203]
### Your GTNH Discord Username

ichheissemarvin

### Mod Version

1.0.0-alpha14

### Java Version

Java 19

### Bug Report

So the block itself isn't rendering except the inner portal-like part.
![image](https://github.com/GTNewHorizons/Angelica/assets/56234595/374aa3bd-1c63-4d34-bdd3-a8ac9fc928f3)

### Mod List or GTNH Pack Version

GTNH 2.5.1 with updated angelica dependencies +
matmos-1.7.10-35.4.8
FullscreenWindowed-1.7.10-1.3.0b
FancyBlockParticles-1.7.x-2.4.1
FTBUtilities-1.1.0-GTNH
FTBLib-1.0.19-GTNH

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by KAMKEEL** [comment]
Can confirm this is an issue! @Marvun 
Also, just ran into the issue. Removed `Angelica` and it resolved. Even tried `Angelica` on older versions of EnderIO and the issue persists.

**Comment by mitchej123** [comment]
Try again with the latest alpha (28+) and reopen if still an issue.

**Comment by KAMKEEL** [comment]
Still opening @mitchej123 just tested it out with just Angelica + EnderIO

**Comment by PlayfulPiano** [comment]
can also confirm this is still happening with alpha35.

**Comment by mitchej123** [comment]
Are you using the latest nh eio version?

**Comment by PlayfulPiano** [comment]
no, i'm not using nightly versions outside of nei and angelica required prereqs

**Comment by mitchej123** [comment]
I believe this has been fixed eio side
