### ISSUE TITLE
Food nutrition preview not animated

### ISSUE THREAD

**Issue by Marvun** [GTNewHorizons/Angelica#204]
### Your GTNH Discord Username

ichheissemarvin

### Mod Version

1.0.0-alpha14

### Java Version

Java 19

### Bug Report

With angelica the nutrition preview when holding food is not animated.
With Angelica:

https://github.com/GTNewHorizons/Angelica/assets/56234595/2a4149a9-15bd-4e36-b4cc-6630e5ad0396

Without:

https://github.com/GTNewHorizons/Angelica/assets/56234595/cd5af203-820f-46b7-a8ac-cd7062804421

### Mod List or GTNH Pack Version

GTNH 2.5.1 with updated angelica dependencies +
matmos-1.7.10-35.4.8
FullscreenWindowed-1.7.10-1.3.0b
FancyBlockParticles-1.7.x-2.4.1
FTBUtilities-1.1.0-GTNH
FTBLib-1.0.19-GTNH

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Pistonight** [comment]
This feels HUD caching related

**Comment by Marvun** [comment]
> This feels HUD caching related. does it happen with HUD caching off?

I tested it with version 16, where it still exists. By disabling HUD caching, the problem does not appear anymore.
