### ISSUE TITLE
Rendering/Coloring issues caused by Fluid Patterns in Interfaces

### ISSUE THREAD

**Issue by Marvun** [GTNewHorizons/Angelica#205]
### Your GTNH Discord Username

ichheissemarvin

### Mod Version

1.0.0-alpha14

### Java Version

Java 19

### Bug Report

When holding shift to display the item, that the pattern is for i encountered some strange behaviors:

https://github.com/GTNewHorizons/Angelica/assets/56234595/dd452e25-6fb6-4fec-9dcc-2eed50351feb

When the pattern is in the hotbar, the interface flickers in the color of the fluid drop from the pattern. When the pattern is in the inventory, "random" items get displayed with the same color as the drop. Depending on where the pattern is in the inventory, different items seem to have the issue. 

I have tried it with a different recipe, where the fluid drop has another color. The issue was the same with the respective color.

### Mod List or GTNH Pack Version

GTNH 2.5.1 with updated angelica dependencies +
matmos-1.7.10-35.4.8
FullscreenWindowed-1.7.10-1.3.0b
FancyBlockParticles-1.7.x-2.4.1
FTBUtilities-1.1.0-GTNH
FTBLib-1.0.19-GTNH

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try again with the latest alpha (28+) and reopen if still an issue.
