### ISSUE TITLE
Since 1.0.0-alpha15 BetterFPS crash on startup

### ISSUE THREAD

**Issue by quentin452** [GTNewHorizons/Angelica#207]
### Your GTNH Discord Username

imacatfr

### Mod Version

1.0.0-alpha15

### Java Version

Java 8

### Bug Report

[crash-2024-01-19_03.42.18-client.txt](https://github.com/GTNewHorizons/Angelica/files/13983615/crash-2024-01-19_03.42.18-client.txt)

### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.15
angelica-1.0.0-alpha15
BetterFps-1.0.1
gtnhlib-0.0.13

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Good call.  Better fps is not supported. Will add that to the list.  See the reasons why in legacy modding

**Comment by quentin452** [comment]
i tried on my modpack and the issue appaer even without betterFPS so idk .....

**Comment by mitchej123** [comment]
... Did you add the new dependency?

**Comment by quentin452** [comment]
a lol i have gtnhlib-0.0.13 , i should update it

**Comment by quentin452** [comment]
its work by updating it thx

**Comment by Roadhog360** [comment]
Suggestion: Please remove BetterFPS from your setup anyways. The trig functions in the game don't need to be optimized, the only way to do that is to cut corners and cause the math to have incorrect outputs sometimes.
