### ISSUE TITLE
Chests change color to a purple shade while moving around.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#208]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

1.0.0-alpha15

### Java Version

Java 21

### Bug Report

https://github.com/GTNewHorizons/Angelica/assets/3158887/6195c693-b263-4312-9f8f-e2fd6a115ec8

### Mod List or GTNH Pack Version

2.5.1
gtnhlib 0.2.1
hodgepodge 2.4.9
JustEnoughCalculation 4.0
craftingtweaks 1.0.88
fullscreenwhileinactive 1.0
fullscerenwindowed 1.3.0b
matmos v36
dynamicsurroundings 1.0.6.4
itemphysiclite 1.1.5
fpsreducer 1.10.3

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by SKProCH** [comment]
Also, signs and iron chests for me:  
![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/61b5d2b4-d21e-42ac-96a3-3b04ad5a09ae)

![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/d029e623-1c6a-417f-b3af-39ae539523bd)

**Comment by mitchej123** [comment]
Is this still an issue on the latest alpha? (28+)

**Comment by SKProCH** [comment]
Seems like it works fine, at least for me.

**Comment by PlayfulPiano** [comment]
Rendering seems fixed as of latest.
