### ISSUE TITLE
outside layer of skin besides the head is not rendering

### ISSUE THREAD

**Issue by justaguywhowantsminecraftmods** [GTNewHorizons/Angelica#209]
### Mod Version

1.0.0-alpha15

### Java Version

Java 8

### Bug Report

The outside layer of my skin does not render except for the head portion.

### Mod List or GTNH Pack Version

unimixins 0.1.15, gtnhlib 0.2.1, angelica 1.0.0 alpha 15

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by queeek180** [comment]
Skin layers were added in 1.8, 1.7.10 only has support for a head layer. I could not find reference to angelica adding support for the 1.8 skin format but I could be wrong about this, in which case disregard this comment.
