### ISSUE TITLE
Game crashes when logging into a server with chunk multi draw enabled

### ISSUE THREAD

**Issue by justaguywhowantsminecraftmods** [GTNewHorizons/Angelica#210]
### Mod Version

1.0.0-alpha15

### Java Version

Java 8

### Bug Report

When logging into minemen with it enabled or enabling it while already logged in the game crashes.
[latest.log](https://github.com/GTNewHorizons/Angelica/files/13985045/latest.log)

### Mod List or GTNH Pack Version

unimixins 0.1.15, gtnhlib 0.2.1, angelica 1.0.0 alpha 15

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by wahfl2** [comment]
This may not fix it, but make sure you have up to date drivers from the [Intel website].(https://www.intel.com/content/www/us/en/download/776137/intel-7th-10th-gen-processor-graphics-windows.html)

**Comment by ah-OOG-ah** [comment]
java 1.8.0_u51... please update it.

**Comment by bombcar** [comment]
> java 1.8.0_u51... please update it.

That just means curse.

**Comment by justaguywhowantsminecraftmods** [comment]
> java 1.8.0_u51... please update it.

uhhh... how?

**Comment by Pxx500** [comment]
> > java 1.8.0_u51... please update it.
> 
> uhhh... how?

if you're using curse then go to the discord help channel and use !install command for more information on how to not use curse.
If you are not using curse, there should be a setting in the launcher that allows you to choose another java installation, for more information go to the discord help channel.

**Comment by bombcar** [comment]
> > java 1.8.0_u51... please update it.
> 
> uhhh... how?

To be precise, for GTNH curse will “eventually” work but it may have problems downloading. But if you’re on GTNH you can run it on Java 21 and get some additional benefits like better garbage collection. Unlikely to fix this particular issue, however. Java 21 requires prism or multimc.

**Comment by justaguywhowantsminecraftmods** [comment]
are you guys talking about the curseforge launcher? If so I'm just using the default Minecraft launcher

**Comment by bombcar** [comment]
> are you guys talking about the curseforge launcher? If so I'm just using the default Minecraft launcher

yeah, that would also use 8_u51 as that was the version of Java shipped with 1.7.10.

Highly recommend trying prism or multimc for various reasons, especially since it lets you modify/mess with mods easier. But; the bug remains.

**Comment by Roadhog360** [comment]
Newer versions of Minecraft launcher actually started using Java 8u202
