### ISSUE TITLE
Toxic Everglades Dimension Render Issue

### ISSUE THREAD

**Issue by SudeKun** [GTNewHorizons/Angelica#215]
### Mod Version

1.0.0-alpha-15

### Java Version

Java 21

### Bug Report

I just downloaded angelica, I played a few minutes with it, whenever I enter toxic everglades I faced with major render issue. I walk a few seconds then this happens:

![2024-01-20_15 55 31](https://github.com/GTNewHorizons/Angelica/assets/67206902/a081f8fd-9906-4fb4-a7c0-9d51de7c385a)
![Screenshot 2024-01-20 155645](https://github.com/GTNewHorizons/Angelica/assets/67206902/b38ffb13-43da-4066-a97b-37e7074869e1)

This is my log file:
[crash-2024-01-20_15.56.43-client.txt](https://github.com/GTNewHorizons/Angelica/files/13998012/crash-2024-01-20_15.56.43-client.txt)

### Mod List or GTNH Pack Version

GTNH 2.5.1
Angelica 1.0.0-alpha-15

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try again with the latest alpha (28+) and reopen if still an issue.
