### ISSUE TITLE
Archaicfix Compat

### ISSUE THREAD

**Issue by Charles3541** [GTNewHorizons/Angelica#216]
### Mod Version

1.0.0-alpha15

### Java Version

Java 21

### Bug Report

https://mclo.gs/xfcF4vv

Game crashes without getting to startup phase, something related to injection?

### Mod List or GTNH Pack Version

  [✔] +unimixins-all-1.7.10-0.1.15
  [🖿] 1.7 (folder)
  [✔] AdvancedRocketry-1.7.10-1.4.0-32
  [✔] angelica-1.0.0-alpha15(1)
  [✔] appliedenergistics2-rv3-beta-6
  [✔] archaicfix-0.7.0
  [✔] buildcraft-7.1.25
  [✔] Chisel-2.9.5.11
  [✔] Chunk+Pregenerator-V1.7.10-2.5.3
  [✔] CodeChickenCore-1.2.1
  [✔] CoFHCore-[1.7.10]3.1.4-329
  [✔] ComputerCraft1.75
  [✔] craftingtweaks-mc1.7.10-1.0.88
  [✔] CraftPresence-2.2.6+1.7.10
  [✔] DynamicSurroundings-1.7.10-1.0.6.4
  [✔] Eln-1.21.7
  [✔] EnderCore-1.7.10-0.2.0.40_beta
  [✔] EnderIO-1.7.10-2.3.0.430_beta
  [✔] EnderStorage-1.7.10-1.4.7.37-universal
  [✔] Et_Futurum_Requiem-2.5.1
  [✔] ExtraCells-1.7.10-2.4.0
  [✔] fgtXray-1.7.10-1.0.8
  [✔] FTBLib-1.7.10-1.0.18.3
  [✔] FTBUtilities-1.7.10-1.0.18.3
  [✔] gtnhlib-0.2.1
  [✔] HBM-NTM-.1.0.27_X4845
  [✔] hodgepodge-2.4.9
  [🖿] ic2 (folder)
  [✔] iChunUtil-4.2.3
  [✔] industrialcraft-2-2.2.827-experimental
  [✔] LibVulpes-1.7.10-0.2.8-37-universal
  [✔] LunatriusCore-1.7.10-1.1.2.21-universal
  [✔] lwjgl3ify-1.5.13
  [✔] Mantle-1.7.10-0.3.2b
  [✔] Mekanism-1.7.10-9.1.1.1031
  [✔] MekanismGenerators-1.7.10-9.1.1.1031
  [✔] MekanismTools-1.7.10-9.1.1.1031
  [✔] MouseTweaks-2.4.4-mc1.7.10
  [✔] NotEnoughItems-2.5.7-GTNH-pre
  [✔] OpenBlocks-1.7.10-1.6
  [✔] OpenModsLib-1.7.10-0.10.1
  [✔] p455w0rdslib-1.7.10-1.0.4
  [✔] PortalGun-4.0.0-beta-6-fix-1
  [✔] ProjectE-1.7.10-PE1.10.1
  [✔] ProjectRed-1.7.10-4.7.0pre12.95-Base
  [✔] ProjectRed-1.7.10-4.7.0pre12.95-Compat
  [✔] ProjectRed-1.7.10-4.7.0pre12.95-Integration
  [✔] ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  [✔] ProjectRed-1.7.10-4.7.0pre12.95-Mechanical
  [✔] ProjectRed-1.7.10-4.7.0pre12.95-World
  [✔] TConstruct-1.7.10-1.8.8
  [✔] ThermalDynamics-[1.7.10]1.2.1-172
  [✔] ThermalExpansion-[1.7.10]4.1.5-248
  [✔] ThermalFoundation-[1.7.10]1.2.6-118
  [✔] Unifier-1.7.10-1.12
  [✔] UpToDateMod-mc1.7.10-2.4.1
  [✔] Waila-1.5.10_1.7.10
  [✔] WailaHarvestability-mc1.7.10-1.1.6
  [✔] WAILAPlugins-MC1.7.10-0.2.0-25
  [✔] Wawla-1.0.5.120
  [✔] WirelessCraftingTerminal-1.7.10-rv3-1.8.7.4b
  [✔] Xaeros_Minimap_21.10.36_Forge_1.7.10
  [✔] XaerosWorldMap_1.14.1.30_Forge_1.7.10

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Charles3541** [comment]
Fixed by disabling optimizeWorldUpdateLight config

**Comment by mitchej123** [comment]
Should have an excluded mod annotation to not mixing it AF is loaded
