### ISSUE TITLE
 codechickencore requirit versionem 1.2.0+

### ISSUE THREAD

**Issue by Inheero** [GTNewHorizons/Angelica#226]
### Your GTNH Discord Username

Inxero

### Mod Version

angelica-1.0.0-alpha16

### Java Version

Java 8

### Bug Report

[latest.log](https://github.com/GTNewHorizons/Angelica/files/14013605/latest.log)

The game says it doesn't see codechickencore version 1.2.0+. although I am using the 1.2.50 version. if I remove your mod, then everything is fine

### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.15
angelica-1.0.0-alpha16
Avaritia_1.13
ChromatiCraft+1.7.10+V33a
codechickencore -1.2.50
CodeChickenLib-1.7.10-1.2.50
DragonAPI+1.7.10+V33b
gtnhlib-0.2.1
NaturesCompass_1.7.10_1.3.1
NotEnoughItems-1.7.10-1.0.5.120-universal

![1](https://github.com/GTNewHorizons/Angelica/assets/129995913/de074b86-a704-465f-9fc5-05822eefb987)
![изображение_2024-01-22_205019735](https://github.com/GTNewHorizons/Angelica/assets/129995913/77ad4efd-1d65-456c-8fd8-c165d1f5a059)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
You clearly just renamed the jar....

```
[20:42:30] [main/DEBUG]: Injecting coremod CodeChickenCorePlugin {codechicken.core.launch.CodeChickenCorePlugin} class transformers
[20:42:30] [main/TRACE]: Registering transformer codechicken.lib.asm.ClassHeirachyManager
[20:42:30] [main/TRACE]: Registering transformer codechicken.core.asm.InterfaceDependancyTransformer
[20:42:30] [main/TRACE]: Registering transformer codechicken.core.asm.TweakTransformer
[20:42:30] [main/TRACE]: Registering transformer codechicken.core.asm.DelegatedTransformer
[20:42:30] [main/TRACE]: Registering transformer codechicken.core.asm.DefaultImplementationTransformer
```

It's missing `codechicken.lib.asm.RedirectorTransformer` which is included in the NH version of 1.2.0+; additionally you're running an old old version of NEI instead of the NH version.

**Comment by Inheero** [comment]
Well, let's start in order. I hope you will understand me because I speak English poorly.

I downloaded the latest version of gtnh and took all 3 mods from
there and I still have the same error

As for the accusation that I renamed the files, you should know that this was a version with fixes for a number of errors for my server and I just renamed the file for my server

**Comment by Inheero** [comment]
After that, I tried downloading these mods separately from curceforge DreamMasterXXL, which didn't help either.

**Comment by Roadhog360** [comment]
So this 1.2.50 is a custom build with fixes? If there's fixes to be made, you should let us know what the issues are so we can pull them into the main version of the mod.

Also most GTNH projects are posted on CurseForge and Modrinth by mitchej123, not DreamMasterXXL:
https://www.curseforge.com/members/mitchej123/projects
https://modrinth.com/user/mitchej123

If you still get the issue after redownloading the GTNH versions of the mods and removing the old version, please post the  version numbers you downloaded and remove the old version.

**Comment by mitchej123** [comment]
The log you posted is clearly _not_ derived from the 1.2.0 NH series, it doesn't have the required transformer.  Also the filename doesn't dictate the mod version, it's compiled into the mod.  I'm not supporting custom builds of CCC/CCL.  If there are appropriate fixes they should be mainlined.

**Comment by mitchej123** [comment]
As for CF, there was a small bug preventing it from being updated until the past few days, you'll have to download the mods from the github releases page as linked to in the readme.
