### ISSUE TITLE
Gui Resources Packs bugs

### ISSUE THREAD

**Issue by VIZZI-DK** [GTNewHorizons/Angelica#230]
### Your GTNH Discord Username

foxysister

### Mod Version

1.0.0-alpha15

### Java Version

Java 17

### Bug Report

Before re-entering the game, the white square in this menu was blinking
![image](https://github.com/GTNewHorizons/Angelica/assets/61440550/f55deec5-6c98-4b01-9e33-c5d4b472ca41)

### Mod List or GTNH Pack Version

[GTNHMixins/]: LoadedMods [money_ore, MineFactoryReloaded|CompatExtraBiomes, p455w0rdslib, BuildCraft|Silicon, MTRM, DynamicLights_onFire, ExtraBees, DynamicLights, DynamicLights_floodLights, CleanView, MouseTweaks, MineFactoryReloaded|CompatTwilightForest, wildcaves3, Botany, endercore, mixinbooterlegacy, MineFactoryReloaded|CompatProjRed, bspkrsCore, betterquesting, BuildCraft|Robotics, ae2stuff, mixinextras, PacketUnlimiter, elegant_networking, economy, BiomesOPlenty, ExtraUtilities, MineFactoryReloaded|CompatRailcraft, bq_standard, MineFactoryReloaded|CompatForestry, IC2NuclearControl, MineFactoryReloaded|CompatVanilla, ThermalFoundation, DynamicLights_dropItems, PowerUtils, CoFHCore, DynamicLights_entityClasses, regions, neresources, guard, Forge, ExtraTrees, DynamicLights_otherPlayers, gvc, spark, MineFactoryReloaded|CompatChococraft, AdvancedSolarPanel, BuildCraft|Energy, modtweaker2, AFSU, IC2, ae2additions, richsolarpanel, DynamicLights_creepers, MineFactoryReloaded|CompatIC2, mixingasm, netherlicious, FML, Natura, NEIAddons|Forestry, customnpcs, supersolarpanel, <CoFH ASM>, gtnhlib, itemphysic, NEIAddons|CraftingTables, NEIAddons|ExNihilo, ArmorStatusHUD, WailaHarvestability, ThermalDynamics, unimixins, fastleafdecay, beebetteratbees, NotEnoughItems, Waila, extracells, TConstruct, unimixins-compat, appliedenergistics2-core, NEIAddons, BinnieCore, BuildCraft|Core, helper, ImmersiveEngineering, NEIAddons|Developer, Genetics, mcp, unimixins-mixin, Mantle, journeymap, appliedenergistics2, jgendustry, MineFactoryReloaded|CompatAtum, MineFactoryReloaded|CompatTConstruct, MineFactoryReloaded|CompatAppliedEnergistics, inventorytweaks, MineFactoryReloaded|CompatBuildCraft, UniDict, ThermalExpansion, BuildCraft|Factory, MineFactoryReloaded|CompatThaumcraft, skinport, GraviSuite, NEIAddons|AppEng, gasstation, topplayers, MineFactoryReloaded|CompatSufficientBiomes, MineFactoryReloaded|CompatForgeMicroblock, CarpentersBlocks, MineFactoryReloaded, EnderIO, BuildCraft|Compat, wailaplugins, neiintegration, configuration, hologram, immersiveintegration, IronChest, NEIAddons|Botany, MineFactoryReloaded|CompatThermalExpansion, DynamicLights_mobEquipment, CodeChickenCore, BigReactors, bugpatch, DynamicLights_flameArrows, preloader, MineTweaker3, lwjgl3ify, gtnhmixins, spongemixins, bfcore, bugpatch-core, BuildCraft|Transport, additionalcapacitor, chisel, Forestry, ae2wct, BuildCraft|Builders, DynamicLights_thePlayer, customaddons, MineFactoryReloaded|CompatBackTools]

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try again with the latest alpha (28+) and reopen if still an issue.
