### ISSUE TITLE
score board is very transparent

### ISSUE THREAD

**Issue by justaguywhowantsminecraftmods** [GTNewHorizons/Angelica#231]
### Mod Version

1.0.0-alpha16

### Java Version

Java 8

### Bug Report

score board in minemenclub is almost fully transparent and hard to see.
![2024-01-23_17 55 44](https://github.com/GTNewHorizons/Angelica/assets/143472034/44b669ab-9a80-4ad8-8c0a-9cacbd56171b)

### Mod List or GTNH Pack Version

angelica, gtnhlib, unimixins.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Pistonight** [comment]
Seems to be related to enableFontRenderer (fixes when turned off)

**Comment by justaguywhowantsminecraftmods** [comment]
> Seems to be related to enableFontRenderer (fixes when turned off)

Thank you! This also fixed other ui bugs I was having
