### ISSUE TITLE
Angelica render hotbar as white when holding Botania Lexicon

### ISSUE THREAD

**Issue by kappa-maintainer** [GTNewHorizons/Angelica#236]
### Your GTNH Discord Username

geeky_kappa

### Mod Version

1.0.0-alpha16

### Java Version

Java 21

### Bug Report

![2024-01-26_23 11 04](https://github.com/GTNewHorizons/Angelica/assets/11038263/9559c111-0b5b-4c11-baf8-5d794a7b9394)
No related log in this case
This was happened exactly when the cover of lexicon is being rendering. Open the book or switch to another item the problem will be gone.

### Mod List or GTNH Pack Version
```
.
|____gtnhlib-0.2.1.jar
|____hodgepodge-2.4.12.jar
|____falsepatternlib-mc1.7.10-1.0.0.jar
|____ chunkapi-mc1.7.10-0.5.0.jar
|____+unimixins-all-1.7.10-0.1.15.jar
|____endlessids-mc1.7.10-1.5-beta0002.jar
|____BaublesExpanded-2.1.4.jar
|____lwjgl3ify-1.5.14.jar
|____Botania+r1.8-249.jar
|____angelica-1.0.0-alpha16.jar
```

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Does this happen with his coaching disabled?  If so try alpha 17

**Comment by kappa-maintainer** [comment]
Still white in alpha 17 and started glitching. Which config option is "his coaching"?

**Comment by ALongStringOfNumbers** [comment]
I think that should be "HUD Caching"

**Comment by kappa-maintainer** [comment]
Not working, but glitching is gone

**Comment by mitchej123** [comment]
lol mobile auto correct fail.  Yes HUD Caching -- what does it look like with it disabled?

**Comment by kappa-maintainer** [comment]
![2024-01-27_11 44 28](https://github.com/GTNewHorizons/Angelica/assets/11038263/2cd718c7-704e-4510-ad1a-b9303327139a)

**Comment by Pistonight** [comment]
Appears to be related to enableFontRenderer
