### ISSUE TITLE
Crashed while breaking a conduit of Ender IO

### ISSUE THREAD

**Issue by FSO3H** [GTNewHorizons/Angelica#237]
### Mod Version

alpha17

### Java Version

Java 17

### Bug Report

https://mclo.gs/e0QC044
This issue was not found in single player games.
The savefile in the server was migrated in GTNH2.3.0

### Mod List or GTNH Pack Version

GTNH2.5.1-Java17

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Should be fixed in recent alphas
