### ISSUE TITLE
Strong fog around the bedrock

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/Angelica#238]
### Your GTNH Discord Username

skproch

### Mod Version

angelica-1.0.0-alpha17.jar

### Java Version

Java 21

### Bug Report

After y <= 25 the fog starts abruptly
The lower the y, then lower is visibility. Around bedrock I can't see anything in 2 block away from me.

https://github.com/GTNewHorizons/Angelica/assets/29896317/4607503a-1db5-4960-bcfc-3f572eb62347

It might be worth making it possible to adjust the strength of this effect, since being near the bedrock becomes almost impossible due to visibility.

Also, seems like fog culling works weirdly.

### Mod List or GTNH Pack Version

GTNH 2.5.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Did this happen on older versions?

**Comment by SKProCH** [comment]
Did you mean older versions of Angelica?

**Comment by SKProCH** [comment]
On angelica 1.0.0-alpha1 there is no abruptly starting fog in y=25, but visibility still quite low:


https://github.com/GTNewHorizons/Angelica/assets/29896317/4e08a9c5-0adc-45cc-b24d-9fdfb72711ac

**Comment by Dynamiczbee** [comment]
I don't know if anyone else can second this but I'm no longer getting this fog on alpha29 with GTNH 2.5.1.

**Comment by SKProCH** [comment]
Still has on alpha29. 

![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/b39ad3bf-90a2-45f1-b99e-cea244bee0f4)

**Comment by SKProCH** [comment]
As it turns out - this is not a bug, but a Optifine feature that needs to be implemented

**Comment by SKProCH** [comment]
Also, in some cases in different height fog overlay became inverted.

https://github.com/GTNewHorizons/Angelica/assets/29896317/0a90a2c9-3086-4331-b0ea-b36fd9da82a4

Still can't figure out conditions.

**Comment by SKProCH** [comment]
Works fine, thanks!
