### ISSUE TITLE
Crashed while mining obsidian after updating from alpha12

### ISSUE THREAD

**Issue by Ghostdesu** [GTNewHorizons/Angelica#241]
### Your GTNH Discord Username

ghostdesu

### Mod Version

1.0.0-alpha17

### Java Version

Java 17

### Bug Report

https://mclo.gs/xLd6p2G

### Mod List or GTNH Pack Version

GTNH2.5.1-Java17 + BetterQuesting 3.5.4 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Need a full log, this isn't sufficient.

**Comment by Ghostdesu** [comment]
Where would I get one?

**Comment by Pistonight** [comment]
in `.minecraft/logs`
