### ISSUE TITLE
The game won't start.

### ISSUE THREAD

**Issue by 167OSS** [GTNewHorizons/Angelica#244]
### Mod Version

1.0.0-alpha18

### Java Version

Java 8

### Bug Report

[crash-2024-01-28_19.26.41-client.txt](https://github.com/GTNewHorizons/Angelica/files/14075833/crash-2024-01-28_19.26.41-client.txt)

### Mod List or GTNH Pack Version

![`A2JVP)XX(G$2PI75A1L}`H](https://github.com/GTNewHorizons/Angelica/assets/78334210/61c8ada0-5b16-4a31-86a5-5c8126d6b651)
![K`IDCN(%$UYM@M(}F)H}JF8](https://github.com/GTNewHorizons/Angelica/assets/78334210/1fadc3c5-48d0-41b4-ac99-0b9ecb025cba)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Pistonight** [comment]
> SplashProgress has detected a error loading Minecraft.
This can sometimes be caused by bad video drivers.
We have automatically disabeled the new Splash Screen in config/splash.properties.
Try reloading minecraft before reporting any errors.

Have you tried?
