### ISSUE TITLE
TerraFirmaCraft+ crashes upon game loading

### ISSUE THREAD

**Issue by eggplantedd** [GTNewHorizons/Angelica#248]
### Your GTNH Discord Username

argo._

### Mod Version

1.0.0-alpha18

### Java Version

Java 8

### Bug Report

https://mclo.gs/oqaiVXg

### Mod List or GTNH Pack Version

![image](https://github.com/GTNewHorizons/Angelica/assets/96150927/7d83436d-93ce-49ff-aa24-089c806b4ff1)

And Forge 10.13.4.1614. I've tried to isolate it as much as possible.

Whilst I've seen similar issues submitted of people getting into the game and it crashing, not seen with TerraFirmaCraft+.

[CurseForge download page](https://legacy.curseforge.com/minecraft/mc-mods/terrafirmacraftplus/files/3779230) (Source code available as an attached file to each download.)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
```
Caused by: java.lang.NoSuchFieldError: field_149760_C
	at com.dunk.tfc.Blocks.Vanilla.BlockCustomLeaves.func_149646_a(BlockCustomLeaves.java:186)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4334)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
```

```
Intermediate Name	field_149760_C
Mapped Name	minY
```
