### ISSUE TITLE
bug with xaerominimap's entity radar

### ISSUE THREAD

**Issue by wangyu2333333** [GTNewHorizons/Angelica#250]
### Mod Version

alpha 18

### Java Version

Java 8

### Bug Report

When angelica alpha18 and xaerominimap21.10.41 are enabled at the same time, if the entity radar of xaerominimap always displays the icon, it will cause the interface of some mod to be misaligned in some situations, such as lotr's Alignment bar

### Mod List or GTNH Pack Version

LOTRReworked-1.3.1
Xaeros_Minimap_21.10.41_Forge_1.7.10.jar
XaerosWorldMap_1.14.1.31_Forge_1.7.10.jar
+unimixins-all-1.7.10-0.1.15.jar
angelica-1.0.0-alpha18.jar
gtnhlib-0.2.2.jar

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try again with the latest alpha (28+) and reopen if still an issue.
