### ISSUE TITLE
#260 breaks iris in gtnh 336

### ISSUE THREAD

**Issue by aheirman** [GTNewHorizons/Angelica#266]
### Mod Version

alpha 22

### Java Version

Java 20

### Bug Report

Without using _**a**_ shader, but with enabling Iris, alpha 22 breaks text rendering in menu and in game, each character becomes blocky.
I assume you want Iris bug reports, but not bugs related to a shader, if not feel free to close it :)

### Mod List or GTNH Pack Version

nightly 336

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [x] This issue is not shader related  (they aren't ready yet for testing)

**Comment by aheirman** [comment]
it appears to also occur on alpha 21 with iris?

**Comment by mitchej123** [comment]
> This issue is not shader related (they aren't ready yet for testing)

Shaders, shader mod.  Anything shader related is not ready unless you want to track it down and fix it.  The iris backport is disabled by default for a reason.
