### ISSUE TITLE
game breakdown

### ISSUE THREAD

**Issue by L-Temple** [GTNewHorizons/Angelica#270]
### Your GTNH Discord Username

L-Temple

### Mod Version

1.0.0-alpha23

### Java Version

Java 8

### Bug Report

[crash-2024-02-05_20.38.54-client.txt](https://github.com/GTNewHorizons/Angelica/files/14165875/crash-2024-02-05_20.38.54-client.txt)

### Mod List or GTNH Pack Version

update:+unimixins-all-1.7.10-0.1.15,CodeChickenLib-1.2.1,CodeChickenCore-1.2.1,hodgepodge-2.4.20,gtnhlib-0.2.3.
add:archaicfix-0.7.0,FoamFix-1.7.10-universal-1.0.4,mobs-no-render-1.7.10-05,falsepatternlib-mc1.7.10-1.0.0,InputFix-1.7.10-v6,NotEnoughCharacters-1.7.10-1.5.2,OmniOcular-1.7.10-1.0build103,RightProperGUIScale-mc1.7.10-2.1.0,ServerUtilities-2.0.11,SmoothFont-1.7.10-1.15.3,spark-1.10.19-forge1710,Torcherino-1.7.10-2.2s,TwistSpaceTechnology-0.4.14-2.5.1fitted,worldedit-forge-mc1.7.10-6.1.1-dist

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Should be fixed in recent alphas
