### ISSUE TITLE
Strange NEI Lighting Bug

### ISSUE THREAD

**Issue by KAMKEEL** [GTNewHorizons/Angelica#274]
### Your GTNH Discord Username

kamkeel

### Mod Version

1.0.0-alpha23

### Java Version

Java 17

### Bug Report

There seems to be a weird issue with Angelica where in NEI random items begin to black out with odd assortments of items being rendered. I can be simple small phrases that will black out even normal items (not special/plain). I'm not too sure how to narrow this down, but it does not happen when Angelica is not installed on the exact same setup.

Before Angelica
![2024-02-09_04 02 07](https://github.com/GTNewHorizons/Angelica/assets/28842281/b9647e06-715e-40a9-888f-29fb3ec437b0)
![2024-02-09_04 05 28](https://github.com/GTNewHorizons/Angelica/assets/28842281/e08b552b-d6e3-413a-832a-72cf401f2c29)

After Angelica:
![2024-02-09_04 04 18](https://github.com/GTNewHorizons/Angelica/assets/28842281/1ec2316a-f1f1-4e79-a967-a66ac9a6fd6a)
![2024-02-09_04 04 28](https://github.com/GTNewHorizons/Angelica/assets/28842281/fcafba9a-2b20-44ad-9b34-fb10e200d458)
![2024-02-09_04 05 32](https://github.com/GTNewHorizons/Angelica/assets/28842281/1df6733f-f241-4af1-8932-42960cb3757f)
![2024-02-09_04 08 47](https://github.com/GTNewHorizons/Angelica/assets/28842281/7b7b1794-79cc-4a4a-9a0a-11cb0a96d317)

### Mod List or GTNH Pack Version

  [✔] +unimixins-all-1.7.10-0.1.15
  [🖿] 1.7 (folder)
  [✔] 4Space-4.1.9
  [✔] AbyssalCraft-1.7.10-1.9.1.3-FINAL
  [✔] Aether2
  [✔] angelica-1.0.0-alpha23
  [✔] AnimationAPI-1.7.10-1.2.4
  [✔] AppleCore-3.2.11
  [✔] AppleMilkTea2-1.7.10_2.9n
  [✔] appliedenergistics2-rv3-beta-312-GTNH
  [✔] Aquaculture-1.7.10-1.2.6.21
  [✔] archaicfix-0.7.0fork7
  [✔] Back In Slime-1.7.10-3.1.6
  [✔] backpack-2.0.1-1.7.x
  [✔] Better+HUD+by+NukeDuck+[1.7.10][1.3.5]
  [✔] Better-Furnaces
  [✔] BetterSprinting  MC-1.7.10  v1.1.3
  [✔] BiblioCraft[v1.11.6][MC1.7.10]
  [✔] BiomesOPlenty-1.7.10-2.1.0.2308-universal
  [✔] Born in a Barn 1.7.x
  [✔] Botania-1.10.6-GTNH
  [✔] bugtorch-1.2.11
  [✔] campfirebackport-1.7.10-1.10.1
  [✔] Cheese-Mod-4.3
  [✔] chisel-2.13.5-Kam
  [✔] ChunkPurge-1.7.10-2.1
  [✔] CleanView-1.7.10-v2
  [✔] CodeChickenCore-1.2.1
  [✔] CoFHCore-[1.7.10]3.1.4-329
  [✔] Color-Blocks-Plus-1.0
  [✔] CoreTweaks-1.7.10-0.3.3.2+nomixin
  [✔] coroutil-1.7.10-1.1.6
  [✔] CosmeticArmorReworked-1.7.10-v6b
  [✔] CraftHeraldry+1.1.3
  [✔] CraftingPillars-1.7.x-1.6.1
  [✔] creativecore-1.4.0-GTNH
  [✔] custommainmenu-1.11.0
  [✔] CustomMobSpawner+3.3.0
  [✔] CustomNPC-Plus-1.9-beta3.1
  [✔] Damage-Indicators-Mod-1.7.10
  [✔] Decocraft-2.4.2_1.7.10
  [✔] doorsoplenty-1.0
  [✔] DrZharks MoCreatures Mod v6.3.2
  [✔] EnchantFix
  [✔] endercore-0.3.1
  [✔] EnderIO-2.6.4
  [✔] Et_Futurum_Requiem-2.5.1-custom
  [✔] eternalfrost-2.0b6
  [✔] ExtendedPotions-MC1.7.10-1.2
  [✔] ExtraTiC-1.7.10-1.4.6
  [✔] extrautilities-1.2.12
  [✔] falsepatternlib-mc1.7.10-1.0.0
  [✔] FlatSigns-1.7.10-universal-2.1.0.19
  [✔] FoamFix-1.7.10-universal-1.0.4
  [✔] fossilsarcheology-7.3.2
  [✔] FpsReducer-mc1.7.10-1.10.3
  [✔] GalacticraftCoreAll-1.7-3.0.12.505
  [✔] GardenStuff-1.7.10-1.7.0
  [✔] gilded-games-util-1.7.10-2.0
  [✔] grapplemod-1.7.10-v10
  [✔] gtnhlib-0.2.2
  [✔] Hats-4.0.1
  [✔] HealthBar-1.7.10-1.0.2-11
  [✔] HexWool-1.7.10-0.4.2.16
  [✔] hodgepodge-2.4.20
  [✔] iChunUtil-4.2.3
  [✔] INpureCore-1.2.0-GTNH
  [✔] inventorytweaks-1.6.2
  [✔] IronBackpacks-1.7.10-1.2.20
  [✔] IronChest-6.0.75
  [✔] IvToolkit-1.2.1
  [✔] journeymap-1.7.10-5.1.4p2-unlimited
  [✔] llibrary-1.5.1-1.7.10
  [✔] Locks-1.0.0
  [✔] LunatriusCore-1.2.0-GTNH
  [✔] lwjgl3ify-1.5.15-kam
  [✔] mam-1.7.10-1.0.2
  [✔] Mantle-0.4.1
  [✔] MCA-1.7.10-5.2.2-universal
  [✔] MicdoodleCore-1.7-3.0.12.505
  [✔] MineFactoryReloaded-[1.7.10]2.8.1-174
  [✔] moredyes-1.7.10-1.0.8
  [✔] MorePlayerModels-Plus-3.2
  [✔] MoShiz-1.7
  [✔] MowziesMobs-1.2.99
  [✔] MrCrayfishFurnitureModv3.4.7(1.7.10)
  [✔] MutantCreatures-1.7.10-1.4.9
  [✔] Natura-2.6.0
  [✔] neiaddons-1.12.14.40-mc1.7.10
  [✔] netherlicious-3.2.8
  [✔] nhlib-1.7.10-2.0.11
  [✔] nhtech-1.7.10-1.0.7
  [✔] NoMoreRecipeConflict-0.3(1.7.10)
  [✔] notenoughIDs-1.5.5
  [✔] NotEnoughItems-1.7.10-2.1.12-GTNH-universal
  [✔] NotEnoughResources-1.7.10-0.1.0-128
  [✔] OnlinePicFrame+v1.0+mc1.7.10
  [✔] OpenBlocks-1.9.1-GTNH
  [✔] OpenModsLibs-0.10.9
  [✔] Pam's HarvestCraft 1.7.10Lb
  [✔] PlayerAPI-1.4.4
  [✔] PlugEditor-1.1
  [✔] PluginMod-5.2
  [✔] PlugLog
  [✔] PotionCore
  [✔] ProjectRed-1.7.10-4.7.0pre12.95-Base
  [✔] ProjectRed-1.7.10-4.7.0pre12.95-Integration
  [✔] Psychedelicraft-1.5.2
  [✔] RadixCore-1.7.10-2.1.3-universal
  [✔] ReAuth-1.7.10-Forge-4.0.3
  [✔] RedstoneArsenal-[1.7.10]1.1.2-92
  [✔] ResourceLoader-MC1.7.10-1.3
  [✔] RopeBridge-v1.3-mc1.7.10
  [✔] Schematica-1.10.0-GTNH
  [✔] SilentGems-1.7.10-1.3.14-172
  [✔] simplecore-1.7.10-1.1.1.3
  [✔] simpleores-1.7.10-1.6.1.4
  [✔] SimplyJetpacks-MC1.7.10-1.5.3
  [✔] SkyForge-Beta 2.2.2
  [✔] SolarFlux-1.7.10-0.8b
  [✔] spark-1.9.19-forge1710
  [✔] SpiceOfLife-mc1.7.10-1.3.11
  [✔] TConstruct-1.11.11-GTNH
  [✔] Thaumcraft-1.7.10-4.2.3.5
  [✔] thaumcraftneiplugin-1.7.10-1.7a
  [✔] TheElysium-1.7.x-1.0.3
  [✔] TheKitchenMod-1.3.23-1.7.2-10
  [✔] ThermalExpansion-[1.7.10]4.1.5-248
  [✔] ThermalFoundation-[1.7.10]1.2.6-118
  [✔] TwilightForest-2.5.3
  [✔] UniDict-1.7.10-2.9.2
  [✔] UpToDateMod-mc1.7.10-2.3.11
  [✔] Waila-1.7.0
  [✔] WallpaperCraft-1.7.10-1.03
  [✔] WanionLib-1.9.0
  [✔] weaponmod-1.14.3
  [✔] zip_search
  [✔] Zoocraft+Discoveries+1.7.10-1.1.0
  [✔] Ztones-1.7.10-2.2.1
  [✔] zume-0.13.2

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by LekKit** [comment]
Can also confirm this with only upstream OpenComputers & GTNH NEI installed. After viewing certain item tabs in NEI, some weird dark shade is applied to the GUI, the world rendering gets weird too. It keeps this way even after exiting to main menu.

**Comment by mitchej123** [comment]
Does this still happen with alpha 28+?

**Comment by KAMKEEL** [comment]
Yep @mitchej123 still happening on Alpha 28+
