### ISSUE TITLE
MCPF: Extended HD module crashes with CoFHCore at launch

### ISSUE THREAD

**Issue by Flanisch** [GTNewHorizons/Angelica#278]
### Your GTNH Discord Username

albient

### Mod Version

1.0.0-alpha23

### Java Version

Java 17

### Bug Report

Having CoFHCore loaded and having MCPF's extended_hd module enabled, causes the game to crash at launch.
[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/14231299/fml-client-latest.log)

Replacing CoFHCore with CoFHLib doesn't crash the game at all. Even with a full GTNH 2.5.1 instance that only has StevesAddons disabled (since it's the only mod that depends specifically on the core), the pack launches completely fine when CoFHCore is replaced with CoFHLib.

### Mod List or GTNH Pack Version

- Angelica 1.0.0-alpha23
- CoFHCore 3.1.4
- GTNHLib 0.2.1
- lwjgl3ify 1.5.7
- UniMixins 0.1.14

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by jss2a98aj** [comment]
From having debugged some conflicts with NotFine (also embeds MCPF) this involves the font portion of extended HD.
