### ISSUE TITLE
MCPF: Extended_HD's font renderer functionality is partly overwritten by Angelica's font renderer

### ISSUE THREAD

**Issue by Flanisch** [GTNewHorizons/Angelica#279]
### Your GTNH Discord Username

albient

### Mod Version

1.0.0-alpha23

### Java Version

Java 17

### Bug Report

When MCPF's extended_hd module and Angelica's FontRenderer both are enabled, hd fonts (provided by a resource pack such as Dynamic Duo from the [GTNH wiki](https://gtnh.miraheze.org/wiki/Resource_Packs)) won't work. Instead, Minecraft's default font is rendered.

When only extended_hd is enabled, hd fonts work correctly.

### Mod List or GTNH Pack Version

Angelica 1.0.0-alpha23
GTNHLib 0.2.1
lwjgl3ify 1.5.7
UniMixins 0.1.14

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
MCPF is disabled by default and not ready; enough with the issues until it's enabled by default and ready for testing; unless you're planning to submit a fix.

**Comment by Flanisch** [comment]
Fair enough, I am aware it's not the focus atm, but I thought I should at least report what I found out. Maybe adding a disclaimer for MCPF on the bug report template would help. After all, I asked in `#github-discussion` before submitting tickets.

But at least most features of mcpf actually seem to work fine, including connected textures. Which is a nice thing to have working.

**Comment by mitchej123** [comment]
We're finishing up the sodium backport related bugs, threading issues, stutters, other errors; then we'll move on to shaders and MCPF, although anyone's welcome to submit fixes, I'm not personally going to focus on them until the other bugs have been cleaned up.

When things are enabled by default in the config is when they're ready for bug reports.
