### ISSUE TITLE
Quantum Force Transformer effect rendering issue

### ISSUE THREAD

**Issue by Tree-er233** [GTNewHorizons/Angelica#292]
### Your GTNH Discord Username

tree_er

### Mod Version

1.0.0-Alpha26

### Java Version

Java 8

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

![image](https://github.com/GTNewHorizons/Angelica/assets/110247896/5c11e132-f5ce-49d1-80eb-f006a18d5edd)
https://mclo.gs/cdqwj7g

### Mod List or GTNH Pack Version

GTNH2.5.1 with
Hodgepodge 2.4.4
CodeChickenCore 1.2.0
CodeChickenLib 1.2.0
Angelica 1.0.0-alpha26
gtnhlib 2.3.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Is this still an issue with alpha 28+?

**Comment by Tree-er233** [comment]
> Is this still an issue with alpha 28+?

alpha28 still has this issue

**Comment by Tree-er233** [comment]
This issue no longer occurs in 2.6.0.
