### ISSUE TITLE
Render Distance does not go above 16

### ISSUE THREAD

**Issue by PhantomCloak** [GTNewHorizons/Angelica#293]
### Mod Version

1.0.0-alpha27

### Java Version

Java 8

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

When I'm trying to set render distance anything above 16 it does not have effect I tried on my both Windows Nvidia machine and OSX machine same behaviour persist.

Reproduction Steps
1) Create/Join World
2) Set render chunk distance to anything above 16
3) Effects does not apply when re-open video settings render distance back to 16

Additional Details:
Hardware: M1 Macbook 
OS: Sonoma 14.1.1
Java Version: 1.8.0_372 aarch64 Zulu JDK

### Mod List or GTNH Pack Version

Mods: https://github.com/PhantomCloak/MinecraftForgeServer/tree/1.7.10

List:
backport5160-1.1m
Angelica
AI-Improvements
Applied Energistics 2
ArchaicFix
Biomes O' Plenty
BiomeTweaker
Born in a Barn 1.7.x
Chisel
Chocolate Quest
Chunk Purge
CodeChicken Core
CrashGuard
Dynamic Surroundings
Ender IO
EnderCore
Et Futurum Requiem
FalsePatternLib
FoamFix
FPS Reducer
Grappling hook mod
Gravestone
GTNH Lib
Hbm's Nuclear Tech
Immersive Engineering
Iron Chest
JourneyMap
Leaf Culling
legacyjavafixer-1.0
Mantle
Mouse Tweaks
Natura
Neat
Netherlicious
netherportalfix-mc1.7.10-1.1.0
NotEnoughItems
The OreSpawn Mod
Pam's HarvestCraft
PathfinderTweaks
Realistic Terrain Generation
redirectionor-1.7.10-1.2
Roguelike Dungeons
Squidless
WorldBorder
Vein Miner
UniMixins
Tinkers' Construct
Thaumcraft

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by MellowArpeggiation** [comment]
This is due to a check in Nuclear Tech Mod that sets the render distance back down below 16 if Optifine is not installed to prevent crashes. Angelica is now included in this check in the latest release.

**Comment by PhantomCloak** [comment]
I can confirm that issue related to HBM Nuclear Tech Mod and seems like it can be changed through it's config files.

**Comment by timb8g** [comment]
Hello,
I am playing GTNH 2.6.1 with Java 20 on a Mac and I am facing the same issue.
Reder distance over 16 has no effect.

I dont h ave HBM Nuclear Tech installed I think. No additional mods to v2.6.1

Is there a solution for this issue?

Thank you a lot.

**Comment by Caedis** [comment]
@timb8g Already fixed in dev; temp solution is disable pollution rendering in one of the gregtech config files

**Comment by timb8g** [comment]
fixed my issue. Thank you.
