### ISSUE TITLE
Holoinventory HUD breaks from Angelica 1.0.0-alpha23, reverting to alpha 22 fixes the issue

### ISSUE THREAD

**Issue by SilearFlare** [GTNewHorizons/Angelica#299]
### Mod Version

1.0.0-alpha23 to alpha 27

### Java Version

Java 8

### Graphics Card Vendor

AMD/ATI

### Bug Report

In an empty instance with only Angelica and Holoinventory (and dependency mods) installed, Holoinventory refuses to output its HUD when looking at any chest. Downgrading to angelica Alpha 22 fixes the issue. Default configs are applied and this should be easily reproducible with the mentioned modlist.

### Mod List or GTNH Pack Version

All the mods required to run Angelica and Holoinventory together in an otherwise `empty` instance:

Angelica (alpha23 to 27)
Holoinventory (2.4.3-GTNH)
NEI (2.5.13-GTNH)
Unimixins (0.1.16)
CCCore & CCLib(1.21)
GTNHlib (0.21)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by brandyyn** [comment]
![image](https://github.com/GTNewHorizons/Angelica/assets/11356565/6d99de96-a320-4efe-9dbd-43b277c2fd92)

**Comment by SilearFlare** [comment]
I will take the opportunity to specify that this specfically happens with the GTNH version of HoloInventory. Using the original unforked version with any version of angelica ([HoloInventory-1.7.10-1.9.1124)](https://legacy.curseforge.com/minecraft/mc-mods/holoinventory/files/2290760) likewise "fixes" this issue.
![15](https://github.com/GTNewHorizons/Angelica/assets/5557920/ffcdeb1d-d6b5-4ec9-a7c2-c4e7c14ead11)
(pictured: angelica 24 and holoinventory 1.9.1124)
I am guessing something between angelica alpha 22 and angelica alpha 23 broke something along with holoinventory's gtnh fork.

**Comment by brandyyn** [comment]
@mitchej123 latest angelica, holo inventory, hodgepodge and gtnhlib
https://github.com/GTNewHorizons/Angelica/assets/11356565/d45de815-4ef0-495a-8836-6b634fc510a5
![image](https://github.com/GTNewHorizons/Angelica/assets/11356565/1da9124e-b38e-4187-92c5-0b444d620da0)

**Comment by mitchej123** [comment]
@brandyyn next time post some context so I know what you're trying to show in the video.

Anyway - someone else reported it as stuttering and it's HUD caching related.   Unlikely to be fixed easily.

**Comment by BritishCynic** [comment]
You can indeed prevent this by disabling HUD Caching, but your FPS tanks considerably.
