### ISSUE TITLE
Readme refers to Angelica as an “Angle” rather than an Angel  

### ISSUE THREAD

**Issue by WyattTheSkid** [GTNewHorizons/Angelica#30]
Angelica is a classy lady who deserves to be refer as an Angel rather than an Angle :P
(Jokes aside there is a typo in the readme that is all)

**Comment by mitchej123** [comment]
It's an actual quote.

**Comment by mitchej123** [comment]
![image](https://github.com/GTNewHorizons/Angelica/assets/1894689/4f653e3b-d347-4516-90e4-c6ffca50397c)

**Comment by WyattTheSkid** [comment]
Didn’t know it was intentional lol. Definitely a funny little inside joke though.

**Comment by glowredman** [comment]
Maybe a "[sic!]" is needed to avoid confusion :P

**Comment by vovaksenov** [comment]
Yes, its like the 3rd or 4th time this comes up at least lol
