### ISSUE TITLE
Config graphic error

### ISSUE THREAD

**Issue by erialsan** [GTNewHorizons/Angelica#300]
### Your GTNH Discord Username

Keierialsan

### Mod Version

Alpha27

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

![image](https://github.com/GTNewHorizons/Angelica/assets/151856104/71b75877-6231-40b8-bbed-c32161925a2c)
As you can see, the bug occurs on the config screen (even in world selection)

### Mod List or GTNH Pack Version

Angelica + premise alone, even with some mods from the GTNH team.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by justaguywhowantsminecraftmods** [comment]
disabling "Batch drawScreen fonts" in the config fixed this for me. I think its something with intel graphics

**Comment by mitchej123** [comment]
Interesting.

I plan on looking into adding some intel driver workarounds, in the mean time it might be worth trying coretweaks and see if that helps at all.

**Comment by erialsan** [comment]
> 設定で「バッチdrawScreenフォント」を無効にすると、これを修正しました。インテルグラフィックスを使ったものだと思います
We have improved it there.
When entering the world, Core Tweaks is a must since it is Intel Graphics. However, even when Core Tweaks was used, there was no improvement.

**Comment by Dynamiczbee** [comment]
Can confirm this is still happening in alpha 29, GTNH 2.5.1 w/ Java 20.

**Comment by Dynamiczbee** [comment]
Seems to have been fixed for me now w/ alpha 32, can anyone else double check here?

**Comment by erialsan** [comment]
Still occurring in Alpha33.

**Comment by AnrDaemon** [comment]
> disabling "Batch drawScreen fonts" in the config fixed this for me. I think its something with intel graphics

What is this setting name in config? I can't access ingame configuration due to this bug.

**Comment by justaguywhowantsminecraftmods** [comment]
> > disabling "Batch drawScreen fonts" in the config fixed this for me. I think its something with intel graphics
> 
> What is this setting name in config? I can't access ingame configuration due to this bug.

Just edit the actual config file. Change Batch draws screen fonts to false

**Comment by AnrDaemon** [comment]
> Could not find the string
> "Batch draws screen fonts"

…

**Comment by AnrDaemon** [comment]
Turned out, the mod settings were lost due to the change in configuration file name.
Setting `B:enableFontRenderer=false` back resolved both this and #46 issues.

**Comment by erialsan** [comment]
According to my acquaintance, this problem existed at the time of Optifine.
The incompatibility of Intel drivers with Minecraft is persistent, I wish I had known about this before buying Minecraft...

**Comment by erialsan** [comment]
G　　　O　　　D

**Comment by ah-OOG-ah** [comment]
are you still having this issue in the latest alpha?

**Comment by justaguywhowantsminecraftmods** [comment]
> are you still having this issue in the latest alpha?

no it was fixed in one of the previous releases
