### ISSUE TITLE
[alpha27] Crash on opening video settings in options.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#302]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

1.0.0-alpha27

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

On game start, whenever I open the "video settings" menu (either while in a world or in the main menu), it causes the below crash. Haven't launched angelica since v15 for reference, so I was wanting to check out how it was running after a few alphas have gone by.

[crash-2024-02-15_20.42.09-client.txt](https://github.com/GTNewHorizons/Angelica/files/14304166/crash-2024-02-15_20.42.09-client.txt)
[crash-2024-02-15_20.43.25-client.txt](https://github.com/GTNewHorizons/Angelica/files/14304167/crash-2024-02-15_20.43.25-client.txt)
[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/14304171/fml-client-latest.log)
[latest.log](https://github.com/GTNewHorizons/Angelica/files/14304172/latest.log)

### Mod List or GTNH Pack Version

GTNH 2.5.1
angelica 1.0.0-alpha27
NEI-GTNH 2.5.17
CodeChickenCore 1.2.1
gtnhlib 0.2.1
hodgepodge 2.4.9
JustEnoughCalculation 4.0
CraftingTweaks 1.0.88
FullscreenWhileInactive 1.0.0
FullscreenWindowed 1.3.0b
matmos 36
DynamicSurroundings 1.0.6.4
ItemPhysicLite 1.1.5
FPSReducer 1.10.3

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
I'd remove the angelica-options.json and relaunch

**Comment by PlayfulPiano** [comment]
> I'd remove the angelica-options.json and relaunch

tried this with alpha28 and still crashes https://mclo.gs/ejKvGYE

**Comment by mitchej123** [comment]
Maybe options.txt then - one of the video settings isn't compatible with the current version it seems

**Comment by PlayfulPiano** [comment]
Yeah that's what fixed it, although noticing some settings don't seem to be configurable atm? e.g., Ambient Occlusion.

**Comment by mitchej123** [comment]
I haven't paid much attention to settings, make an issue for it
