### ISSUE TITLE
OpenComputers robot rendering issues

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/Angelica#303]
### Your GTNH Discord Username

skproch

### Mod Version

1.0.1-alpha27

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Chest and held items are shown white through blocks. When looking at robot all screen will turn white.

https://github.com/GTNewHorizons/Angelica/assets/29896317/a81f62ba-f6ee-454b-81b2-5e4c682abb9f

### Mod List or GTNH Pack Version

GTNH 2.5.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Does it happen with the GL State Manager disabled?

**Comment by SKProCH** [comment]
> Does it happen with the GL State Manager disabled?

What does you mean by GL State Manager? 

This setting?  
![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/a1dc8518-0b08-4573-b93f-107558da0c74)

If yes, it helps partially. There is no white screen when pointing to robot, and robot renders weirdly in other way:  
![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/dba20063-bc7b-4d0f-909e-b319b86bdf4a)

**Comment by JuanICasareski** [comment]
Same setup here, with GL state manager disabled it doesn't bug as bad.

But when you have it in your hand it bugs the HUD

![image](https://github.com/GTNewHorizons/Angelica/assets/66040481/d3887338-56a1-4ed4-90ca-a2cbf9cb5acc)

**Comment by Dynamiczbee** [comment]
![2024-02-24_21 59 15](https://github.com/GTNewHorizons/Angelica/assets/48137022/949dfac2-7fe5-407f-b840-21e1be3ff1e2)

Can confirm this is still happening in alpha 29 alongside J20 and GTNH 2.5.1. 
Also, when holding the robot it increases the Journey Map minimap to half my screen?

**Comment by mitchej123** [comment]
lololol that's hilarious

GL state leakage I'd guess... or a wayward transform/scale

**Comment by Dynamiczbee** [comment]
> ![2024-02-24_21 59 15](https://private-user-images.githubusercontent.com/48137022/307563238-949dfac2-7fe5-407f-b840-21e1be3ff1e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MzA4MzQsIm5iZiI6MTcwODgzMDUzNCwicGF0aCI6Ii80ODEzNzAyMi8zMDc1NjMyMzgtOTQ5ZGZhYzItN2ZlNS00MDdmLWI4NDAtMjFlMWJlM2ZmMWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDAzMDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNzNiM2QwZmExNGQyMTZjOGVhY2U5NTNhNGQ3NTBjNjYwZDY1OTEwZmJhMDE4ZWFlYmQyZmM0Mjg2NmM0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xrQMGHbLjOTIf7fezFuimQNz8VwuN13zWCmi8OAbGZo)
> 
> Can confirm this is still happening in alpha 29 alongside J20 and GTNH 2.5.1. Also, when holding the robot it increases the Journey Map minimap to half my screen?

Large minimap is fixed by disabling the GL State Cache option, however the rendering of the inworld TE still isn't fixed.

**Comment by SKProCH** [comment]
Yep, this is partially fixed now, not not fully:

![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/a7a1dde4-947f-4bb3-9e41-f4118af0de97)

Chests still opaque, animation of robot floating and red line in the middle updates one time at second:

https://github.com/GTNewHorizons/Angelica/assets/29896317/61acd0a6-79d9-46b0-8c9b-37b966da91b3

Text inside robot is still partially unreadable:

![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/a89b56a5-03d9-4574-b465-d4d3d0a7897d)
