### ISSUE TITLE
Alpha27 and newer breaks HBM's Nuclear Tech Mod

### ISSUE THREAD

**Issue by Crimento** [GTNewHorizons/Angelica#307]
### Your GTNH Discord Username

crimento

### Mod Version

1.0.0-alpha28

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Alpha 27 and newer breaks rendering of items from [HBM's Nuclear Tech Mod](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT)

If you put some of those items in the inventory, whole rendering pipeline goes crazy.

Test on Alpha28: [Logs](https://mclo.gs/19YwOAC), [Video](https://github.com/GTNewHorizons/Angelica/assets/8221822/a32c0cb0-bccb-4803-837e-44b4c5824628) (same on Alpha27)

Test on Alpha26 [Logs](https://mclo.gs/7ptOI2j), [Video](https://github.com/GTNewHorizons/Angelica/assets/8221822/85c0b2d5-f340-49d8-b471-51e2d1000445)

Reproducible with minimum amount of mods

### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.16.jar
angelica-1.0.0-alpha28.jar
CodeChickenCore-1.2.1.jar
CodeChickenLib-1.2.1.jar
gtnhlib-0.2.4.jar
HBM-NTM-.1.0.27_X4859.jar
hodgepodge-2.4.27-pre.jar
lwjgl3ify-2.0.0-alpha-7.jar
NotEnoughItems-2.5.13-GTNH-pre.jar

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Try with some combination of the following and let me know if any of them fix it
1) GL State Manager Disabled
2) Batch Font Renderer Disabled
3) HUD Caching Disabled

**Comment by Crimento** [comment]
@mitchej123 thanks for the fast response.

No effect with `enableFontRenderer=false` and `enableHudCaching=false`.
There are no options related to GL State Manager in angelica.cfg

disabling ingame "Use GL State Cache" partially fixes rendering in the world, but not inventory issues. Some items are breaking the font rendering, some items break UI rendering completely (tried with both enabled/disabled font renderer and hud caching)

![image](https://github.com/GTNewHorizons/Angelica/assets/8221822/ac72867f-0c99-4953-b209-6c8591c6f77e)
![image](https://github.com/GTNewHorizons/Angelica/assets/8221822/15486091-cd43-4a00-90ed-2b63e18269e7)

also the mod is in active development, maybe there's something that can be implemented on mod side as well to improve compatibility

**Comment by Crimento** [comment]
@mitchej123 looks fine with alpha 31 now :)

although SmoothFont is now completely broken and not working even with disabled font renderer

**Comment by mitchej123** [comment]
I'm not expecting compat with smoothfont unless someone adds it or I get really bored.
