### ISSUE TITLE
Crashing on Alpha28

### ISSUE THREAD

**Issue by Nohtell** [GTNewHorizons/Angelica#308]
### Your GTNH Discord Username

Nohtell

### Mod Version

GTNH 2.5.1

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Updated GTNHLib and Algeica now it keeps crashing

### Mod List or GTNH Pack Version

latest log and crash report

[latest.log](https://github.com/GTNewHorizons/Angelica/files/14321797/latest.log)

https://pastebin.com/CnmYhsAx

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by PhantomCloak** [comment]
I got same issue on my side with latest Angelica (29) and GTNHLib 0.2.7. It might have some relation with NEI since disabling it causes similar crash log to #322. I suspect also my NEI might be out of date so I'll try if that's the case.

### Hardware: 
MacOS M1

### Java Version:
Zulu OpenJDK 8

### Graphics Card Vendor
Apple

### Mod List
```
Mods:
  [✔] [1.7.10]Treecapitator-universal-2.0.4 (1)
  [✘] +unimixins-all-1.7.10-0.1.15.jar (disabled)
  [✔] +unimixins-all-1.7.10-0.1.16-dev
  [🖿] 1.7 (folder)
  [✔] AIImprovements-1.7.10-0.0.1b19-dev
  [✘] angelica-1.0.0-alpha26.jar (disabled)
  [✔] angelica-1.0.0-alpha29-dev
  [✔] AppleCore-mc1.7.10-3.1.1
  [✔] appliedenergistics2-rv3-beta-6
  [✔] archaicfix-0.7.0
  [✔] backport5160-1.1m
  [✔] BiomesOPlenty-1.7.10-2.1.0.2308-universal
  [✔] BiomeTweaker-1.7.10-2.0.182
  [✔] Born in a Barn 1.7.x
  [✔] Chisel-2.9.5.11
  [✔] chocolateQuest-1.7.10-1.1d
  [✔] ChunkPurge-1.7.10-2.1
  [✔] CodeChickenCore-1.2.1
  [✔] CoFHCore-[1.7.10]3.1.4-329
  [🖿] config (folder)
  [✔] Dockerfile
  [✔] DynamicSurroundings-1.7.10-1.0.6.4
  [✔] EnderCore-1.7.10-0.2.0.40_beta
  [✔] EnderIO-1.7.10-2.3.0.430_beta
  [✔] Et_Futurum_Requiem-2.5.1
  [✔] falsepatternlib-mc1.7.10-1.0.0
  [✘] Flan.s.Mod-1.7.10-4.10.0.jar (disabled)
  [✔] Flans_Mod_Ultimate_Stability_Edition-1.57
  [✘] FoamFix-1.7.10-universal-1.0.4.jar (disabled)
  [✔] FpsReducer-mc1.7.10-1.10.3
  [✔] grapplemod-1.7.10-v10
  [✔] GraveStone Mod 0.7.10.3
  [✔] greggen-mc1.7.10-0.0.3
  [✘] gtnhlib-0.2.3.jar (disabled)
  [✔] gtnhlib-0.2.7-dev
  [✘] HardcoreDarkness-MC1.7.10-1.7.jar (disabled)
  [✔] HBM-NTM-.1.0.27_X4859
  [✔] HungerOverhaul-1.7.10-1.0.0.jenkins104
  [✔] immersivecavegen-1.2g-hotfix5
  [✔] ImmersiveEngineering-0.7.7
  [✔] IronBackpacks-1.7.10-1.2.20
  [✔] ironchest-1.7.10-6.0.62.742-universal
  [✔] journeymap-1.7.10-5.1.4p6-unlimited
  [✔] LeafCulling-mc1.7.10-1.1.0.dirty
  [✔] legacyjavafixer-1.0
  [✔] Mantle-1.7.10-0.3.2b
  [✔] Mekanism-1.7.10-9.1.1.1031
  [✔] MouseTweaks-2.4.4-mc1.7.10
  [✔] natura-1.7.10-2.2.1a2
  [✔] Neat 1.0-1
  [✔] netherlicious-3.2.8
  [✔] netherportalfix-mc1.7.10-1.1.0
  [✘] NotEnoughItems-2.5.17-GTNH.jar (disabled)
  [✔] Ore-Spawn-Mod-1.7.10
  [✔] Pam's HarvestCraft 1.7.10Lb
  [✔] PathfinderTweaks-1.7.10-1.0.13
  [✔] redirectionor-1.7.10-1.2
  [✔] roguelike-1.5.5
  [✔] RTG-1.7.10-1.1.1.7
  [✔] SkinPort-1.7.10-v10d
  [✔] squidless-1.7.10-0.6.1
  [✔] TConstruct-1.7.10-1.8.8
  [✔] Thaumcraft-1.7.10-4.2.3.5
  [✔] ThermalDynamics-[1.7.10]1.2.1-172
  [✔] ThermalExpansion-[1.7.10]4.1.5-248
  [✔] ThermalFoundation-[1.7.10]1.2.6-118
  [✔] UniDict-1.7.10-2.9.2
  [✔] VeinMiner-1.7.10-0.36.0.496+28a7f13
  [✔] WorldBorder-Forge-1.0.2
  [✔] worldedit-forge-mc1.7.10-6.1.1-dist
  ```

Log with NEI:
https://pastebin.com/cqm3gPj3

Log without NEI:
https://pastebin.com/cHXJr0S5

**Comment by PhantomCloak** [comment]
Now I tried to disable all mods except Angelica, GTHNLib and UniMixin to figure out if it's due to another mod but no luck still got crash with exceptions in the log. 

Here is my crash log
https://pastebin.com/0BxAC7jf

**Comment by Caedis** [comment]
Can you try disabling legacyjavafixer?
