### ISSUE TITLE
Some settings aren't currently configurable in alpha28.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#310]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

1.0.0-alpha28

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

was comparing my options.txt file due to an earlier crash issue and saw some settings aren't listed inside video settings. Ones I saw included:
- advanced occlusion
- advanced opengl
- "showInventoryAchievementHint" (whatever that is)

### Mod List or GTNH Pack Version

gtnh 2.5.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
> advanced opengl

This is generally buggy and I wouldn't want it around anyway.  Unclear on the others, will let @jss2a98aj chime in.

**Comment by jss2a98aj** [comment]
I am not sure why "showInventoryAchievementHint" would be under video settings, but if it was in vanilla we may need to add it. I can second "advanced opengl" being incredibly buggy. I am not sure why "advanced occlusion" isn't configurable. It may have been an oversight when the Sodium style menu was added, or it was also deemed too buggy to keep in.
