### ISSUE TITLE
game crashes when enabling use chunk multi draw

### ISSUE THREAD

**Issue by justaguywhowantsminecraftmods** [GTNewHorizons/Angelica#312]
### Mod Version

1.0.0-alpha28

### Java Version

Java 8

### Graphics Card Vendor

Intel iGPU

### Bug Report

when enabling "use chunk multi draw" in video settings the game crashes. I'm guessing this is some incompatibility with intel integrated graphics
[latest.log](https://github.com/GTNewHorizons/Angelica/files/14325725/latest.log)

### Mod List or GTNH Pack Version

angelica, unimixins, gtnh lib

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by AnrDaemon** [comment]
Try the suggestion from https://github.com/GTNewHorizons/Angelica/issues/373#issuecomment-1991928261
