### ISSUE TITLE
White textures

### ISSUE THREAD

**Issue by mts2200** [GTNewHorizons/Angelica#320]
### Your GTNH Discord Username

mts2200

### Mod Version

alpha29

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

I upgraded from alpha24 to alpha29 and encountered the following problem:
![image](https://github.com/GTNewHorizons/Angelica/assets/82391229/dd62e06d-1961-40a7-a15b-41d042283e9f)
![image](https://github.com/GTNewHorizons/Angelica/assets/82391229/fbdd2392-9f14-47e3-acf0-7965cd3aabd4)

My graphics settings:
![image](https://github.com/GTNewHorizons/Angelica/assets/82391229/c48d3444-5184-49f4-b044-9b3a182d3501)
![image](https://github.com/GTNewHorizons/Angelica/assets/82391229/fc57423e-151a-4e25-9da6-bee7a46961a3)

### Mod List or GTNH Pack Version

I don't know what mods this exactly works with, but in the screenshot you can see a problem with Thaumcraft, Gadomancy, EvilCraft. This is also can be reproduced with some private mods.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
I've done plenty of thaumcraft without an issue - not sure I have any gadomancy things out there... and I definitely haven't used Evilcraft -- can you see if you can get it down to a bare minimum of items to reproduce it?

**Comment by mts2200** [comment]
I'm not sure I can minimize this list since I don't know the exact ways to reproduce it, but I'll try to find the version of Angelica with which this problem appeared.

**Comment by mts2200** [comment]
This problem starts with version alpha27 and does not exist on alpha26. I think you need to review this commits: https://github.com/GTNewHorizons/Angelica/compare/1.0.0-alpha26...1.0.0-alpha27

**Comment by mts2200** [comment]
Disabling "GL State Cache" did not help.

**Comment by mitchej123** [comment]
Interesting, pretty much everything 26 -> 27 was GLStateManager (Cache) related, and some AMD driver bug workarounds...

**Comment by Dynamiczbee** [comment]
Unsure if useful but I was unable to replicate this on GTNH 2.5.1,
