### ISSUE TITLE
crash while starting up at 100%

### ISSUE THREAD

**Issue by Ekor1st** [GTNewHorizons/Angelica#326]
### Your GTNH Discord Username

ekor1st

### Mod Version

angelica-1.0.0-alpha28

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

[crash-2024-02-20_21.07.53-client.txt](https://github.com/GTNewHorizons/Angelica/files/14387261/crash-2024-02-20_21.07.53-client.txt)
i'm new to GTNH so i believe i have all the mods' latest versions

### Mod List or GTNH Pack Version

[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/14387280/fml-client-latest.log)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Literally the same issue as #322 .....
