### ISSUE TITLE
Random chunk build failure crashes when teleporting

### ISSUE THREAD

**Issue by ItsMeGoo** [GTNewHorizons/Angelica#336]
### Your GTNH Discord Username

xgoo

### Mod Version

1.0.0-alpha30

### Java Version

Java 20

### Graphics Card Vendor

NVidia

### Bug Report

Occasionally during mid-to-long range teleportation via either commands or items, chunks will fail to render briefly before the game crashes. I've not found anything directly that triggers this, as I can execute the same teleports back and forth a few times, and it's fairly random when the chunk build will fail, but it's regular enough that this happens every few teleports. It does only happen when loading an area that contains Ender IO conduits, as it seems directly related to the conduit bundle's facade check. Removing Angelica seems to alleviate the problem however, so it does seem directly related to the sodium chunk build process and not just an EIO bug.

Relevant crash log: [crash-2024-02-27_00.37.48-client.txt](https://github.com/GTNewHorizons/Angelica/files/14415019/crash-2024-02-27_00.37.48-client.txt)

Latest client log: [fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/14415041/fml-client-latest.log)

### Mod List or GTNH Pack Version

GTNH 2.5.1 stable

+unimixins-all-1.7.10-0.1.16
angelica-1.0.0-alpha30
gtnhlib-0.2.7
ForgeRelocation-0.1.2

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Impos913** [comment]
I can confirm the issue, can be reproduced.
[crash-2024-02-28_07.34.26-client.txt](https://github.com/GTNewHorizons/Angelica/files/14428910/crash-2024-02-28_07.34.26-client.txt)
