### ISSUE TITLE
Rendering issue caused by LogisticsPipes pipes and blocks

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/Angelica#345]
### Your GTNH Discord Username

impvt

### Mod Version

1.0.0-alpha30

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Logistics pipes cause black tint on blocks and items in inventory when they are placed in the inventory or chest, in NEI when searched or bookmarked and non-full blocks like chests, tanks, item labels on drawers in world when they are placed.
Also in the log it started a spam after searching for logistics pipes in NEI
[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/14437960/fml-client-latest.log)
![image](https://github.com/GTNewHorizons/Angelica/assets/36479271/42694bd2-635e-4493-8e31-9777e63d164c)
![image](https://github.com/GTNewHorizons/Angelica/assets/36479271/fbcf17b2-60a0-4ecc-855f-df711ce05d16)
![image](https://github.com/GTNewHorizons/Angelica/assets/36479271/49fc6a1c-836c-47f9-b5c4-89f3b58f4f2c)
![image](https://github.com/GTNewHorizons/Angelica/assets/36479271/407e915f-54b3-46e7-8504-e968ca3ff9f5)
![image](https://github.com/GTNewHorizons/Angelica/assets/36479271/4bfd5121-8507-4026-b2b8-c213be45fb5f)
![2024-02-28_20 07 19](https://github.com/GTNewHorizons/Angelica/assets/36479271/792b05e7-065a-4714-b483-9e43d46d4bc0)
![2024-02-28_20 07 24](https://github.com/GTNewHorizons/Angelica/assets/36479271/278a5ff6-474c-46d6-8f9f-24a2b5406c37)

### Mod List or GTNH Pack Version

GTNH 2.5.1 and:
- angelica-1.0.0-alpha30
- +unimixins-all-1.7.10-0.1.16
- CodeChickenLib-1.2.1
- CodeChickenCore-1.2.1
- gtnhlib-0.2.9
- hodgepodge-2.4.31
- zume-0.15.0
- ServerUtilities-2.0.8
- JustEnoughCalculation-1.7.10-3.8.6
- RTG-1.7.10-1.1.1.7
- ClimateControl-0.8.2
- journeymap-1.7.10-5.1.4p6-unlimited

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by EJaxx** [comment]
when disabling "new renderer", this problem disappears. 
2.6.0 + angelica-1.0.0-alpha42
![WA](https://github.com/GTNewHorizons/Angelica/assets/51190289/ecfd3614-df61-4fef-a582-4fc45330729c)
