### ISSUE TITLE
Xaeros Minimap's in-world waypoints get rendered at 20fps and are very laggy

### ISSUE THREAD

**Issue by HRudyPlayZ** [GTNewHorizons/Angelica#346]
### Your GTNH Discord Username

hrudyplayz

### Mod Version

1.0.0-alpha28

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

As you may know, Xaeros's Minimap is a minimap mod that can add waypoints in-game.
The issue is that the hotbar optimisations seem to also apply to Xaero's waypoints, as they're probably getting rendered as a HUD overlay too. Making the waypoints very laggy and display at 20fps.
It could probably be fixed by making that mixin ignore Xaero's classes.

### Mod List or GTNH Pack Version

- Angelica 1.0.0-alpha28
- GTNH Lib 0.2.9
- UniMixins 0.1.16
- Xaeros Minimap 21.10.31

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by makamys** [comment]
Sounds like a duplicate of #223

**Comment by HRudyPlayZ** [comment]
Indeed, closing the issue and moving it to the OG thread.
