### ISSUE TITLE
Tinker's Construct tools not rendering on inventory

### ISSUE THREAD

**Issue by fuckindumbfox** [GTNewHorizons/Angelica#351]
### Your GTNH Discord Username

fuckindumbfox

### Mod Version

1.0.0-alpha30

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

![image](https://github.com/GTNewHorizons/Angelica/assets/130804352/6ab77a7f-55cc-43cd-941a-83ff90ffc90f)
Title is self-explanatory, but sometimes. placing certain items next to them (or hovering over its side) makes it render. It is visible when dropped on the ground.
![image](https://github.com/GTNewHorizons/Angelica/assets/130804352/426c3190-e7c2-45fe-a765-47b93eb460f7)
![image](https://github.com/GTNewHorizons/Angelica/assets/130804352/7017c47c-21ab-4475-8b74-7bce48df96a8)

### Mod List or GTNH Pack Version

GregTech: New Horizons ver. 2.5.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by chrisstuartparry** [comment]
Friend of mine is having the same issue
