### ISSUE TITLE
StacksOnStacks stacks don't render

### ISSUE THREAD

**Issue by unicornbloods** [GTNewHorizons/Angelica#359]
### Your GTNH Discord Username

Unicorn Blood

### Mod Version

Alpha 32

### Java Version

Java 8

### Graphics Card Vendor

AMD/ATI

### Bug Report

Stacks of ingots from StacksOnStacks don't render.

### Mod List or GTNH Pack Version

Galaxy Odyssey modpack. 
Should happen with just StacksOnStacks and Angelica though 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by AstroTibs** [comment]
Without Angelica:
![2024-10-07_21 35 20](https://github.com/user-attachments/assets/7358d405-a712-45f2-a322-bac9a2ae8006)

With Angelica:
![2024-10-07_21 32 19](https://github.com/user-attachments/assets/fceb1319-ffc5-4614-bc91-fefbcd81ba35)

**Comment by Cleptomania** [comment]
Fixed with #703 should probably be in beta15 release
