### ISSUE TITLE
Angelica causes crushes at random times

### ISSUE THREAD

**Issue by Ya9yu** [GTNewHorizons/Angelica#362]
### Your GTNH Discord Username

Ya9yu

### Mod Version

1,0,0-alpha33

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

I still don’t understand when this crash occurs, sometimes it happens when I’m afk, or when I open some controller, it just happens, and also it have different potential causes, but it’s always NotFine MCPatcherForge Angelica Embeddium, here are the logs so that we can find a solution to the problem
[crash-2024-03-07_00.14.24-client.txt](https://github.com/GTNewHorizons/Angelica/files/14517315/crash-2024-03-07_00.14.24-client.txt)
[crash-2024-03-07_01.32.06-client.txt](https://github.com/GTNewHorizons/Angelica/files/14517316/crash-2024-03-07_01.32.06-client.txt)

### Mod List or GTNH Pack Version

GTNH Nighlty-372
KeyboardWizard-Legacy-Forge-1.7.10-1.0.0
ModernControlling-Forge-1.7.10-1.0.0
ModernKeyBinding-Forge-1.7.10-2.1.0-mixinless

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Ya9yu** [comment]
[crash-2024-03-07_19.28.39-client.txt](https://github.com/GTNewHorizons/Angelica/files/14527887/crash-2024-03-07_19.28.39-client.txt)
New crash log, just stood AFK

**Comment by mitchej123** [comment]
Bartworks non thread safe rendering/field access.  Will look into fixing when I'm back from my work trip
