### ISSUE TITLE
Shader pack option is not working

### ISSUE THREAD

**Issue by erialsan** [GTNewHorizons/Angelica#364]
### Your GTNH Discord Username

Keierialsan

### Mod Version

Alpha31+

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

Angelica has its own shader configuration in the config file, not Angelica's configuration since Alpha31, but the Iris function cannot be used even if that configuration is set to True. Also, there is no Iris configuration in Angelica-modules, and it cannot be used even if shaderpack is installed.

### Mod List or GTNH Pack Version

AngelicaAlpha33(Everything after 31 has been tested, the first tested being the latest version.)
GTNHlib, lwjgl3ify and Unimixins (all the latest versions, from GitHub release)
CoreTweaks-Nomixin (latest build)
Minecraft version 1.7.10

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Caedis** [comment]
Shaders will be worked on during beta

**Comment by mitchej123** [comment]
Learn to read. 
![Screenshot_20240307-071013](https://github.com/GTNewHorizons/Angelica/assets/1894689/6664a8b7-a19c-4843-8404-b52261d6d870)
