### ISSUE TITLE
Crash when opening Keybind menu with enableHudCaching=false

### ISSUE THREAD

**Issue by SilearFlare** [GTNewHorizons/Angelica#365]
### Mod Version

Alpha 33

### Java Version

Java 8

### Graphics Card Vendor

AMD/ATI

### Bug Report

Tested in an empty instance with only angelica: when setting hud caching to false (from the default true) and trying to access the keybind menu (Controls) the game will crash immediately without a log report outside of
```
[Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
```

### Mod List or GTNH Pack Version

Angelica Alpha 33 and required dependencies. Issue seems to have been active since alpha 23 (first instance of the crash happening)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Caedis** [comment]
confirmed
