### ISSUE TITLE
Crash java.lang.IllegalStateException: GbufferPrograms in weird state

### ISSUE THREAD

**Issue by tomasz-brak** [GTNewHorizons/Angelica#368]
### Your GTNH Discord Username
baron9972

### Mod Version

1.0.0-alpha29

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

[log.txt](https://github.com/GTNewHorizons/Angelica/files/14546437/log.txt)

Crashes when joining a server

### Mod List or GTNH Pack Version

GTNH 2.5.1 + Angelica + Hodgepodge 2.4.31 + GTNH lib 0.2.7

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by tomasz-brak** [comment]
I've manually compiled this version cherry picking the #354 in to release 29.  But then tested on the unchanged version and the bug persists

**Comment by mitchej123** [comment]
You check the box yet blatantly post something shader related...,.  Why?
![Screenshot_20240309-062507](https://github.com/GTNewHorizons/Angelica/assets/1894689/9657bb1f-c766-418e-ada5-f003aa4ff32a)

**Comment by tomasz-brak** [comment]
i don't have shaders on. or does that mean the config setting?
sorry

**Comment by mitchej123** [comment]
You have the iris backport module enabled, which is disabled by default.  Gbuffers is shaders.
