### ISSUE TITLE
Multi-draw indirect crashes without lwjgl3ify

### ISSUE THREAD

**Issue by wahfl2** [GTNewHorizons/Angelica#373]
### Your GTNH Discord Username

beljihnwahfl

### Mod Version

1.0.0-alpha34

### Java Version

Java 8

### Graphics Card Vendor

Intel iGPU

### Bug Report

Enabling multi-draw indirect and entering any world/server causes a crash without lwjgl3ify installed. Seemingly, this would happen regardless of setup.

https://mclo.gs/5CGAaD2

I tested the same instance + world after installing lwjgl3ify and it worked without crashing.

### Mod List or GTNH Pack Version

Only Angelica + deps

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
What OS?  

Seems like an Intel specific issue this far.... I've run multidraw on linux, with nvidia, and lwjgl2 without issue.  (I'll test it again tonight to verify it's not a regression).

**Comment by mitchej123** [comment]
It seems to currently only be reproducible on intel drivers running on windows, while using lwjgl2.  Apparently lwjgl3 disabled some checks for speed.  

The two options seem to be:
1) Disabling the check via  `-Dorg.lwjgl.util.NoChecks=true` 
2) Using Oneshot instead of Multidraw

**Comment by AnrDaemon** [comment]
> 1. -Dorg.lwjgl.util.NoChecks=true

Confirmed to be working with my setup. No more crashes with multidraw option enabled.

**Comment by justaguywhowantsminecraftmods** [comment]
> It seems to currently only be reproducible on intel drivers running on windows, while using lwjgl2. Apparently lwjgl3 disabled some checks for speed.
> 
> The two options seem to be:
> 
> 1. Disabling the check via  `-Dorg.lwjgl.util.NoChecks=true`
> 2. Using Oneshot instead of Multidraw

where do I find Dorg.lwjgl.util.NoChecks=true?

**Comment by quentin452** [comment]
-Dorg.lwjgl.util.NoChecks=true its probably a jvm arguments that you need to put

**Comment by AnrDaemon** [comment]
Yes, it is a JVM argument.
