### ISSUE TITLE
angelica render block fluid buffer

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/Angelica#377]
### Your GTNH Discord Username

Admin_XiaoMai

### Your Pack Version

nightly-374

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Actions

watch block

### Crash Report

https://paste.ubuntu.com/p/kHFc7NcDS2/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
@AdminXiaoMai Have you added any mods not included with NH by default?  If so which.

It looks like a mixin application problem, something else is asm/mixin RenderGlobal; you'll need to post the full log.

**Comment by AdminXiaoMai** [comment]
> @AdminXiaoMai Have you added any mods not included with NH by default? If so which.
> 
> It looks like a mixin application problem, something else is asm/mixin RenderGlobal; you'll need to post the full log.

There are no additional mods, and the trigger for this bug is to look at an AE2FC-enabled ME fluid buffer,which delays rendering fluids.For example, an ME fluid buffer for helium plasma

**Comment by mitchej123** [comment]
Do these mods come with GTNH now?

```
    UC    fw{c83bad6-master+c83bad64ae-dirty} [Fullscreen Windowed] ([11]FullscreenWindowed-1.7.10-gtnh-1.3.1b-java17-20.jar) 
    UC    bakadanmaku{2.0.0} [Baka Danmaku] ([1]bakadanmaku-1.7.10-2.0.0.jar) 
    UC    servertabinfo{Final-b3} [Server Tab Info] ([2]ServerTabInfo-1.7.10-Final-b3.jar) 
    UE    falsepatternlib{1.0.0} [FalsePatternLib] ([3]falsepatternlib-mc1.7.10-1.0.0.jar) 
    UC    nechar{1.5.1} [Not Enough Characters] ([6]NotEnoughCharacters-1.7.10-1.5.1.jar) 
    ```

**Comment by mitchej123** [comment]
Also, I requested a _FULL_ log, not just the crash log.

**Comment by AdminXiaoMai** [comment]
https://paste.ubuntu.com/p/gDh6X8M6S7/
