### ISSUE TITLE
Water/Lava flow not animated

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/Angelica#378]
### Your GTNH Discord Username

brandyyn

### Mod Version

n/a

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

Since Angelica V31 Lava/Water doesn't flow.

V30 is the last version in which it doesn

Speedupanimations is turned OFF(which causes this problem in older versions where it does work)

### Mod List or GTNH Pack Version

n/a

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Dream-Master** [comment]
works fine with Angelica 34

![image](https://github.com/GTNewHorizons/Angelica/assets/2970688/235efc92-be3c-4e3e-a109-46d00134ac4c)

**Comment by brandyyn** [comment]
> works fine with Angelica 34

i updated from angelica 28 to angelica 34 which is how i noticed the issue, in my pack, unfortunately it doesnt work after v30
