### ISSUE TITLE
HBM-NTM, Deco blocks not rendering.

### ISSUE THREAD

**Issue by MerrittK** [GTNewHorizons/Angelica#381]
### Mod Version

1.0.0 -alpha34

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

If sodium render is turned on, all blocks with connected textures in NTM stop rendering in the inventory.

If I turn off sodium render, machines and other things start flashing green tinted repeatedly. 

[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/14608424/fml-client-latest.log)

### Mod List or GTNH Pack Version

Unimixens-all
Angelica alpha34
CodeChickenCore
gtnhlib
HBM-NTM
Hodgepodge
NotEnoughItems
serializationisbad

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by MerrittK** [comment]
![2024-03-14_18 17 10](https://github.com/GTNewHorizons/Angelica/assets/65367913/bb60fb89-5469-43ec-9d55-092178f126bc)
Also, models turn transparent from a distance.

**Comment by MerrittK** [comment]
Actually, when I turn of sodium rendering, the game crashes.
[crash-2024-03-14_18.30.59-server.txt](https://github.com/GTNewHorizons/Angelica/files/14608569/crash-2024-03-14_18.30.59-server.txt)

**Comment by MerrittK** [comment]
The transparency has stopped happening when I deleted configs.

**Comment by Crimento** [comment]
Can confirm, still an issue with Alpha 36
![image](https://github.com/GTNewHorizons/Angelica/assets/8221822/6d31f0a5-e623-47ca-bb75-d4288e3f5755)

**Comment by MellowArpeggiation** [comment]
Connected block rendering is fixed in NTM for Angelica with this PR https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/pull/1445
