### ISSUE TITLE
Cables and pipes are shrinked while holding a soldering iron

### ISSUE THREAD

**Issue by czerwonogrodzki** [GTNewHorizons/Angelica#382]
### Your GTNH Discord Username

cier7679

### Mod Version

1.0.0-alpha34

### Java Version

Java 17

### Graphics Card Vendor

AMD/ATI

### Bug Report

![2024-03-15_00 39 08](https://github.com/GTNewHorizons/Angelica/assets/78734422/c15613d5-496a-4daf-9b83-95af2bbc7d57)
![2024-03-15_00 39 12](https://github.com/GTNewHorizons/Angelica/assets/78734422/45f53bcf-eb3c-4dec-acae-64b3d3a951b2)

### Mod List or GTNH Pack Version

GTNH 2.5.1, added ServerUtilities, WorldEdit, updated required stuff for Angelica

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
This is a feature of GT5u and working as intended.
