### ISSUE TITLE
Issue with BlockRenderer6343 NEI preview

### ISSUE THREAD

**Issue by Lyfts** [GTNewHorizons/Angelica#383]
### Your GTNH Discord Username

fakelyft

### Mod Version

1.0.0-alpha34

### Java Version

Java 21

### Graphics Card Vendor

AMD/ATI

### Bug Report

Without Angelica hovering over a block in in the preview shows its tooltip and right clicking a block shows all the valid hatches that can be placed there.
![no-angelica](https://github.com/GTNewHorizons/Angelica/assets/127234178/16aad73a-588b-4383-86dc-0e235c7de934)

With Angelica hovering over a block no longer shows the tooltip and right clicking does nothing. There is also some weird black outline around the preview.
![with-angelica](https://github.com/GTNewHorizons/Angelica/assets/127234178/ade7a95c-fd02-4619-8cb8-cc6d2c29281d)

However if you zoom so that the camera is inside a block you can interact with it again.

![angelica zoom](https://github.com/GTNewHorizons/Angelica/assets/127234178/4b46179d-269b-4903-8ff2-a1b42a4e88af)

I've tried disabling hud caching but that doesn't change it.

### Mod List or GTNH Pack Version

GTNH nightly 391 as well as BlockRenderer6343 dev env with Angelica added
Minimally reproducible modlist so far:
```
mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
FML{7.10.99.99} [Forge Mod Loader] (recompiled_minecraft-1.7.10.jar) 
Forge{10.13.4.1614} [Minecraft Forge] (recompiled_minecraft-1.7.10.jar) 
NotEnoughItems{2.5.24-GTNH} [NotEnoughItems] (NotEnoughItems-2.5.24-GTNH-dev.jar) 
CodeChickenCore{1.2.1} [CodeChicken Core] (minecraft.jar) 
appliedenergistics2-core{rv3-beta-342-GTNH} [Applied Energistics 2 Core] (minecraft.jar) 
<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
GT++_Preloader{0.5-Beta} [GT++ Preloader] (minecraft.jar) 
BWCore{0.0.1} [BartWorks ASM Core] (minecraft.jar) 
blockrenderer6343{1.1.6} [BlockRenderer6343] (blockrenderer6343-1.1.6.jar) 
Waila{1.7.1} [Waila] (waila-1.7.1-dev.jar) 
Mantle{0.4.1} [Mantle] (Mantle-0.4.1-dev.jar) 
CoFHCore{1.7.10R3.1.4} [CoFH Core] (cofh-core-69162-2388751.jar) 
TConstruct{1.11.12-GTNH} [Tinkers' Construct] (TinkersConstruct-1.11.12-GTNH-dev.jar) 
IC2{2.2.828-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.828-experimental-dev.jar) 
GalacticraftCore{3.1.1-GTNH} [Galacticraft Core] (Galacticraft-3.1.1-GTNH-dev.jar) 
GalacticraftMars{3.1.1-GTNH} [Galacticraft Planets] (Galacticraft-3.1.1-GTNH-dev.jar) 
structurelib{1.3.0} [StructureLib] (StructureLib-1.3.0-dev.jar) 
gtnhlib{0.2.10} [GTNH Lib] (GTNHLib-0.2.10-dev.jar) 
gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (unimixins-0.1.16-dev.jar) 
unimixins{0.1.16} [UniMixins] (unimixins-0.1.16-dev.jar) 
hodgepodge{2.4.35} [Hodgepodge] (Hodgepodge-2.4.35-dev.jar) 
modularui{1.1.42} [ModularUI] (ModularUI-1.1.42-dev.jar) 
appliedenergistics2{rv3-beta-342-GTNH} [Applied Energistics 2] (Applied-Energistics-2-Unofficial-rv3-beta-342-GTNH-dev.jar) 
Forestry{4.8.7} [Forestry] (ForestryMC-4.8.7-dev.jar) 
gregtech{MC1710} [GregTech] (GT5-Unofficial-5.09.45.110-dev.jar) 
gtneioreplugin{1.2.0} [GT NEI Ore Plugin GT:NH Mod] (GTNEIOrePlugin-1.2.0-dev.jar) 
YAMCore{0.6.0} [YAMCore] (Yamcl-0.6.0-dev.jar) 
tectech{5.3.34} [TecTech - Tec Technology!] (TecTech-5.3.34-dev.jar) 
bartworks{0.9.17} [BartWorks] (bartworks-0.9.17-dev.jar) 
bartworkscrossmodtgregworkscontainer{0.9.17} [BartWorks Mod Additions - TGregworks Container] (bartworks-0.9.17-dev.jar) 
miscutils{1.11.39} [GT++] (GTplusplus-1.11.39-dev.jar) 
ToxicEverglades{1.11.39} [GT++ ToxicEverglades] (GTplusplus-1.11.39-dev.jar) 
bartworkscrossmod{0.9.17} [BartWorks Mod Additions] (bartworks-0.9.17-dev.jar) 
galacticgreg{1.1.0} [Galactic Greg] (GalacticGregGT5-1.1.0-dev.jar) 
ae2fc{1.2.21-gtnh} [AE2 Fluid Crafting] (AE2FluidCraft-Rework-1.2.21-gtnh-dev.jar) 
ae2wct{1.11.1} [AE2 Wireless Crafting Terminal] (WirelessCraftingTerminal-1.11.1-dev.jar) 
neenergistics{1.5.1} [NotEnoughEnergistics] (NotEnoughEnergistics-1.5.1-dev.jar) 
mcpatcherforge{1.0.0-alpha} [MCPatcherForge] (Angelica-1.0.0-alpha34-dev.jar) 
embeddium{1.0.0-alpha34} [Embeddium] (Angelica-1.0.0-alpha34-dev.jar) 
notfine{1.0.0-alpha34} [NotFine] (Angelica-1.0.0-alpha34-dev.jar) 
angelica{1.0.0-alpha34} [Angelica] (Angelica-1.0.0-alpha34-dev.jar) 
Avaritia{1.49} [Avaritia] (Avaritia-1.49-dev.jar) 
IronChest{6.0.74} [Iron Chests] (ironchest-6.0.74-dev.jar) 
Baubles{1.0.4} [Baubles] (Baubles-1.0.4-dev.jar) 
ForgeMultipart{1.4.8} [Forge Multipart] (ForgeMultipart-1.4.8-dev.jar) 
ForgeMicroblock{1.4.8} [Forge Microblocks] (ForgeMultipart-1.4.8-dev.jar) 
McMultipart{1.4.8} [Minecraft Multipart Plugin] (ForgeMultipart-1.4.8-dev.jar) 
AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (advsolar-362768-2885953.jar) 
unimixins-mixin{0.1.16} [UniMixins: Mixin (UniMix)] (unimixins-0.1.16-dev.jar) 
unimixins-compat{0.1.16} [UniMixins: Compatibility] (unimixins-0.1.16-dev.jar) 
mixingasm{0.3} [UniMixins: Mixingasm] (unimixins-0.1.16-dev.jar) 
spongemixins{2.0.1} [UniMixins: SpongeMixins] (unimixins-0.1.16-dev.jar) 
mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (unimixins-0.1.16-dev.jar) 
gasstation{0.5.1} [UniMixins: GasStation] (unimixins-0.1.16-dev.jar) 
mixinextras{0.1.16} [UniMixins: MixinExtras] (unimixins-0.1.16-dev.jar) 
lwjgl3ify{2.0.0} [lwjgl3ify] (lwjgl3ify-2.0.0-dev.jar) 
```

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Lyfts** [comment]
After much investigation I can conclude that the whole not being able to select blocks/view their tooltips is caused by GL State Cache and functionality is restored after turning it off. 
The odd black bars are caused by font renderer, turning it off also fixes most of the ones mentioned here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15816

**Comment by mitchej123** [comment]
Interesting, I wonder what state specifically is being cached incorrectly... need to narrow that down and add a new test case

**Comment by Lyfts** [comment]
My guess is it's related to the way it unprojects https://github.com/GTNewHorizons/BlockRenderer6343/blob/38da19faf8c62e197a1bf6c03d36d2ae5342c3d3/src/main/java/blockrenderer6343/client/utils/ProjectionUtils.java#L67-L115. 
If the camera is placed above a block (no matter how high) and facing downwards the highlight and tooltip will show no matter the mouse location which does point to something being wrong with the unproject.

I also tried stealing OpenMods unproject but that yielded the same results so it might be for a different reason than https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15957.

**Comment by Lyfts** [comment]
Okay after one more round of testing I've found that the highlighting does work in some positions. It's not highlighting the block under the mouse though and the position it needs the mouse to be in shifts when rotating the multiblock.
![br-highlighting](https://github.com/GTNewHorizons/Angelica/assets/127234178/c88aa3de-77db-492b-b333-49ce47fa14cf)

Hopefully someone knows what to make of that.

**Comment by chochem** [comment]
I dont think this was ever fixed. Black outlines are still an issue on GTNH nightly 569 which uses angelica-1.0.0-beta2.

![image](https://github.com/user-attachments/assets/f0a6ffd6-3385-45c0-a5e4-f4432f76111a)

**Comment by Lyfts** [comment]
Just for note, the black bars are caused by the Angelica fontrenderer and cause black bars on multiple different NEI pages as seen here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15816

**Comment by chochem** [comment]
gonna claim its fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/528
