### ISSUE TITLE
Bio Vat Rendering Issues

### ISSUE THREAD

**Issue by NickBjurstrom** [GTNewHorizons/Angelica#387]
### Your GTNH Discord Username

Nick#7586

### Mod Version

angelica-1.0.0-alpha34

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

I'm crashing whenever I'm around Bio Vats, not even interacting, just being around them will sometimes crash my game.

Crash Log:
https://mclo.gs/6m5SSfi

fml-client-latest:
[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/14622809/fml-client-latest.log)

### Mod List or GTNH Pack Version

GTNH 2.5.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Fixed with https://github.com/GTNewHorizons/bartworks/commit/50dfbb44acdd28bc183dc58b9cd40d5ba5121685
