### ISSUE TITLE
Chisel's cobblestone blocks not rendering

### ISSUE THREAD

**Issue by Charles3541** [GTNewHorizons/Angelica#394]
### Mod Version

1.0.0-alpha35

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Blocks from chisel do not render at all, and i've noticed some HBM blocks do the same (tho i don't have any screenshots of it happening)
![thebug](https://github.com/GTNewHorizons/Angelica/assets/73392486/f32fad0d-f76f-4540-a25b-6fbfde48ec60)

### Mod List or GTNH Pack Version

  [✔] +unimixins-all-1.7.10-0.1.16
  [🖿] 1.7 (folder)
  [✔] ActuallyAdditions-1.7.10-r21
  [✔] adventurebackpack-1.7.10-0.8c
  [✔] angelica-1.0.0-alpha35.jar
  [✔] appliedenergistics2-rv3-beta-6
  [✔] archaicfix-0.7.1
  [✔] BetterAchievements-1.7.10-0.1.0
  [✔] BetterBoat-1.7.10-1.1.0
  [✔] BetterPlacement-MC1.7.10-1.0.0-1
  [✔] BigReactors-0.4.0A
  [✔] Bookshelf-1.7.10-1.0.4.187
  [✔] buildcraft-7.1.25
  [✔] Chisel-2.9.5.11
  [✔] Chunk-Pregenerator-1.7.10-4.4.2
  [✔] CodeChickenCore-1.2.1
  [✔] CoFHCore-[1.7.10]3.1.4-329
  [✔] CoFHLib-[1.7.10]1.2.1-185
  [✔] ComputerCraft1.75
  [✔] CoreTweaks-1.7.10-0.3.3.2+nomixin
  [✔] CosmeticArmorReworked-1.7.10-v7
  [✔] craftingtweaks-mc1.7.10-1.0.88
  [✔] CraftPresence-2.2.6+1.7.10
  [✔] Dynamic Lights-1.3.9a-MC1.7.10
  [✔] DynamicSurroundings-1.7.10-1.0.6.4
  [✔] EnderCore-1.7.10-0.2.0.40_beta
  [✔] EnderIO-1.7.10-2.3.0.430_beta
  [✔] EnderStorage-1.7.10-1.4.7.37-universal
  [✔] EnergyControl-1.7.10-0.3.5
  [✔] entityculling-1.6.3-mc1.7.10
  [✔] Et_Futurum_Requiem-2.5.1+nomixin
  [✔] ExtraCells-1.7.10-2.3.14b200
  [✔] extrautilities-1.2.12
  [✔] falsepatternlib-mc1.7.10-1.0.1
  [✔] FoamFix-1.7.10-universal-1.0.4
  [✔] FTBLib-1.7.10-1.0.18.3
  [✔] FTBUtilities-1.7.10-1.0.18.3
  [✔] Galacticraft-1.7-3.0.12.504
  [✔] GalaxySpace-1.7.10-1.2.15(1)
  [✔] gtnhlib-0.2.10
  [✔] HBM-NTM-.1.0.27_X4895
  [✔] hodgepodge-2.4.40
  [🖿] ic2 (folder)
  [✔] iChunUtil-4.2.3
  [✔] industrialcraft-2-2.2.827-experimental
  [✔] InventoryTweaks-1.59-unofficial-asie-1
  [✔] ironchest-1.7.10-6.0.62.742-universal
  [✔] journeymap-1.7.10-5.2.3-unlimited
  [✔] LeafCulling-mc1.7.10-1.1.0.dirty
  [✔] Loading-Progress-Bar-v1.0-mc1.7.10
  [✔] lwjgl3ify-2.0.2
  [✔] Mantle-1.7.10-0.3.2b
  [✔] mcjtylib-1.8.1
  [✔] Mekanism-Community-Edition-1.7.10-9.10.35-Core
  [✔] Mekanism-Community-Edition-1.7.10-9.10.35-Generators
  [✔] Mekanism-Community-Edition-1.7.10-9.10.35-Tools
  [✔] mobs-no-render-1.7.10-05
  [✔] modernsplash-1.7.10-1.2.1-d88da6a.dirty
  [✔] MouseTweaks-2.4.4-mc1.7.10
  [✔] NettyPatcher-0.2
  [✔] NotEnoughEnergistics-1.7.10-1.4.2
  [✔] NotEnoughItems-2.5.18-GTNH
  [✔] OpenBlocks-1.7.10-1.6
  [✔] OpenModsLib-1.7.10-0.10.1
  [✔] PortalGun-4.0.0-beta-6-fix-1
  [✔] ProjectE-1.7.10-PE1.10.1
  [✔] redirectionor-1.7.10-1.2
  [✔] rftools-4.23
  [✔] serializationisbad-1.5.2
  [✔] TConstruct-1.7.10-1.8.8
  [✔] ThermalDynamics-[1.7.10]1.2.1-172
  [✔] ThermalExpansion-[1.7.10]4.1.5-248
  [✔] ThermalFoundation-[1.7.10]1.2.6-118
  [✔] tlskincape1.7.10-1.4
  [✔] Unifier-1.7.10-1.12
  [✔] UpToDateMod-mc1.7.10-2.4.1
  [✔] Waila-1.5.10_1.7.10
  [✔] WailaHarvestability-mc1.7.10-1.1.6
  [✔] WAILAPlugins-MC1.7.10-0.2.0-25
  [✔] Wawla-1.0.5.120

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Fixed with [2.14.0-GTNH](https://github.com/GTNewHorizons/Chisel/releases/tag/2.14.0-GTNH)
