### ISSUE TITLE
Tinker's Construct related crash

### ISSUE THREAD

**Issue by dhasial** [GTNewHorizons/Angelica#408]
### Mod Version

1.0.0-alpha35

### Java Version

Java 17

### Graphics Card Vendor

AMD/ATI

### Bug Report

Breaking TCon seared bricks causes a crash. It often doesn't crash on the first blocks broken, but if you have enough seared bricks to break, it will always eventually crash. The world sometimes becomes impossible to load, even after disabling Angelica. 

- I'm not sure if this is specific to seared bricks.
- So far I've only tested this using a TCon hammer. 
 
Here's the crash log of a test world I made for this bug.
https://gist.github.com/dhasial/63e6086801e79afad4462c311dad9a7d

### Mod List or GTNH Pack Version

GTNH 2.5.1
+
WorldEdit
WorldEdit CUI Forge Edition
Enchiridion 2
UpToDateMod
Zume
Passthrough Signs
Golem Tweaks
Chunk Pregenerator
UniMixins
Super Sound Muffler: Legacy
Angelica
Connected Glass
Dynamic Surroundings
Just Enough Calculation

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Should be fixed in [1.11.12-GTNH](https://github.com/GTNewHorizons/TinkersConstruct/releases/tag/1.11.12-GTNH) +
