### ISSUE TITLE
Unable to access block behind GregTech wires and pipes

### ISSUE THREAD

**Issue by Valor760** [GTNewHorizons/Angelica#41]
### Your GTNH Discord Username

valor760

### Mod Version

1.0.0-alpha1

### Java Version

Java 17

### Bug Report

With Angelica installed, it is impossible to check the block behind GregTech cable or pipe.
Expected:
![image](https://github.com/GTNewHorizons/Angelica/assets/31585840/871162cd-126c-4c92-8423-35ff590596c8)
Actual:
![image](https://github.com/GTNewHorizons/Angelica/assets/31585840/2b1edd85-9bab-4aab-b0bf-c5f854097354)

### Mod List

GTNH 2.5.0

![image](https://github.com/GTNewHorizons/Angelica/assets/31585840/48079835-56e9-4c85-8c8f-0c2f9fb399e3)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by Valor760** [comment]
Additionally noticed, that if I stay very close to the wire, but look away, waila is still reporing as I am looking at the wire

![image](https://github.com/GTNewHorizons/Angelica/assets/31585840/032268ef-b77f-4393-806d-bcc374837844)

**Comment by unilock** [comment]
I'm having a similar issue that is likely related: I simply cannot interact with RotaryCraft Gasoline Engines. It's as if their hitbox isn't registered at all. However, collision with them still works fine. (I'm standing on one in the screenshot)

![image](https://github.com/GTNewHorizons/Angelica/assets/11802133/a5a334c8-3842-4813-8cd3-5a321f42223e)

**Comment by bombcar** [comment]
> Additionally noticed, that if I stay very close to the wire, but look away, waila is still reporing as I am looking at the wire

You’re standing “inside” the wire but it’s not registering the smaller hit box. I bet something similar could occur with hoppers. 

Crop sticks do this “normally” as part of the design.

**Comment by mitchej123** [comment]
Might be fixed by alpha9, reopen if it's not
