### ISSUE TITLE
Missing text entries for many configs

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/Angelica#412]
### Your GTNH Discord Username

chochem

### Mod Version

Angelica 1.0.0-alpha36a

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

specifically:
![image](https://github.com/GTNewHorizons/Angelica/assets/40274384/dbb2e4b7-5666-465e-b40e-37b318a2ff4b)
![image](https://github.com/GTNewHorizons/Angelica/assets/40274384/74ef8318-dbfe-4a6a-9896-edbcf096674c)
![image](https://github.com/GTNewHorizons/Angelica/assets/40274384/ac4d2b7f-a9c0-4847-b218-62b0cbcc1efd)
![image](https://github.com/GTNewHorizons/Angelica/assets/40274384/1cf4dade-a22a-48f6-a561-1f4c6ef5c0de)
![image](https://github.com/GTNewHorizons/Angelica/assets/40274384/bc105ad0-c73a-446b-92d2-d5d2468f1b72)
![image](https://github.com/GTNewHorizons/Angelica/assets/40274384/7ded32c1-a0d8-41f3-8b20-320348b1c732)
![image](https://github.com/GTNewHorizons/Angelica/assets/40274384/b67a196f-8fa0-4516-b28b-cac13c6af73d)
![image](https://github.com/GTNewHorizons/Angelica/assets/40274384/9b3cdd1b-7108-4706-9126-a9f453beaaba)
![image](https://github.com/GTNewHorizons/Angelica/assets/40274384/e72e3c3f-1015-43e4-b7bc-217a5bbd8e79)
![image](https://github.com/GTNewHorizons/Angelica/assets/40274384/d0f5306c-a1f1-40eb-9816-703e5fbd213f)

### Mod List or GTNH Pack Version

GTNH 2.6.0-beta2 with angelica updated to alpha36a

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by chochem** [comment]
still an issue

**Comment by mitchej123** [comment]
Please submit a PR, most of them you can just duplicate the name and add a .tooltip.   I added a bunch recently, some are still missing.

**Comment by chochem** [comment]
ah nice I updated to beta8 and a large amount is fixed. still open:
![image](https://github.com/user-attachments/assets/a916ef5c-8380-4735-80b7-989a3bcf130a)
![image](https://github.com/user-attachments/assets/36814768-cb41-4b5b-99e4-96e52f72aba7)
![image](https://github.com/user-attachments/assets/1208a00c-defe-49d5-b9bf-2ff90461b0e3)
![image](https://github.com/user-attachments/assets/c596e499-78e8-407d-8b6c-87afe2c49538)
![image](https://github.com/user-attachments/assets/af8d88b3-0d97-4848-9edd-e7a116373924)

not sure what you mean with the .tooltip. I certainly dont feel qualified to write descriptions here.

**Comment by mitchej123** [comment]
![image](https://github.com/user-attachments/assets/7f9b8f86-9dda-4557-b1d4-28276fc201cc)

In this example, find the entry for `options.gui_background` duplicate it, add a `.tooltip` and keep the same description unless you want to enhance it ;)
