### ISSUE TITLE
Completing Quests causes the entire game rendering (minus HUD, GUIs) to turn black.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#414]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

alpha 36a

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://github.com/GTNewHorizons/Angelica/assets/3158887/aeb67d64-9178-48c5-93d5-46090152893a

### Mod List or GTNH Pack Version

GTNH 2.5.1, other mods listed in the lastest.log link below:
https://mclo.gs/hSKnoNJ

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by chochem** [comment]
this is a problem in GTNH 2.5.1 (specifically BetterQuesting mod) and not in angelica. This has been fixed since.

**Comment by PlayfulPiano** [comment]
Oh, huh. Never had the issue earlier with 2.5.1.
