### ISSUE TITLE
[HBM 's Nuclear Tech Mod] Reeds cast an upward shadow

### ISSUE THREAD

**Issue by LoSilopante** [GTNewHorizons/Angelica#416]
### Mod Version

1.0.0 - Alpha35

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

Reeds spawned or placed have an upward casted texture:

[bugged look](https://imgur.com/aSBPNJ9)

[expected look](https://imgur.com/sNTSrM5)

### Mod List or GTNH Pack Version

Angelica 1.0.0 - Alpha35
Unimixin 0.1.17
gtnhlib 0.2.10

HBM-NTM-[1.0.27_X4895]

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by MellowArpeggiation** [comment]
This issue is related to the _Video Settings > Advanced > Use Compact Vertex Format_ option, disabling it fixes the rendering of reeds in NTM.
