### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by xronin01** [GTNewHorizons/Angelica#417]
### Mod Version

1.0.0-alpha36a

### Java Version

Java 8

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

[latest.log](https://github.com/GTNewHorizons/Angelica/files/14921586/latest.log)

### Mod List or GTNH Pack Version

angelica-1.0.0-alpha36a
gtnhlib-0.2.10
+unimixins-all-1.7.10-0.1.17

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by xronin01** [comment]
Crash continues in alpha 50
[latest.log](https://github.com/GTNewHorizons/Angelica/files/15367160/latest.log)

**Comment by mitchej123** [comment]
Android isn't supported.  If someone wants to PR compat great, but I don't have the time or setup to test it unfortunately
