### ISSUE TITLE
[HBM's Nuclear Tech Mod]Transparency issue, likely GL Blend State leak

### ISSUE THREAD

**Issue by 70000hp** [GTNewHorizons/Angelica#423]
### Your GTNH Discord Username

70000hp

### Mod Version

1.0.0-alpha35

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

https://cdn.discordapp.com/attachments/603348502637969419/1223321595637141535/image.png?ex=662be304&is=66196e04&hm=90aa1c994bd9019b2014bef2b231f5149268526f510d276db0516cc98dab06cb&
Issue happens on TESR models with multiple parts when utilizing NTM's display list implementation
Upon disabling display lists, no issue occurs with the model
From what I could tell, it is seemingly a blend state leak
I have also two API trace files with the issue, one with, and one without the issue happening
[with_error.zip](https://github.com/GTNewHorizons/Angelica/files/14968723/with_error.zip)
[without_error.zip](https://github.com/GTNewHorizons/Angelica/files/14968725/without_error.zip)

### Mod List or GTNH Pack Version

angelica-1.0.0-alpha35
+unimixins-all-1.7.10-0.1.17
gtnhlib-0.2.10
HBM-NTM-.1.0.27_X4921

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by MellowArpeggiation** [comment]
This has been resolved within HBM's Nuclear Tech Mod with this PR:
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/pull/1445
