### ISSUE TITLE
Items in HoloGlasses rotate when used with Angelica

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/Angelica#431]
### Your GTNH Discord Username

britishcynic

### Your Pack Version

2.6.0-beta3 with Angelica-a38 and HoloGlasses 2.4.4

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

This is a test of the item preview used by HoloGlasses with the now-coded bypass of HUD Caching to make the item preview not judder when the player is moving. The goal is for identical or superior functionality compared to not having Angelica loaded.

### The Reality

Example video is located at https://cdn.discordapp.com/attachments/522098956491030558/1230957764398940181/Peek_2024-04-19_20-06.mp4?ex=663535c1&is=6622c0c1&hm=512af8364796400355332053a12d37270bf7426734d4ede4e5a6823e63d2efde&

As you can see, the items rotate with the player when they should remain facing the player. In addition, the items flicker if the weapon in the player's hand intersects with them.

Disabling HUD Caching prevents HoloGlasses working at all in identical fashion to disabling HoloGlasses with the keybind.

### Your Proposal

Fix it so that the items correctly display and preferably fix the flicker.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hallucinogender** [comment]
![image](https://github.com/GTNewHorizons/Angelica/assets/107995536/d94377c8-d9cc-4e7d-98f8-814d61f0a997)
Can confirm, same issue here. Nightly 443 with Angelica updated to alpha 48.

**Comment by Caedis** [comment]
Unable to replicate the issues with rotating in a dev environment

**Comment by Dream-Master** [comment]
https://cdn.discordapp.com/attachments/1091759598836400228/1233010228442828810/image.png?ex=662b89c2&is=662a3842&hm=be58a5b3f79f9646c4a628ea622f5f403484b1066f5b5ff7a2aa384aafd3d24e&
https://cdn.discordapp.com/attachments/1091759598836400228/1233010288585080862/image.png?ex=662b89d1&is=662a3851&hm=53589058ebdcb40890b2f112dd5c99b21857795fd2fd536b3a1992d247b83e2c&
https://cdn.discordapp.com/attachments/1091759598836400228/1233010342507053106/image.png?ex=662b89dd&is=662a385d&hm=b874c786a86f053355089518a5307e1fd5fda3815e87340f074f4f7db88ccd54&

**Comment by Dream-Master** [comment]
look like the icons have a front side but no back side a
it have to do with east west north and south i guess (because i switched the orientation of the chest)
when i look to north i see coins when i look to south side i dont see them

**Comment by Caedis** [comment]
What OS and GPU vendor?

**Comment by Caedis** [comment]
@mitchej123 @eigenraven  can you try and replicate this on your end? Might be a windows only issue

**Comment by BritishCynic** [comment]
This happens to me on Manjaro + NVIDIA

**Comment by eigenraven** [comment]
I have now seen a new variant in the latest angelica master+latest holoinv release

https://github.com/GTNewHorizons/Angelica/assets/1017004/8a4e78a6-4ef0-4f1a-8749-47997970e616

**Comment by eigenraven** [comment]
Nevermind, the slowly spinning items are just a default config that's disabled in gtnh
