### ISSUE TITLE
Animations are broken or laggy.

### ISSUE THREAD

**Issue by Valor760** [GTNewHorizons/Angelica#44]
### Your GTNH Discord Username

valor760

### Mod Version

1.0.0-alpha1

### Java Version

Java 17

### Bug Report

I don't know if it is really a bug, or expected behavior of "optimization" of this mod, but animations from blocks is laggy, or there is no animation at all in some cases. See videos below.

### Multiblock Centrifuge
Expected:

https://github.com/GTNewHorizons/Angelica/assets/31585840/0805d477-53db-44c1-aefa-00db9d41c2b3

Actual:

https://github.com/GTNewHorizons/Angelica/assets/31585840/192329cd-8288-4d29-a598-68a82df27fd4

### AE Controller
Expected:

https://github.com/GTNewHorizons/Angelica/assets/31585840/00e362c1-d106-43f8-b258-49c1b4b23bdc

Actual:

https://github.com/GTNewHorizons/Angelica/assets/31585840/59768c45-ea3e-4b8f-8c9d-151f2cab3e6f

### Mod List

GTNH 2.5.0

![image](https://github.com/GTNewHorizons/Angelica/assets/31585840/31e51ec6-0f76-4d4d-be2d-9c89ed6fbd57)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by lordIcocain** [comment]
Can you try without fastcraft?
<img width="346" alt="image" src="https://github.com/GTNewHorizons/Angelica/assets/62835225/6f271a87-f83d-4dd0-b09f-0b6e5e6eed15">

**Comment by Valor760** [comment]
@lordIcocain - Sorry, forgot to remove it.

Still, all the issues (linking here #40 #41  #42   ) persist after deleting fastcraft:
![image](https://github.com/GTNewHorizons/Angelica/assets/31585840/4a407a7b-4dec-4191-bbe0-22f20cc29e36)

**Comment by mitchej123** [comment]
Likely a bug or problem with the hodgepodge mixins I ported over, try disabling speedupAnimations in the config and see if that fixes it.

**Comment by Valor760** [comment]
@mitchej123 - Yes, disabling speedupAnimations in config fixed issue.

**Comment by ALongStringOfNumbers** [comment]
I have been seeing a similar issue, with animations not working, and disabling this config option worked for me to get the animations working again.

**Comment by mitchej123** [comment]
Fixed in recent alphas
