### ISSUE TITLE
Angelica + Psychedelicraft, constant GL ERROR while in a world

### ISSUE THREAD

**Issue by WolfBV** [GTNewHorizons/Angelica#441]
### Your GTNH Discord Username

wolfbv

### Mod Version

1.0.0-alpha38

### Java Version

Java 8

### Graphics Card Vendor

AMD/ATI

### Bug Report

While in a world, I noticed the console creating this message multiple time a second. [Client thread/ERROR] [psychedelicraft]: ########## GL ERROR ########## @ Post render pass 'Default' 1282: Invalid operation

https://mclo.gs/GYu7G15

### Mod List or GTNH Pack Version

Angelica, GTNH Lib, IvToolkit, Psychedelicraft, Unimixins.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by WolfBV** [comment]
Can be dealt with by changing Psychedelicraft's Visuals > shaderEnabled option from True to False in Psychedelicraft's config file, reducing the errors from multiple per second to once when joining a world.

**Comment by Goosegit11** [comment]
how is that completed

**Comment by Goosegit11** [comment]
and it's a bad workaround, shaders are crucial part of the Psychedelicraft
