### ISSUE TITLE
Magic map in a chest breaks HUD when looked at with holo glasses

### ISSUE THREAD

**Issue by Demiu** [GTNewHorizons/Angelica#455]
### Your GTNH Discord Username

Demiu

### Mod Version

1.0.0-alpha40

### Java Version

Java 21

### Graphics Card Vendor

AMD/ATI

### Bug Report

When holo glasses are equipped and I look at a chest containing a twilight forest magic map the hud completely stops rendering, no info in the top left, no journeymap, no bar at the bottom. Opening inventory or the chest itself also shows nothing. The holo glasses'  floating inventory is visible though, but without the map item. Seems to may be influenced by the angle at which the chest is looked at, looking differently at the block, only some positions have this problem. Taking the glasses off or removing the map from the chest prevents this issue.

![image](https://github.com/GTNewHorizons/Angelica/assets/7906172/5bdc17bd-211b-49b9-aa25-9f6c707d5421)

### Mod List or GTNH Pack Version

2.6.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Caedis** [comment]
Fix in latest version of Holoinventory
