### ISSUE TITLE
PojavLauncher

### ISSUE THREAD

**Issue by EvenWen1215** [GTNewHorizons/Angelica#459]
### Mod Version

42

### Java Version

Java 8

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

when i use this mod on pojavlauncher holy is crash

### Mod List or GTNH Pack Version

2.6.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by chochem** [comment]
please post logs. also, what device is that on?

**Comment by mitchej123** [comment]
I can't say I'm surprised 
![image](https://github.com/GTNewHorizons/Angelica/assets/1894689/242252c5-61b6-4fb4-9ff8-7e1c01b55ad9)

**Comment by chochem** [comment]
yea I know what pojav is, hence me asking for the device :P

**Comment by EvenWen1215** [comment]
> 是的，我知道 pojav 是什么，因此我要这个设备：P

Snapdragon 8 Gen 2 holy gl4es

**Comment by mitchej123** [comment]
Needs a lot, but no promises

**Comment by EvenWen1215** [comment]
> 需要日志，但没有承诺

[crash-2024-05-04_01.16.43-client.txt](https://github.com/GTNewHorizons/Angelica/files/15203093/crash-2024-05-04_01.16.43-client.txt)
[Uploading latest.log…]()

**Comment by EvenWen1215** [comment]
[latest.log](https://github.com/GTNewHorizons/Angelica/files/15203116/latest.log)
[crash-2024-05-04_01.16.43-client.txt](https://github.com/GTNewHorizons/Angelica/files/15203117/crash-2024-05-04_01.16.43-client.txt)

**Comment by EvenWen1215** [comment]
> 需要日志，但没有承诺

do you have some solutions

**Comment by EvenWen1215** [comment]
You can refer to the link to launch a version specifically for pojavlauncher 【[个人魔改]最新版本的钠可以在手机上运行了!-哔哩哔哩】 https://b23.tv/WOjCvbP
