### ISSUE TITLE
Feature request: Optifine style zoom

### ISSUE THREAD

**Issue by lynxx131** [GTNewHorizons/Angelica#467]
### Your GTNH Discord Username

lynxx131#3686

### Mod Version

1.0.0-alpha44

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

With dynamic lights now added I've finally ditched Optifine for Angelica and so far it's been great and I'm only missing a couple of things that I used in Optifine one is Shaders which I know are WIP but the other which I haven't seen mentioned is the zooming feature offered by Optifine.

It's a handy way to quickly survey the distance however being visually challenged I do actually also find it handy to quickly zoom the screen to look at certain small block elements such as the conduit arrows on EnderIO conduits which can sometimes be a bit hard to see under certain circumstances especially with shaders.

Understand this won't be a priority but would be interested to see if it can be included.

### Mod List or GTNH Pack Version

GTNH-2.6.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Caedis** [comment]
Give https://github.com/Nolij/Zume a try

**Comment by Alexdoru** [comment]
Done,download latest beta
