### ISSUE TITLE
AE2 Dense Cable Crash: Cannot create a wrapper icon with a null icon

### ISSUE THREAD

**Issue by MarshTheBacca** [GTNewHorizons/Angelica#468]
### Your GTNH Discord Username

marshthebacca

### Mod Version

1.0.0-alpha40

### Java Version

Java 21

### Graphics Card Vendor

AMD/ATI

### Bug Report

I'm not sure what triggered it, but I exited my AE2 crafting terminal, the screen went pale-blue, and BetterCrashes caught the following report:
https://mclo.gs/8NydG8o

The crash does not reoccur upon rejoining the server, and I did not have to restart my game.

### Mod List or GTNH Pack Version

GTNH 2.6.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Caedis** [comment]
Update to latest AE2
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/download/rv3-beta-400-GTNH/appliedenergistics2-rv3-beta-400-GTNH.jar

**Comment by Ubus99** [comment]
Is there a workaround that does not require updating?
For server compatibility.

**Comment by Caedis** [comment]
No
