### ISSUE TITLE
[GTNH 2.4.0] Minecraft don't even start

### ISSUE THREAD

**Issue by valentimarco** [GTNewHorizons/Angelica#47]
### Your GTNH Discord Username

valentimarco

### Mod Version

1.0.0-alpha1

### Java Version

Java 17

### Bug Report

Minecraft don't even start.
Crash-file:
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-12-25 17:59:47 CET
Description: Initializing game

java.lang.NoClassDefFoundError: org/lwjglx/opengl/KHRDebugCallback
    at net.coderbot.iris.gl.GLDebug.setupDebugMessageCallback(GLDebug.java:89)
    at net.coderbot.iris.gl.GLDebug.setupDebugMessageCallback(GLDebug.java:36)
    at net.coderbot.iris.Iris.setDebug(Iris.java:395)
    at net.minecraft.client.renderer.OpenGlHelper.handler$zdf000$angelica$sodium$initIrisDebug(OpenGlHelper.java:1296)
    at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:189)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:455)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6595)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: org.lwjglx.opengl.KHRDebugCallback
    at java.net.URLClassLoader.findClass(URLClassLoader.java:445)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:130)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:592)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:525)
    ... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6595)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 17.0.9, Eclipse Adoptium
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
    Memory: 227341704 bytes (216 MB) / 536870912 bytes (512 MB) up to 10737418240 bytes (10240 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx10240m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: 
    Mixins in Stacktrace: 
        net.minecraft.client.renderer.OpenGlHelper:
            mixins.angelica.early.json:angelica.startup.MixinInitGLStateManager from mod angelica
            mixins.angelica.early.json:sodium.startup.MixinInitDebug from mod angelica
        net.minecraft.client.Minecraft:
            mixins.angelica.early.json:sodium.MixinMinecraft from mod angelica
            mixins.hodgepodge.early.json:minecraft.MixinMinecraft_UnfocusedFullscreen from mod hodgepodge
            mixins.hodgepodge.early.json:minecraft.MixinMinecraft_ToggleDebugMessage from mod hodgepodge
            mixins.hodgepodge.early.json:minecraft.MixinMinecraft_UpdateKeys from mod hodgepodge
            mixins.hodgepodge.early.json:minecraft.profiler.MinecraftMixin from mod hodgepodge
            mixins.hodgepodge.early.json:minecraft.MixinMinecraft_ResizableFullscreen from mod hodgepodge
            mixins.hodgepodge.early.json:minecraft.MixinMinecraft_ClearRenderersWorldLeak from mod hodgepodge
            mixins.bettercrashes.json:minecraft.MinecraftMixin from mod bettercrashes
    Suspected Mods: Unknown
    Launched Version: 1.7.10
    LWJGL: 3.3.2+13
    OpenGL: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.01, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.client.resources.LanguageManager.func_135041_c()" because the return value of "net.minecraft.client.Minecraft.access$100(net.minecraft.client.Minecraft)" is null
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```
All log: https://mclo.gs/otGN9Kc

### Mod List

Retrive from prismlaucher log  (idk why the latest.log is not generated)
[🖿] 1.7 (folder)
  [✔] AdvancedSolarPanel-1.7.10-3.5.1a
  [✔] adventurebackpack-1.0.14-GTNH
  [✔] ae2fc-1.1.42-gtnh
  [✔] ae2stuff-0.5.7-GTNH
  [✔] AFSU-1.7.10-1.2.6-GTNH
  [✔] alchgrate-1.0.3-GTNH
  [✔] AmunRa-GC-0.4.36
  [✔] angelica-1.0.0-alpha1
  [✔] AngerMod-1.7.10-0.6.3
  [✔] AppleCore-3.2.11
  [✔] appliedenergistics2-rv3-beta-250-GTNH
  [✔] ArchitectureCraft-1.8.6
  [✔] Aroma1997Core-1.7.10-1.0.2.16
  [✔] AromaBackup-1.7.10-0.1.0.0
  [✔] AsieLib-0.5.4
  [✔] Automagy-1.7.10-0.28.2
  [✔] Avaritia-1.46
  [✔] Avaritiaddons-1.5.5-GTNH
  [✔] backpack-2.2.12-GTNH
  [✔] bartworks-0.7.40
  [✔] battlegear2-1.2.0
  [✔] Baubles-1.0.1.16
  [✔] bdlib-1.7.10-1.9.8-GTNH
  [✔] beebetteratbees-0.3.1-GTNH
  [✔] BetterAchievements-1.7.10-0.1.3
  [✔] BetterBuildersWands-1.7.10-0.9.6-GTNH
  [✔] bettercrashes-1.2.2-GTNH
  [✔] betterloadingscreen-1.4.4-GTNH
  [✔] betterp2p-1.1.20
  [✔] BetterQuesting-3.3.27-GTNH
  [✔] BiblioCraft[v1.11.7][MC1.7.10]
  [✔] BiblioWoods[BiomesOPlenty][v1.9]
  [✔] BiblioWoods[Forestry][v1.7]
  [✔] BiblioWoods[Natura][v1.5]
  [✔] binnie-mods-2.1.10
  [✔] BiomesOPlenty-1.7.10-2.1.0.2308-universal
  [✔] BlockLimiter-1.7.10-0.55
  [✔] blockrenderer6343-1.0.3
  [✔] BloodArsenal-1.2.11
  [✔] BloodMagic-1.4.3
  [✔] Botania-1.9.24-GTNH
  [✔] BotanicHorizons-1.0.15-GTNH
  [✔] BrandonsCore-1.7.10-1.0.0.13-GTNH
  [✔] bugtorch-1.2.10-GTNH
  [✔] buildcraft-7.1.36
  [✔] buildcraft-compat-7.1.14
  [✔] BuildCraftOilTweak-1.7.10-1.0.4
  [🖿] carpentersblocks (folder)
  [✔] CarpentersBlocks-3.4.0-GTNH
  [✔] catwalks-1.7.10-2.1.4-GTNH
  [✔] chisel-2.11.4-GTNH
  [✔] chiseltones-1.7.10-1.0.4-GTNH
  [✔] CodeChickenCore-1.2.0
  [✔] CoFHCore-[1.7.10]3.1.4-329
  [✔] CompactKineticGenerators-1.7.10-1.0
  [✔] Computronics-1.7.1-GTNH
  [✔] controlling-1.0.0.5
  [✔] CookingForBlockheads-1.2.16-GTNH
  [✔] craftingtweaks-mc1.7.10-1.0.88
  [✔] CraftPresence-2.2.2%2B1.7.10
  [✔] CraftTweaker-3.2.13
  [✔] creativecore-1.3.31-GTNH
  [✔] CropLoadCore-1.7.10-0.1.10
  [✔] CropsPP-1.4.1
  [✔] custommainmenu-1.7.10-1.9.4
  [✔] defaultkeys-1.1.3
  [✔] defaultserverlist-1.7.10-1.4.0
  [✔] defaultworldgenerator-1.7.10-0.2
  [✔] Draconic-Evolution-1.1.19-GTNH
  [✔] DummyCore-1.17.0
  [✔] duradisplay-1.0.10
  [✔] EMT-1.3.3
  [✔] endercore-0.2.17
  [✔] EnderIO-2.4.24
  [✔] EnderStorage-1.7.10-1.4.12
  [✔] EnderZoo-1.7.10-1.0.23
  [✔] EnhancedLootBags-1.1.0
  [✔] eternalsingularity-1.1.2
  [✔] extrautilities-1.2.13a
  [✘] fastcraft-1.25.jar (disabled)
  [✔] findit-1.1.0
  [✔] FloodLights-1.7.10-1.2.9
  [✔] Forbidden.Magic-0.6.7-GTNH
  [✔] Forestry-4.6.14
  [✔] forgelin-1.9.7-GTNH
  [✔] ForgeMultipart-1.3.4
  [✔] ForgeRelocation-1.7.10-0.0.3
  [✔] ForgeRelocationFMP-1.7.10-0.0.4
  [✔] FTBLib-1.0.19-GTNH
  [✔] FTBUtilities-1.1.1-GTNH
  [✔] gadomancy-1.1.3
  [✔] galacticgreg-1.0.10
  [✔] Galacticraft-3.0.73-GTNH
  [✔] GalaxySpace-1.2.7-GTNH
  [✔] gendustry-1.7.10-1.6.5.5-GTNH
  [✔] ggfab-0.2.5
  [✔] GoodGenerator-0.6.41
  [✔] GraviSuite-1.7.10-2.0.3
  [✔] gravisuiteneo-1.0.15
  [✔] gregtech-5.09.43.192
  [✔] GT.Scanner.Mod-1.7.2
  [✔] gtneioreplugin-1.1.3
  [✔] GTNewHorizonsCoreMod-2.1.110
  [✔] gtnhintergalactic-1.1.28
  [✔] gtnhlanth-0.10.8
  [✔] gtnhlib-0.0.13
  [✔] GTNH-TC-Wands-1.3.1
  [✔] GT-PlusPlus-1.9.85
  [✔] GTTweaker-2.0.1
  [✔] HardcoreDarkness-MC1.7.10-1.7
  [✔] HardcoreEnderExpansion-1.7.10-1.9.7-GTNH
  [✔] harvestcraft-1.1.1-GTNH
  [✔] Healer-1.2.1
  [✔] HelpFixer-1.7.10-1.1.0
  [✔] hodgepodge-2.4.3
  [✔] holoinventory-2.2.4-GTNH
  [✔] HungerOverhaul-1.7.10-1.0.4-GTNH
  [✔] hydroenergy-1.1.0
  [🖿] ic2 (folder)
  [✔] IC2 Crop Plugin Version 1.7.10-1.3.1
  [✔] IC2NuclearControl-2.4.19
  [✔] ifu-1.9.6
  [✔] IguanaTweaksTConstruct-2.3.0
  [✔] industrialcraft-2-2.2.828a-experimental
  [✔] InfernalMobs-1.7.9-GTNH
  [✔] InGameInfoXML-2.8.4
  [✔] INpureCore-1.1.5-GTNH
  [✔] inventorytweaks-1.5.16
  [✔] IronChest-6.0.72
  [✔] IronChestMinecarts-1.7.10-1.0.8
  [✔] irontanks-1.7.10-1.2.6
  [✔] itlt-1.7.10-1.0.4
  [✔] JABBA-1.2.22
  [✔] journeymap-1.7.10-5.1.4p6-fairplay
  [✔] kekztech-0.8.9
  [✔] kubatech-0.12.8
  [✔] littletiles-1.2.9-GTNH
  [✔] logisticspipes-1.0.6-GTNH
  [✔] lootgames-1.7.10-2.0.8
  [✔] LumySkinPatch-1.0.12
  [✔] LunatriusCore-1.7.10-1.1.7-GTNH
  [✔] lwjgl3ify-1.4.2
  [✔] magicbees-2.6.6-GTNH
  [✔] malisiscore-0.14.9
  [✔] malisisdoors-1.13.7-GTNH
  [✔] Mantle-0.3.7
  [✔] mobsinfo-0.1.6-GTNH
  [✔] ModTweaker2-0.9.10
  [✔] modularui-1.1.16
  [✔] MouseTweaks-2.4.9-GTNH
  [✔] mxrandom-0.2.0
  [✔] Natura-2.5.7
  [✔] naturescompass-1.7.10-1.3.6-GTNH
  [✔] NEIAddons-1.7.10-1.12.22
  [✔] NEICustomDiagram-1.5.11
  [✔] NEIIntegration-1.3.3
  [✔] netherportalfix-1.7.10-1.1.2
  [✔] NettyPatch-1.7.10-0.3.1
  [✔] NodalMechanics-1.7.10-1.1.-6-GTNH
  [✔] NotEnoughEnergistics-1.4.2
  [✔] notenoughIDs-1.7.10-1.4.6
  [✔] NotEnoughItems-2.3.83-GTNH
  [✔] nutrition-0.0.4
  [✔] oauth-1.7.10-1.06.1-GTNH
  [✔] OpenBlocks-1.7.0-GTNH
  [✔] OpenComputers-1.9.14-GTNH
  [✔] OpenGlasses-1.3.1-GTNH
  [✔] OpenModsLibs-1.7.10-0.10.6
  [✔] OpenModularTurrets-1.7.10-2.2.11-247
  [✔] openprinter-1.7.10-0.1.3-GTNH
  [🖿] OpenSecurity (folder)
  [✔] opensecurity-1.7.10-1.0.120-GTNH
  [✔] Opis-1.7.10-1.3.8-mapless
  [✘] OptiFine_1.7.10_HD_U_E7.jar (disabled)
  [✔] OreExcavation-1.1.134
  [✔] overloadedarmorbar-1.7.10-1.0.1
  [✔] p455w0rdslib-1.7.10-1.0.4
  [✔] Pam's Harvest the Nether 1.7.10a
  [✔] personalspace-1.0.26
  [✔] PlayerAPI-1.7.10-1.4.2
  [✔] ProjectBlue-1.1.12-GTNH
  [✔] ProjRed-4.7.12-GTNH
  [✔] Railcraft-9.14.9
  [✔] RandomThings-2.4.5
  [✔] RemoteIO-1.7.10-2.4.8
  [✔] roguelike-1.7.10-1.5.3-GTNH
  [✔] RWG-1.7.10-alpha-1.3.3.2
  [✔] Schematica-1.9.3-GTNH
  [✔] SGCraft-1.7.10-1.3.13-GTNH
  [✔] sharewhereiam-1.7.10-0.2.0
  [✔] sleepingbag-1.7.10-0.1.4
  [✔] SpecialMobs-3.4.3
  [✔] SpiceOfLife-2.1.0-carrot
  [✔] SSP-1.1.2-GT-NH-Mod
  [✔] StevesAddons-1.7.10-0.10.27
  [✔] StevesCarts-1.7.10-2.0.2
  [✔] StevesFactoryManager-1.1.7-GTNH
  [✔] StorageDrawers-1.12.0-GTNH
  [✔] StorageDrawersBop-1.7.10-1.11.17-GTNH
  [✔] StorageDrawersForestry-1.7.10-1.11.17-GTNH
  [✔] StorageDrawersMisc-1.7.10-1.11.18-GTNH
  [✔] StorageDrawersNatura-1.7.10-1.11.17-GTNH
  [✔] structurecompat-0.4.0
  [✔] structurelib-1.2.8
  [✔] SuperTic-1.7.10-1.2.5
  [✔] Tainted-Magic-7.6.3-GTNH
  [✔] tcinventoryscan-1.7.10-1.0.12-GTNH
  [✔] tcneiadditions-1.2.2
  [✔] tcnodetracker-1.7.10-1.1.7
  [✔] TConstruct-1.9.39-GTNH
  [✔] TecTech-5.2.40
  [✔] TGregworks-1.7.10-GTNH-1.0.24
  [✔] Thaumcraft-1.7.10-4.2.3.5a
  [✔] Thaumcraft4Tweaks-1.5.15
  [✔] ThaumcraftMobAspects-1.7.10-1.0.0-GTNH
  [✔] thaumcraftneiplugin-1.7.10-1.7a
  [✔] ThaumcraftResearchTweaks-1.7.10-1.0.4
  [✔] Thaumic Machina-1.7.10-0.2.1
  [✔] Thaumic-Based-1.5.4
  [✔] thaumicenergistics-1.4.13-GTNH
  [✔] Thaumic-Exploration-1.7.10-1.1.94-GTNH
  [✔] ThaumicHorizons-1.3.5
  [✔] thaumicinsurgence-0.2.7
  [✔] ThaumicTinkerer-2.7.1
  [✔] TiCTooltips-1.2.11
  [✔] Tinkers-Defense-1.2.1d
  [✔] TMechworks-1.7.10-0.2.16.4
  [✔] TooMuchLoot-1.7.10-4.1.0-GTNH
  [✔] torohealth-1.7.10-1.0.1
  [✔] Translocator-1.1.2.21
  [✔] TravellersGear-1.7.10-1.16.6
  [✔] travellersgearneo-1.0
  [✔] TwilightForest-2.4.5
  [✔] txloader-1.5.5
  [✔] -unimixins-all-1.7.10-0.1.11
  [✔] Universal-Singularities-8.6.7
  [✔] visualprospecting-1.1.13
  [✔] Waila-1.6.0
  [✔] WailaHarvestability-1.7.10-1.1.10-GTNH
  [✔] WAILAPlugins-0.2.8
  [✔] WanionLib-1.8.4
  [✔] WarpTheory-1.2.16-GTNH
  [✔] Wawla-1.7.10-1.1.3-GTNH
  [✔] WirelessCraftingTerminal-1.9.4
  [✔] witchery-1.7.10-0.24.1
  [✔] WitcheryExtras-1.1.14
  [✔] WitchingGadgets-1.3.4-GTNH
  [✔] WR-CBE-1.7.10-1.4.8
  [✔] YAMCore-0.5.86
  [✔] Ztones-1.7.10-2.2.2

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by mitchej123** [comment]
Update your LWJGL3ify version, it needs 1.5.5+

I've updated the readme to reflect as such.

**Comment by bombcar** [comment]
Also you can just assume you need to be on 2.5.1 with this, otherwise there’s too much chasing potential totally old issues

**Comment by valentimarco** [comment]
> Also you can just assume you need to be on 2.5.1 with this, otherwise there’s too much chasing potential totally old issues

You are right and i apologize, i am lazy and wanna try it before the update (i need to upgrade even my server....)
