### ISSUE TITLE
OpenGL error

### ISSUE THREAD

**Issue by re7gog** [GTNewHorizons/Angelica#470]
### Mod Version

alpha45

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

[crash-2024-05-09_16.37.44-client.txt](https://github.com/GTNewHorizons/Angelica/files/15263012/crash-2024-05-09_16.37.44-client.txt)
Found out that it's xaeromap texture compression option bug
Also dynamic lighting is not working

### Mod List or GTNH Pack Version

In crashlog

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by re7gog** [comment]
After some testing i have assumption that it's xaeromap texture compression option

**Comment by mitchej123** [comment]
Dynamic lights module needs to be enabled, in addition to the settings.
