### ISSUE TITLE
Crash when inventory is open

### ISSUE THREAD

**Issue by Ciubix8513** [GTNewHorizons/Angelica#473]
### Your GTNH Discord Username

@ciubix8513

### Mod Version

1.0.0-alpha40

### Java Version

Java 21

### Graphics Card Vendor

AMD/ATI

### Bug Report

[hs_err_pid239684.log](https://github.com/GTNewHorizons/Angelica/files/15279383/hs_err_pid239684.log)

### Mod List or GTNH Pack Version

gtnh-2.6.0 + SkinPort

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Seems more driver related.... crashing in `nglGenBuffers` is odd

**Comment by Ciubix8513** [comment]
I did not have this issue on 2.5.1, and i don't believe there was a new driver version

**Comment by mitchej123** [comment]
I'm still not seeing anything Angelica specific or related in there

**Comment by Caedis** [comment]
Might be SkinPort + EMT or an interaction with of those 2 + Angelica

**Comment by mitchej123** [comment]
2muchFPS

**Comment by Ciubix8513** [comment]
I finally got arround to testing the cause of it. It is not Skinport, i removed it and the crash still persists and i also upgraded angelica to the latest version just in case and the crash is still there.

Also it happens when rendering the player, be that inventory, in F5 or in a wireless crafting terminal

[hs_err_pid80773.log](https://github.com/GTNewHorizons/Angelica/files/15358536/hs_err_pid80773.log)

**Comment by Caedis** [comment]
Do you happen to have a EMT wing/jetpack?

**Comment by Ciubix8513** [comment]
Yes, I am using nano wings

**Comment by mitchej123** [comment]
The NanoWing renderer seems to be allocating a new Renderer each tick... which on vanilla seems to create a new DisplayList each tick..... but with Angelica it creates a new VBO each tick... and apparently the driver eventually gets sick of that and crashes.

I'm not sure how the display list spam works, and not the VBO spam.... I also don't see any proper cleanup of it.... It's a bug/leak in EMT that needs to be resolved.

**Comment by Ciubix8513** [comment]
I see... 

I had a look at the EMT code, and tried to fix that, but i don't have enough knowledge of how it works

**Comment by mitchej123** [comment]
Fixed with https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/77
