### ISSUE TITLE
add opengl2.1 version

### ISSUE THREAD

**Issue by EvenWen1215** [GTNewHorizons/Angelica#474]
### Your GTNH Discord Username

EvenWen1215

### Mod Version

45

### Java Version

Java 8

### Graphics Card Vendor

Mesa/Software

### Bug Report

i use opengl2.1 cant run this mod

### Mod List or GTNH Pack Version

gtnhlib unmixins angelica

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
What setup are you using that limits you to OGL 2.1?  I've personally tested it on OSX which is limited to 2.1 or 2.3 and it works.  


I have no plans to move backwards.  Additionally we're moving ahead and plans to move to 3.3+ core....

**Comment by EvenWen1215** [comment]
how can i use this on opengl2.1 i cant run

**Comment by wagyourtail** [comment]
logs? what does `glxinfo | grep OpenGL` show.

**Comment by EvenWen1215** [comment]
[latest.log](https://github.com/GTNewHorizons/Angelica/files/15281186/latest.log)
[crash-2024-05-10_13.57.34-client.txt](https://github.com/GTNewHorizons/Angelica/files/15281188/crash-2024-05-10_13.57.34-client.txt)

**Comment by Caedis** [comment]
Android is not supported

**Comment by EvenWen1215** [comment]
i hope can add version support android

**Comment by EvenWen1215** [comment]
it can run on boat but Ground is not rendered

**Comment by Caedis** [comment]
Yeah.....no

**Comment by mitchej123** [comment]
I'm fine for PRs for Android support but I have no interest in doing it myself
