### ISSUE TITLE
ME Storage Monitor Rendering Issues

### ISSUE THREAD

**Issue by Tree-er233** [GTNewHorizons/Angelica#48]
### Your GTNH Discord Username

tree_er

### Mod Version

1.0.0-alpha

### Java Version

Java 21

### Bug Report

![image](https://github.com/GTNewHorizons/Angelica/assets/110247896/48a99522-4a2c-4f24-b614-6d8e516e9079)
https://mclo.gs/QBWuiOl
I have disabled FontRenderer in Angelica's profile.

### Mod List

![image](https://github.com/GTNewHorizons/Angelica/assets/110247896/dbf3c6b2-e88c-4e71-a171-97560a3c96bb)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by Tree-er233** [comment]
The Alpha4 version will also have this issue.

**Comment by Tree-er233** [comment]
![image](https://github.com/GTNewHorizons/Angelica/assets/110247896/693bbe94-27e9-4e80-9709-f0251d1d2c35)
Alpha11 version has improvements. But there are still problems with rendering some fluids.

**Comment by Tree-er233** [comment]
https://github.com/GTNewHorizons/Angelica/assets/110247896/c9808dfc-9037-4518-9122-66a79eb3151e

Alpha14 version has improvements, but there are still some problems.

**Comment by Tree-er233** [comment]
https://github.com/GTNewHorizons/Angelica/assets/110247896/ce9bd5b8-75f4-459d-845f-87cd80930f04

Some new discoveries in alpha26.

**Comment by mitchej123** [comment]
Give it a try with the latest alpha (28); I've fixed some matrix mode code

**Comment by Tree-er233** [comment]
> Give it a try with the latest alpha (28); I've fixed some matrix mode code

alpha28 still has this issue

**Comment by Tree-er233** [comment]
![image](https://github.com/GTNewHorizons/Angelica/assets/110247896/1b7771ec-5d3b-420d-823d-e781d908e74a)
still in stable 2.6.0

**Comment by Cleptomania** [comment]
Is this still happening? I know we fixed a lot of stuff with AE2 rendering and I haven't seen this or heard of it for a while. I'm going to close this because I think it's fixed, if I'm incorrect please re-open
