### ISSUE TITLE
Xray with the Blueberry Bush from the Natura Mod

### ISSUE THREAD

**Issue by Aaron13139** [GTNewHorizons/Angelica#486]
### Your GTNH Discord Username

ok.7570

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When placing the bush down after it was broken, I am able to see through the blocks around the bush. I have tried to turn off the setting "Chunk Multi-Draw" as asked by another person on the GTNH discord but it doesn't fix it.

### The Reality

When placing the blocks down, was able to see through the blocks around the bush.
![2024-05-08_01 50 07](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/54523708/0c42f4f6-00e8-4bbf-8533-853ef6abe6db)

### Your Proposal

I'm not sure of a solution but the block could be removed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
Reopening to so it can be properly fixed

**Comment by jss2a98aj** [comment]
This should have been fixed with #464
