### ISSUE TITLE
Crash when breaking Thaumic Energistics Essentia Provider

### ISSUE THREAD

**Issue by RecursivePineapple** [GTNewHorizons/Angelica#493]
### Your GTNH Discord Username

recursive_pineapple

### Mod Version

1.0.0-alpha40

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

When I broke an Essentia Provider, my game crashed. This looks like a multithreading issue. The provider was offline, but I can't reproduce this.

[crash-2024-05-18_20.00.12-client.txt](https://github.com/GTNewHorizons/Angelica/files/15367117/crash-2024-05-18_20.00.12-client.txt)

### Mod List or GTNH Pack Version

2.6.0 with a nightly AE2 release

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Cleptomania** [comment]
This looks like, at least the crash would be fixed with Angelica beta8
