### ISSUE TITLE
Client Crash 

### ISSUE THREAD

**Issue by Avalanche7CZ** [GTNewHorizons/Angelica#494]
### Your GTNH Discord Username

Avalanche7

### Mod Version

the one in the modpack 2.6.0 GTNH

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

https://pastebin.com/e9G5f5eq

- Client crash (probably by dense cable)
- Around AE2 / ME

### Mod List or GTNH Pack Version

2.6.0 GTNH Modpack

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Cleptomania** [comment]
We had a series of fixes in AE2 for problems with the cable rendering shortly after 2.6.0 release that were released in 2.6.1. This should be fixed now, if not feel free to re-open
