### ISSUE TITLE
Request: Dynamic Light Support for Battlegear / Backhand

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/Angelica#496]
it would be awesome if torches worked in the offhand in battlegear slots
![image](https://github.com/GTNewHorizons/Angelica/assets/11356565/bea7919e-2616-4b2d-a5a0-edcd6a8f37b0)

the one i use is a battlegear fork that backports the offhand from newer versions called backhand:
![image](https://github.com/GTNewHorizons/Angelica/assets/11356565/7ae5ad61-54eb-4cf2-9ca7-129ab31acd03)

just for proof it doesn't work in offhand slots:
![image](https://github.com/GTNewHorizons/Angelica/assets/11356565/c2085f04-73c0-461b-973c-2b8d03073c29)

### Mod Version
angelica a50

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by xronin01** [comment]
This mod does that
https://modrinth.com/mod/offhandlights

**Comment by Caedis** [comment]
Forgot to close this
