### ISSUE TITLE
VoxelMap not working with Angelica

### ISSUE THREAD

**Issue by huihiuhuai** [GTNewHorizons/Angelica#499]
### Your GTNH Discord Username

hsuihaiui

### Mod Version

alpha50

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

VoxelMap not working with Angelica

### Mod List or GTNH Pack Version

Unimixins, angelica, GTNH Lib, voxelmap, lite loader, hodgepodge.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Cleptomania** [comment]
You've made two issues for the same problem? Closing to track in one issue. See #424
