### ISSUE TITLE
OpenBlocks Tanks crash when viewed in NEI or creative inventory

### ISSUE THREAD

**Issue by LordPINE** [GTNewHorizons/Angelica#50]
### Your GTNH Discord Username

lordpine

### Mod Version

1.0.0-alpha2

### Java Version

Java 8

### Bug Report

https://gist.github.com/LordPINE/d954cd103fe2d5d480492881f8261806

The game does not technically crash, but it freezes and is completely unusable. I've narrowed it down to only angelica and openblocks.

### Mod List

+unimixins-all-1.7.10-0.1.15
angelica-1.0.0-alpha2
CodeChickenLib-1.2.0
CodeChickenCore-1.2.0
NotEnoughItems-2.4.13-GTNH
OpenBlocks-1.7.10-1.6 (though I have also replicated the same issue with the GTNH fork)
OpenModsLib-1.7.10-0.10.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by LordPINE** [comment]
After updating angelica to 1.0.0-apha4, it actually crashes instead of getting into an infinite error loop:
https://gist.github.com/LordPINE/4c3157dc38505633520ab521863c9230
Note that gist truncates it because the error loop still keeps going for a while, spamming the log. The actual crash report is still accessible via gist, but here it is separately as well just in case:
https://gist.github.com/LordPINE/e841bfd6ede9f2492bba4b1b19e31412

**Comment by mitchej123** [comment]
Interesting, I'll look through it in more detail later.  I'll also look into making that warning only pop up once per mod or function... or a config option to shut it off.  I left it in because it's silently doing the wrong thing and it's useful for debugging.

Thanks for isolating the actual crash... Interesting, I made the matrixstack the size queried from the GPU... I wonder what the GPU is doing when it hits max stack size? `java.lang.IllegalStateException: max stack size of 32 reached`

**Comment by AnrDaemon** [comment]
One more to the list of logs. My test world contains a column of OpenBlocks tanks filled with XP juice.
[crash-2023-12-27_12.54.44-client.txt](https://github.com/GTNewHorizons/Angelica/files/13777562/crash-2023-12-27_12.54.44-client.txt)

**Comment by Dream-Master** [comment]
Open blocks tanks are disabled in GTNH

**Comment by AnrDaemon** [comment]
That explains, why it wasn't discovered earlier.

**Comment by mitchej123** [comment]
Try this again with alpha9; the matrix stack over flow shouldn't happen now

**Comment by LordPINE** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/13788609/fml-client-latest.log)
[crash-2023-12-28_19.17.10-client.txt](https://github.com/GTNewHorizons/Angelica/files/13788611/crash-2023-12-28_19.17.10-client.txt)
It still crashes, with I think the same error? Definitely using alpha9, I double checked because I was confused at it still crashing.

**Comment by mitchej123** [comment]
Meh, openblocks causing trouble again

**Comment by PlayfulPiano** [comment]
Can confirm I'm also experiencing this issue when I tried viewing openblocks' trophies in NEI. Loops crashes too.
[crash-2023-12-28_15.28.28-client.txt](https://github.com/GTNewHorizons/Angelica/files/13789312/crash-2023-12-28_15.28.28-client.txt)

Using alpha5 in this case of angelica (alpha8 was having an issue on startup freezing, haven't tried alpha9 yet).

**Comment by AnrDaemon** [comment]
Angelica alpha10

[crash-2023-12-29_03.04.28-client.txt](https://github.com/GTNewHorizons/Angelica/files/13790201/crash-2023-12-29_03.04.28-client.txt)

P.S.
Found last two tanks hidden under the conduits wiring angel cage to experimental EnderIO setup.

Vat and Farm are now rendered correctly. And 110-140 FPS is impressive. But I'll wait for SmoothFont support to judge (had to remove it to get correct text rendering).
