### ISSUE TITLE
Twilight Forest Chunk build failed

### ISSUE THREAD

**Issue by zhehedream** [GTNewHorizons/Angelica#504]
### Mod Version

1.0.0-alpha50

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

Crash happened inside twilight forest dimension. That happened quite frequently
[Crash Log](https://pub.microbin.eu/raw/snake-gecko-eel)

Java: graalvm-jdk-21

### Mod List or GTNH Pack Version

TwilightForest-2.5.25.jar
angelica-1.0.0-alpha50.jar

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Cleptomania** [comment]
That is quite an old version of Twilight Forest. The problem has likely been fixed in Twilight Forest.
