### ISSUE TITLE
crash when loading world

### ISSUE THREAD

**Issue by xronin01** [GTNewHorizons/Angelica#51]
### Mod Version

1.0.0-alpha2

### Java Version

Java 8

### Bug Report

[latest.log](https://github.com/GTNewHorizons/Angelica/files/13767275/latest.log)

### Mod List

+unimixins-all-1.7.10-0.1.15
angelica-1.0.0-alpha2
gtnhlib-0.0.13

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by chochem** [comment]
seems to be a problem with your account and not angelica

**Comment by boubou19** [comment]
pirated accounts are not supported in any form. Try reproducing it with a legit account.

**Comment by boubou19** [comment]
it does not block it, but we don't want to bother with cracked launchers, as they can sometimes cause incompatibilities. So we only want to deal with instances running legally, to at least ensure some sanity checks.
