### ISSUE TITLE
Angelica leaks GL Lighting States

### ISSUE THREAD

**Issue by Quarri6343** [GTNewHorizons/Angelica#511]
### Your GTNH Discord Username

Quarri6343

### Mod Version

1.0.0-alpha51

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

See this for codes. Vanilla chest flickers when I set the directional light in Jabba item renderer
https://github.com/GTNewHorizons/Jabba/pull/33
Probably unrelated to Logisticspipes chest flickering since I can't find Lighting code in its block renderer

### Mod List or GTNH Pack Version

GTNH v2.6.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Cleptomania** [comment]
This has been fixed, we now have better lighting functions in Angelica's GLSM and this lighting code was also changed in JABBA
