### ISSUE TITLE
Biomes O' Plenty Sodium coral crash

### ISSUE THREAD

**Issue by gamemaster112ful** [GTNewHorizons/Angelica#516]
### Mod Version

angelica-1.0.0-alpha51

### Java Version

Java 8

### Graphics Card Vendor

AMD/ATI

### Bug Report

https://mclo.gs/4umVpUB

When loading in the Biomes O' Plenty coral reef biome, or just rendering the coral blocks in general when loading in new chunks, the game crashes both on an AMD and NVidia card.

### Mod List or GTNH Pack Version

  [✔️] +unimixins-all-1.7.10-0.1.17.jar
  [📁] 1.7.10 (folder)
  [✔️] 1.7.10_AM2-1.4.0.009.jar
  [✔️] 1.7.10-ASJCore-1.3.0.1 (1).jar
  [✔️] adventurebackpack-1.7.10-0.8c.jar
  [✔️] aether-1.7.10-v1.1.2.3.jar
  [✔️] AIImprovements-1.7.10-0.0.1b19-dev.jar
  [✔️] Alfheim-54 (1).jar
  [✔️] AmbientSounds Alpha v0.1 mc1.7.10.zip
  [✔️] angelica-1.0.0-alpha51.jar
  [✔️] AnimationAPI-1.7.10-1.2.4.jar
  [✔️] AOBD-2.9.2.jar
  [✔️] AppleCore-mc1.7.10-3.1.1 (CLIENT SIDE).jar
  [✔️] appliedenergistics2-rv3-beta-6.jar
  [✔️] AquaTweaks-1.7.10-1.0.jar
  [✔️] arcane_engineering-0.2.7.jar
  [✔️] archaicfix-0.7.2.jar
  [✔️] ArchimedesShips-1.7.1.jar
  [✔️] Automagy-1.7.10-0.28.2.jar
  [✔️] Avaritia-1.13.jar
  [✔️] BaublesExpanded-2.1.4.jar
  [✔️] BetterStorage-1.7.10-0.13.1.127.jar
  [✔️] BiblioCraft[v1.11.7][MC1.7.10].jar
  [✔️] BiblioWoods[BiomesOPlenty][v1.9].jar
  [✔️] BiblioWoods[Forestry][v1.7].jar
  [✔️] BiblioWoods[Natura][v1.5].jar
  [✔️] Big-Reactors-Mod-1.7.10.jar
  [✔️] binnie-mods-2.3.4 (1).jar
  [✔️] BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
  [✔️] BiomeTweaker-1.7.10-2.0.182.jar
  [✔️] BloodMagic-1.7.10-1.3.3-17.jar
  [✔️] Born in a Barn 1.7.x.jar
  [✔️] Botania+r1.8-249.jar
  [✔️] BrandonsCore-1.0.0.12.jar
  [✔️] buildcraft-7.1.23.jar
  [✔️] buildcraft-compat-7.1.7.jar
  [✔️] campfirebackport-1.7.10-1.10.1.jar
  [✔️] Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
  [📁] carpentersblocks (folder)
  [✔️] ChunkPurge-1.7.10-2.1.jar
  [✔️] ClimateControl-0.8.2.jar
  [✔️] CodeChickenCore-1.2.1.jar
  [✔️] CoFHCore-[1.7.10]3.1.4-329.jar
  [✔️] CoFHLib-[1.7.10]1.2.1-185.jar
  [✔️] ComputerCraft1.75.jar
  [✔️] CosmeticArmorReworked-1.7.10-v6b.jar
  [✔️] CraftingPillars-1.7.x-1.6.1.jar
  [✔️] DisenchanterMod-[1.7.10]1.6.jar
  [✔️] DMod-1.7.10-1.0.3.5.jar
  [✔️] DragonMounts-r41-1.7.10.jar
  [✔️] DummyCore1.13.jar
  [✔️] DynamicSwordSkills-1.7.10-final.jar
  [✔️] EnderCore-1.7.10-0.2.0.36_beta.jar
  [✔️] EnderIO-1.7.10-2.3.0.429_beta.jar
  [✔️] Et_Futurum_Requiem-2.5.1 (1).jar
  [✔️] Ex-Nihilo-1.38-53.jar
  [✔️] ExtraCells-1.7.10-2.3.14b200.jar
  [✔️] ExtraTiC-1.7.10-1.4.6.jar
  [✔️] extrautilities-1.2.12.jar
  [✔️] FastLeafDecay-1.7.10-1.4.jar
  [✔️] FoamFix-1.7.10-universal-1.0.4 (2).jar
  [✔️] Forbidden Magic-1.7.10-0.575.jar
  [✔️] forestry_1.7.10-4.2.16.64.jar
  [✔️] FoxLib-1.7.10-0.7.0.jar
  [✔️] gadomancy-1.7.10-1.0.7.3.jar
  [✔️] Galacticraft-1.7-3.0.12.504.jar
  [✔️] GalaxySpace-1.7.10-1.2.15.jar
  [✔️] gilded-games-util-1.7.10-2.0.jar
  [✔️] GraveStone Mod 0.7.10.3.jar
  [✔️] gtnhlib-0.2.11.jar
  [✔️] Hardcore Wither-1.7.10-1.1.3-21-universal.jar
  [✔️] HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar
  [📁] ic2 (folder)
  [✔️] IC2NuclearControl-2.4.3a.jar
  [✔️] IGW-Mod.jar
  [✔️] ImmersiveEngineering-0.7.7.jar
  [✔️] immersiveintegration-0.6.8.jar
  [✔️] industrialcraft-2-2.2.822-experimental.jar
  [✔️] InventoryTweaks-1.58-147.jar
  [✔️] ironchest-1.7.10-6.0.62.742-universal.jar
  [✔️] journeymap-1.7.10-5.1.4-unlimited.jar
  [✔️] LagFix-2.0.1-mc1.7.10-forge.jar
  [✔️] LunatriusCore-1.7.10-1.1.2.21-universal.jar
  [✔️] magicbees-1.7.10-2.4.3.jar
  [✔️] MagicCookies-1.0.7.1.jar
  [✔️] Mantle-1.7.10-0.3.2b.jar
  [✔️] MCA-1.7.10-5.2.2-universal.jar
  [✔️] Mekanism-1.7.10-9.1.1.1031.jar
  [✔️] MekanismGenerators-1.7.10-9.1.1.1031.jar
  [✔️] Mimicry-1.7.10_1492_1.0.10c.jar
  [✔️] Minechem-1.7.10-5.0.5.406.jar
  [✔️] MineFactoryReloaded-[1.7.10]2.8.1-174.jar
  [✔️] MineTweaker3-1.7.10-3.0.10B.jar
  [📁] mod-config (folder)
  [✔️] ModernKeyBinding-Forge-1.7.10-2.1.0-mixinless.jar
  [✔️] MutantCreatures-1.7.10-1.4.9.jar
  [✔️] natura-1.7.10-2.2.0.1.jar
  [✔️] NEIIntegration-1.4.0.jar
  [✔️] netherlicious-3.2.8.jar
  [✔️] NetherOres-[1.7.10]2.3.1-22.jar
  [✔️] NoMobSpawningOnPlants-1.1.jar
  [✔️] NoMoreRecipeConflict-0.3(1.7.10).jar
  [✔️] NotEnoughItems-1.7.10-1.0.5.120-universal.jar
  [✔️] NuclearCraft-1.9g--1.7.10.jar
  [✔️] OpenBlocks-1.7.10-1.6.jar
  [✔️] OpenModsLib-1.7.10-0.10.jar
  [✔️] overloadedarmorbar-1.7.10-1.0.0.jar
  [✔️] PlayerAPI-1.7.10-1.4.jar
  [✔️] RadixCore-1.7.10-2.1.3-universal.jar
  [📁] railcraft (folder)
  [✔️] Railcraft_1.7.10-9.12.2.1.jar
  [✔️] RedstoneArsenal-[1.7.10]1.1.2-92.jar
  [✔️] roguelike-1.7.10-1.5.0b.jar
  [✔️] RTG-1.1.2-GTNH (1).jar
  [✔️] RunicDungeons-1.1.7b.jar
  [✔️] Schematica-1.7.10-1.7.6.131-universal.jar
  [✔️] SolarExpansion-Basic-1.6a.jar
  [✔️] Steves-Carts-2-Mod-1.7.10.jar
  [✔️] Tails-1.7.10-1.4.1a.jar
  [✔️] Tainted-Magic-1.7.10-8.1.1.jar
  [✔️] tcinventoryscan-mc1.7.10-1.0.11.jar
  [✔️] TConstruct-1.7.10-1.8.8.jar
  [✔️] Thaumcraft-1.7.10-4.2.3.5.jar
  [✔️] Thaumcraft4Tweaks-1.5.7.jar
  [✔️] ThaumcraftMobAspects-1.7.2-2A.jar
  [✔️] ThaumicBases-1.3.1710.4.jar
  [✔️] Thaumic-Dyes-[1.7.10] 1.6.0-0.jar
  [✔️] thaumicenergistics-1.1.3.0.jar
  [✔️] ThaumicExploration-1.7.10-1.1-55.jar
  [✔️] ThaumicHorizons-1.5.4.jar
  [✔️] ThaumicTinkerer-2.5-1.7.10-164.jar
  [✔️] TheElysium-1.7.x-1.0.3.jar
  [✔️] ThermalDynamics-[1.7.10]1.2.1-172.jar
  [✔️] ThermalExpansion-[1.7.10]4.1.5-248.jar
  [✔️] ThermalFoundation-[1.7.10]1.2.6-118.jar
  [✔️] Totemic-1.7.10-0.6.2.jar
  [✔️] TravellersGear-1.7.10-1.16.6.jar
  [✔️] TwilightForest-2.4.3.jar
  [✔️] VillageNames-1.7.10-4.4.10a.jar
  [✔️] Waila-1.5.10_1.7.10.jar
  [✔️] Wawla-1.0.5.120.jar
  [✔️] weaponmod-1.14.3.jar
  [✔️] witchery-1.7.10-0.24.1.jar
  [✔️] WitcheryPatch-1.7.10-1.0.0.jar
  [✔️] WitchingGadgets-1.7.10-1.1.10.jar

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
I'm not immediately seeing anything obviously wrong in the code below 
Caused by: java.lang.ArrayIndexOutOfBoundsException: 15
	at biomesoplenty.common.blocks.BlockBOPCoral.func_149691_a(BlockBOPCoral.java:202) (getIcon)

Are any of your mods modifying/extending/adding corals?  Does it crash without Angelica?

I don't see anything immediately obviously thread unsafe or that would have been changed with Angelica...

```java
	public static enum CoralCategory {
		CAT1, CAT2;
	}
	private final CoralCategory category;
	
	private static final String[] coral = new String[] {"kelpbottom", "kelpmiddle", "kelptop", "kelpsingle", "pinkcoral", "orangecoral", "bluecoral", "glowcoral", "algae"};
	
	@Override
	public IIcon getIcon(int side, int meta) {
		if (meta < 8 || meta >= coral.length + 8) meta = 8;
		
		return textures[getMetaIndex(meta)];
	}
	public int getMetaIndex(int meta) {
		return (meta - 8) + category.ordinal() * 8;
	}
```

**Comment by gamemaster112ful** [comment]
https://mclo.gs/vzgcycm

Yeah, it does seem to be an issue even without Angelica. We use a mix of Biomes O' Plenty and Realistic Terrain Generation with Climate Control, which would be the only thing adding corals to the world.
