### ISSUE TITLE
[Request] Implement "Borderless Windowed/Fullscreen" within Angelica

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#519]
### Your GTNH Discord Username

PlayfulPiano

### Feature Request

Implement the ability to change the client to a Borderless variant. I.e. it still acts as a window but resized to fit your entire desktop screen & is prioritized on top of your taskbar/doesn't have a title bar. Also dependent on what monitor your client is currently on.

There are a couple implementations of this I believe (Fabric Borderless Mining, Embeddium++, Fullscreen Windowed, etc.), but so far when it comes to 1.7.10 the only variant I have found to work for me is, for whatever reason, this *external program* https://github.com/Mr-Technician/BorderlessMinecraft

I have no clue why only this one works, but others either do not properly change my window or make it go into a weird fullscreen which causes issues when taking screenshots / moving it to my second monitor.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by eigenraven** [comment]
FYI if you use lwjgl3ify, disabling window decorations in `config/lwjgl3ify.cfg` and making sure your launcher settings width/height match your monitor size should basically achieve borderless fullscreen. Having a proper GUI for this and toggling without restarting the game would still be a nice feature

**Comment by PlayfulPiano** [comment]
> FYI if you use lwjgl3ify, disabling window decorations in `config/lwjgl3ify.cfg` and making sure your launcher settings width/height match your monitor size should basically achieve borderless fullscreen. Having a proper GUI for this and toggling without restarting the game would still be a nice feature

I tried that in the past and while it helped with the title bar, my taskbar still was drawn on top of my game client.

**Comment by SKProCH** [comment]
If you use lwjgl3fy, you need to use a patched mod. Here is I'm patched a little for compatibility with modern GTNH: https://github.com/GTNewHorizons/Fullscreen-Windowed-Minecraft

**Comment by PlayfulPiano** [comment]
> If you use lwjgl3fy, you need to use a patched mod. Here is I'm patched a little for compatibility with modern GTNH: https://github.com/GTNewHorizons/Fullscreen-Windowed-Minecraft

oooh, is this the reason why the standard version of the mod didn't work for me on external monitors?

**Comment by SKProCH** [comment]
Standard version didn't work, because some functions of lwjgl 2 aren't implemented in lwjgl 3 compatibility layer (lwjgl3fy). So in this fork I've made some changes to use lwjgl 3 directly. It at least works for me now, so give it a try.

**Comment by SKProCH** [comment]
Yep, this is the jar i'm currently using: https://github.com/IlluminedProject/GTNH/raw/master/.minecraft/mods/fw-1.3.0-mc-1-7-10-backport.5+f89c1ca538.jar

**Comment by PlayfulPiano** [comment]
> Yep, this is the jar i'm currently using: https://github.com/IlluminedProject/GTNH/raw/master/.minecraft/mods/fw-1.3.0-mc-1-7-10-backport.5+f89c1ca538.jar

This one has the same problems I had with the other one. Second monitor (on extended) doesn't properly go borderless fullscreen. Alt tabbing minimizes the client window, prtnscr from a capturing program (e.g. greenshot) takes an image of a few seconds in the past / pauses the game, etc.

**Comment by Caedis** [comment]
just use a tiling window manager :trollface:

**Comment by isadora-6th** [comment]
BorderlessGaming program solved this issue for me, while working with backported sodium (while plugin mods did not)

**Comment by PlayfulPiano** [comment]
> BorderlessGaming program solved this issue for me, while working with backported sodium (while plugin mods did not)

it's already implemented via hodgepodge
