### ISSUE TITLE
gui scale auto not properly implemented

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/Angelica#52]
### Your GTNH Discord Username

boubou_19

### Mod Version

1.0.0-alpha2

### Java Version

Java 8

### Bug Report

option list is truncated :/
![2023-12-26_00 13 58](https://github.com/GTNewHorizons/Angelica/assets/12850933/b23361db-c299-4074-a938-1940e9f7a004)

### Mod List

GTNH 2.5.1 java 8 pack + mod updates required to make it load

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by bombcar** [comment]
more like boubou8

**Comment by mitchej123** [comment]
Mainly needs to scroll the options if they overflow...

**Comment by AnrDaemon** [comment]
Same effect with alpha12
Settings barely fit on auto/3.
![image](https://github.com/GTNewHorizons/Angelica/assets/6532485/c4018baf-1381-46e5-ac25-2d03d91433da)

**Comment by AnrDaemon** [comment]
It ALMOST fits. Just… does not look convincing that it actually shows the last item on screen.

**Comment by Pistonight** [comment]
Fixed by #219

**Comment by AnrDaemon** [comment]
Thanks!
