### ISSUE TITLE
Veinmining smeltery bricks causes crash, blocks and their collisions persist after mining.

### ISSUE THREAD

**Issue by Switchamafuck** [GTNewHorizons/Angelica#521]
### Your GTNH Discord Username

Switchamafuck

### Mod Version

1.0.0-alpha52

### Java Version

Java 8

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

Happens after veinmining smeltery bricks. The blocks and their collisions persist after veinmining (even after i got the drops), and can still be broken, but nothing drops and the game crashes soon after. It might be important to note that the persistance occurs with naturally generated smeltery bricks but no crash occurs.

[latest.log](https://github.com/user-attachments/files/15661341/latest.log)

### Mod List or GTNH Pack Version

[✔] +unimixins-all-1.7.10-0.1.17
  [🖿] 1.7 (folder)
  [✔] 1.7.10-MB_Battlegear2-Bullseye-1.0.8.3
  [✔] AdvancedBackups-forge-1.7.10-3.5.2
  [✔] AdvancedRocketry-1.7.10-1.4.0-32
  [✔] ae2fc-1.3.2-gtnh
  [✔] ae2stuff-0.5.1.61-mc1.7.10
  [✔] angelica-1.0.0-alpha52
  [✔] AOBD-2.9.2
  [✔] AOBDOC-1.0.5
  [✔] AppleCore-mc1.7.10-3.1.1
  [✔] appliedenergistics2-rv3-beta-404-GTNH
  [✔] archaicfix-0.7.2
  [✔] asmc-1.7.10-1.0.2.1
  [✔] ASMFixes-1.0
  [✔] autooredictconv-1.7.10-1.3.1
  [✔] BadMobs-1.0.1-1.7.10
  [✔] Baubles-1.7.10-1.0.1.10
  [✔] BBG-1.0.0
  [✔] bdlib-1.9.5.1-mc1.7.10
  [✔] BetterBuildersWands-0.8.1-1.7.10r92+aec06c3
  [✔] BetterBurning-1.7.10-0.4.2
  [✔] BetterPing-1.7.10-1.0
  [✔] BetterPlacement-MC1.7.10-1.0.0-1
  [✔] BiomesOPlenty-1.7.10-2.1.0.2308-universal
  [✔] Born in a Barn 1.7.x
  [✔] ChestTransporter-1.7.10-2.0.6
  [✔] Chisel-2.9.5.11
  [✔] Chunk-Pregenerator-1.7.10-4.4.5
  [✔] CodeChickenCore-1.2.1
  [✔] CoFHCore-[1.7.10]3.1.4-329
  [✔] Controlling-1.7.10-1.0.0.4
  [✔] CosmeticArmorReworked-1.7.10-v7
  [✔] craftingtweaks-mc1.7.10-1.0.88
  [✔] Ding-MC1.7.10v2
  [✔] Dynamic Lights-1.3.9a-MC1.7.10
  [✔] EasyConfigButton-1.0
  [✔] enderbatteries-MC1.7.10-0.1-5
  [✔] EnderCore-1.7.10-0.2.0.40_beta
  [✔] endercrop-1.7.10-1.2
  [✔] EnderIO-1.7.10-2.3.1.10_beta.0
  [✔] EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.13.56_beta
  [✔] EnderStorage-1.7.10-1.4.7.37-universal
  [✔] EnderTanks-rev16-beta1
  [✔] ExtraFixes-1.7.10-1.2.4b
  [✔] extrautilities-1.2.12
  [✔] falsepatternlib-mc1.7.10-1.2.4
  [✔] FancyBlockParticles-1.7.x-2.4.1
  [✔] Farseek-1.7.10-2.0.1
  [✔] FastLeafDecay-1.7.10-1.4
  [✔] fgtXray-1.7.10-1.0.8
  [✔] FloodLights-1.7.10-1.2.8-137
  [✔] FoamFix-1.7.10-universal-1.0.4
  [✔] GraveStone Mod 0.7.10.3
  [✔] gtnhlib-0.2.11
  [✔] HBM-NTM-.1.0.27_X4977
  [✘] HBM-NTM-.1.0.27_X4980.jar (disabled)
  [✔] iChunUtil-4.2.3
  [✔] IguanaTinkerTweaks-1.7.10-2.1.6
  [✔] InGameInfoXML-1.7.10-2.8.1.82-universal
  [✔] InventoryTweaks-1.59-dev-152
  [✔] IronBackpacks-1.7.10-1.2.20
  [✔] ironchest-1.7.10-6.0.62.742-universal
  [✔] IvToolkit-1.2.1
  [✔] JAOPCA-1.7.10-W.0.5.21
  [✔] LibVulpes-1.7.10-0.2.8-37-universal
  [✔] Login_Shield-1.7.10-2-gf6e21a7
  [✔] LunatriusCore-1.7.10-1.1.2.21-universal
  [✔] Mantle-1.7.10-0.3.2b
  [✔] mdecore-1.0
  [✔] Mekanism-Community-Edition-1.7.10-9.10.37-Core
  [✔] MobDismemberment-4.0.0
  [✘] mobsinfo-0.2.0.jar (disabled)
  [✔] MouseTweaks-2.4.4-mc1.7.10
  [✔] MultiMine-1.7.10
  [✔] natura-1.7.10-2.2.1a2
  [✔] netherportalfix-mc1.7.10-1.1.0
  [✔] NotEnoughEnergistics-1.7.10-1.4.2
  [✔] NotEnoughItems-2.6.2-GTNH-pre
  [✔] NotEnoughKeys-1.7.10-3.0.0b45-dev-universal
  [✔] NotEnoughResources-1.7.10-0.1.0-128
  [✔] OpenBlocks-1.7.10-1.6
  [✔] OpenModsLib-1.7.10-0.10.1
  [✔] OreExcavation-1.1.134
  [✔] OreTweaker-1.0.2-1.7.10
  [✔] overloadedarmorbar-1.7.10-1.0.0
  [✔] p455w0rdslib-1.7.10-1.0.4
  [✔] ReAuth-1.7.10-Forge-4.0.7
  [✔] RecurrentComplex-0.9.7.1.1
  [✔] RTG-1.7.10-1.1.1.7
  [✔] ServerUtilities-2.0.46-pre
  [✔] ShetiPhianCore-1.7.10-3.0.0
  [✔] Snad-1.7.10-1.6.01.31a
  [✔] spark-1.10.19-forge1710
  [✔] Streams-1.7.10-0.3.4
  [✔] TConstruct-1.7.10-1.8.8
  [✔] thermalcasting-0.0.3
  [✔] ThermalDynamics-[1.7.10]1.2.1-172
  [✔] ThermalExpansion-[1.7.10]4.1.5-248
  [✔] ThermalFoundation-[1.7.10]1.2.6-118
  [✔] ThermalSmeltery-Redux-v1.1
  [✔] ThermalTinkering-1.7.10-1.2.1
  [✔] TipTheScales-1.7.10-3.0.0.2
  [✔] trashslot-mc1.7.10-1.0.31
  [✔] UpdateCheckerMod-1.7.10
  [✔] Waila-1.5.10_1.7.10
  [✔] WailaHarvestability-mc1.7.10-1.1.6
  [✔] waterhooks-1.2.1
  [✔] Wawla-1.0.5.120
  [✔] Waystones-mc1.7.10-1.0.12
  [✔] WirelessCraftingTerminal-1.7.10-rv3-1.8.7.9b
  [✔] World-Stripper-1.0.0-1.7.10
  [✔] Xaeros_Minimap_21.10.41_Forge_1.7.10
  [✔] XaerosWorldMap_1.14.1.31_Forge_1.7.10

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Caedis** [comment]
Use GTNH fork of Tinkers

**Comment by Switchamafuck** [comment]
thx mate
