### ISSUE TITLE
Glitching inventory player model and random in-world artifacts

### ISSUE THREAD

**Issue by Chibu68** [GTNewHorizons/Angelica#530]
### Your GTNH Discord Username

Chibu68

### Mod Version

1.0.0-alpha50

### Java Version

Java 19

### Graphics Card Vendor

AMD iGPU

### Bug Report

The player model in the inventory is very glitchy and there is in-world artifacting as well (very noticeable on dark blocks).
[The file was too big so i made it a link instead.](https://cdn.discordapp.com/attachments/224191655375273985/1252608199232716862/2024-06-18_14-55-54.mp4?ex=6672d5cb&is=6671844b&hm=e07c34c3fbd9bc0076d7a31e00024e3fd64f01b410d518f5b45a88f6eb4e1967&)

Funnily enough, recording using OBS makes the glitchiness not as bad. Here's what it normally looks like.
https://github.com/GTNewHorizons/Angelica/assets/62471871/07089df8-be9a-4573-888e-2bf121f760d9

Interestingly, the galacticraft tab doesn't glitch at all as shown below.
[File is too big again](https://cdn.discordapp.com/attachments/841087712692928542/1252619975286325248/2024-06-18_15-43-16.mp4?ex=6672e0c2&is=66718f42&hm=e838c6ba0101f02134e78411da17b70ef8889e618ee9b3667e77f3e1e641a3ed&)

#### Pack version
GTNH 2.6.1

#### Mods I added
- World Edit
- Blur (blurs the background when in an inventory)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Chibu68** [comment]
Ok, the in-world artifacting got fixed by disabling Compact Vertex Format. I forgot to check for settings before posting this issue. Messing with the settings didn't help with the player model thing however.

**Comment by lawleagle** [comment]
this got fixed for me by setting `enableHudCaching` to `false` in `angelica-modules.cfg`

**Comment by Caedis** [comment]
Can you disable Blur as well as trying alpha52?

**Comment by Chibu68** [comment]
> Can you disable Blur as well as trying alpha52?

Sorry about the late reply. I kinda forgot about this post. Interestingly the issue seems to have fixed itself. I didn't change anything and I'm not sure when that changed.

**Comment by Caedis** [comment]
Thanks for confirming

**Comment by Chibu68** [comment]
> Thanks for confirming

Just to clarify, I didn't disable blur or try alpha52. It just got fixed by itself somehow.
