### ISSUE TITLE
Fog inconsistency between server and single player

### ISSUE THREAD

**Issue by Brunnosh** [GTNewHorizons/Angelica#531]
### Your GTNH Discord Username

Brunosh

### Mod Version

1.0.0-alpha52

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

No crashes or anything, just fog being inconsistent.
on single player worlds it works fine, changing the render distance slider actually changes something.
now on servers, anything past 12 view distance on the server.properties file does not change anything, tested it by going 1 below (11), and it was slightly closer, and 1 above (13), being exactly as 12 render distance.
for testing purposes i deleted angelica and installed optifine, disabling fog on it i could see to the full 20 chunks even on server

### Mod List or GTNH Pack Version

GTNH 2.6.1 no additional mods

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Brunnosh** [comment]
> Did you up the chunk distance in the server configuration to send further than 12? I have mine set to 24 (yes this is pretty extreme) and it works as expected.

isn't that just increasing view-distance on server.properties? if it is, then yes, i did it.

**Comment by OvermindDL1** [comment]
On my server I have 24 view-distance and on my client I have 24 view distance and fog seems correct, far into the distance?  I wonder what else differs...

**Comment by Brunnosh** [comment]
> On my server I have 24 view-distance and on my client I have 24 view distance and fog seems correct, far into the distance? I wonder what else differs...

what version of angelica are you using?

**Comment by Brunnosh** [comment]
> Mine is: `angelica-1.0.0-alpha51a-beta.34+8c12fe9acd.jar`

no luck, tried alpha51 and alpha50 but same thing, its so strange, it has to be something with my client since optifine works normally

**Comment by OvermindDL1** [comment]
What modpack are you running so we can try to duplicate?  Link or upload or so?

**Comment by Brunnosh** [comment]
> What modpack are you running so we can try to duplicate? Link or upload or so?

literally the packaged GTNH server and client with java 17, nothing more, nothing less

**Comment by OvermindDL1** [comment]
Huh, that's exactly what I'm running, GTNH 2.6.1 (with my slightly edited angelica but nothing about fog), although I'm running java21, I can't see how that would make a difference either though...

I wonder if this is yet another of those nvidia'isms that might need to be worked around...

I'll try to actually test mine in depth tonight with the latest released angelica though after work if someone could ping me in like 7 hours from the time of this message or so?

**Comment by Valeqs** [comment]
> Huh, that's exactly what I'm running, GTNH 2.6.1 (with my slightly edited angelica but nothing about fog), although I'm running java21, I can't see how that would make a difference either though...
> 
> I wonder if this is yet another of those nvidia'isms that might need to be worked around...
> 
> I'll try to actually test mine in depth tonight with the latest released angelica though after work if someone could ping me in like 7 hours from the time of this message or so?

ping

**Comment by Valeqs** [comment]
Isn't there a way to completly turn off the fog?

> Huh, that's exactly what I'm running, GTNH 2.6.1 (with my slightly edited angelica but nothing about fog), although I'm running java21, I can't see how that would make a difference either though...
> 
> I wonder if this is yet another of those nvidia'isms that might need to be worked around...
> 
> I'll try to actually test mine in depth tonight with the latest released angelica though after work if someone could ping me in like 7 hours from the time of this message or so?

Isn't there an option to remove the fog completly?

**Comment by OvermindDL1** [comment]
> > Huh, that's exactly what I'm running, GTNH 2.6.1 (with my slightly edited angelica but nothing about fog), although I'm running java21, I can't see how that would make a difference either though...
> > I wonder if this is yet another of those nvidia'isms that might need to be worked around...
> > I'll try to actually test mine in depth tonight with the latest released angelica though after work if someone could ping me in like 7 hours from the time of this message or so?
> 
> ping

Oh bugger, I took the screenshots but didn't have a browser available at the moment to upload them, here you go, this is how it looks to me at 11, 12, 13, and like 22 I think it was.


![2024-06-18_22 03 48](https://github.com/GTNewHorizons/Angelica/assets/401605/34f34c96-7779-4673-a9f1-cace2800b26e)
![2024-06-18_22 04 02](https://github.com/GTNewHorizons/Angelica/assets/401605/01cd9ce0-c5f2-4576-9e29-f02fa76bcde5)
![2024-06-18_22 04 14](https://github.com/GTNewHorizons/Angelica/assets/401605/f0b32ad9-7621-421a-9e58-e4e37a637d66)
![2024-06-18_22 04 29](https://github.com/GTNewHorizons/Angelica/assets/401605/320fe6f1-9a0f-4094-ab8c-4d33860d017f)

**Comment by Valeqs** [comment]
thats my fog at 24
![2024-06-28_14 46 30](https://github.com/GTNewHorizons/Angelica/assets/129291645/2117bfe4-5891-4d0e-9490-2be6c433b4c7)

**Comment by Valeqs** [comment]
> > > Huh, that's exactly what I'm running, GTNH 2.6.1 (with my slightly edited angelica but nothing about fog), although I'm running java21, I can't see how that would make a difference either though...
> > > I wonder if this is yet another of those nvidia'isms that might need to be worked around...
> > > I'll try to actually test mine in depth tonight with the latest released angelica though after work if someone could ping me in like 7 hours from the time of this message or so?
> > 
> > 
> > ping
> 
> Oh bugger, I took the screenshots but didn't have a browser available at the moment to upload them, here you go, this is how it looks to me at 11, 12, 13, and like 22 I think it was.
> 
> ![2024-06-18_22 03 48](https://private-user-images.githubusercontent.com/401605/344213527-34f34c96-7779-4673-a9f1-cace2800b26e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NTI4NjcsIm5iZiI6MTcxOTY1MjU2NywicGF0aCI6Ii80MDE2MDUvMzQ0MjEzNTI3LTM0ZjM0Yzk2LTc3NzktNDY3My1hOWYxLWNhY2UyODAwYjI2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQwOTE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjY2MDExNzZiMDcwMWU5ZWU1Y2QzZGZlY2NlMzI5ZTQzYThhYzczYWVmN2Q2NjBjMjZlOGFhZGNlMjA3YTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SgGk34kCx2mwYnXvWscra9wHkxAB5bpDlGitUmu2iYQ) ![2024-06-18_22 04 02](https://private-user-images.githubusercontent.com/401605/344213668-01cd9ce0-c5f2-4576-9e29-f02fa76bcde5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NTI4NjcsIm5iZiI6MTcxOTY1MjU2NywicGF0aCI6Ii80MDE2MDUvMzQ0MjEzNjY4LTAxY2Q5Y2UwLWM1ZjItNDU3Ni05ZTI5LWYwMmZhNzZiY2RlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQwOTE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzRlOWQyOTc4NGIzMzQwMWNjZjlhZjBkMzNiOGNmMDVlYzc1YTE2NTA0ODBjZTBhMjc4YTBmMWJkY2Q4NWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a2XsnjUxzJ4PEin8-M6TgmVfrQ1OhnUFGR7IMx9urOk) ![2024-06-18_22 04 14](https://private-user-images.githubusercontent.com/401605/344213703-f0b32ad9-7621-421a-9e58-e4e37a637d66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NTI4NjcsIm5iZiI6MTcxOTY1MjU2NywicGF0aCI6Ii80MDE2MDUvMzQ0MjEzNzAzLWYwYjMyYWQ5LTc2MjEtNDIxYS05ZTU4LWU0ZTM3YTYzN2Q2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQwOTE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDFkYTE5MGU1N2E3MDUxYjgwMmRkM2QxNGYyNDExYWE5OGIyNmFiMDExMmJjOThjYWFhM2ZhZmFjM2Q4NzdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f146Qgd00x6EuIH3BZyXs85S5N3gDBdDognvAS997kw) ![2024-06-18_22 04 29](https://private-user-images.githubusercontent.com/401605/344213755-320fe6f1-9a0f-4094-ab8c-4d33860d017f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NTI4NjcsIm5iZiI6MTcxOTY1MjU2NywicGF0aCI6Ii80MDE2MDUvMzQ0MjEzNzU1LTMyMGZlNmYxLTlhMGYtNDA5NC1hYjhjLTRkMzM4NjBkMDE3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQwOTE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDNiZWFiYTEzODNmZmFlNGRjYTM4MWUwMzg2MWZmOTgwZWFkNWE5YmUwYjk2MDgzMDJhNTRhMTU4NTI0YTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p9WcC3Rb6FLr5nQPKqg2j5r92tKUAR_6wc8B0KwU8EM)

Thats my fog at 24 
![2024-06-28_14 46 30](https://github.com/GTNewHorizons/Angelica/assets/129291645/49d303da-299c-4fa1-b8da-cc990f8083f9)

**Comment by Caedis** [comment]
What did you edit in Angelica?

**Comment by Valeqs** [comment]
> What did you edit in Angelica, @OvermindDL1?
> Is it based on alpha or beta?

I just downloaded it from the mirahaze website the java 17 version 2.6.1. It comes with alpha 50. I didnt change anything in the settings

**Comment by Caedis** [comment]
@Valeqs can you try alpha52?

**Comment by Valeqs** [comment]
> @Valeqs can you try alpha52?

Tried 50 51 52 49 41 same thing, i just wish there is an option to remove that fog completly

**Comment by Caedis** [comment]
What happens if you remove Angelica completely?

**Comment by Valeqs** [comment]
> What happens if you remove Angelica completely?

i replaced angelica with optifine once and the fog was gone. But the problem is you wont see polution and my fps went down to 90 instead of 144.

**Comment by Caedis** [comment]
I am talking without Angelica and Optifine

**Comment by Valeqs** [comment]
without angelica it crashes.

https://mclo.gs/iUtCNPj



> I am talking without Angelica and Optifine

**Comment by Caedis** [comment]
Can you post your fml client latest file?

**Comment by Valeqs** [comment]
[fml-client-latest.log](https://github.com/user-attachments/files/16039657/fml-client-latest.log)


> Can you post your fml client latest file?

**Comment by Caedis** [comment]
Can you disable BetterCrashes? Seems like that mod is hiding the true error

**Comment by Valeqs** [comment]
[fml-client-latest.log](https://github.com/user-attachments/files/16039691/fml-client-latest.log)


> Can you disable BetterCrashes? Seems like that mod is hiding the true error

**Comment by Caedis** [comment]
I think something is wrong with your instance. I just downloaded 2.6.1 and disabled Angelica and loaded into the pack without issue.

Can you try a fresh download of 2.6.1 (https://downloads.gtnewhorizons.com/Multi_mc_downloads/GT_New_Horizons_2.6.1_Java_17-21.zip)?

**Comment by Valeqs** [comment]
> I think something is wrong with your instance. I just downloaded 2.6.1 and disabled Angelica and loaded into the pack without issue.
> 
> Can you try a fresh download of 2.6.1 (https://downloads.gtnewhorizons.com/Multi_mc_downloads/GT_New_Horizons_2.6.1_Java_17-21.zip)?

I downloaded a new Profile. I didnt add anything and removed Angelica, It loaded. It may have something to do with replaymod or a newer version of twilight forest that I added to my mods folder.

I tried loading my new Instance with and without Angelica but there is no difference.

No Angelica 16 chunks (max is 16)
![2024-06-29_13 12 05](https://github.com/GTNewHorizons/Angelica/assets/129291645/191a311d-5fc7-4f05-aa86-3dcf9a968850)

With Angelica 16 Chunks (max is 32)
![2024-06-29_13 16 32](https://github.com/GTNewHorizons/Angelica/assets/129291645/24686df8-f234-496c-ba22-1a7931007927)

With Angelica 24 Chunks (max is 32)
![2024-06-29_13 16 57](https://github.com/GTNewHorizons/Angelica/assets/129291645/f519f37f-6e62-4db2-96c8-d3a198d99704)
/tim

**Comment by Caedis** [comment]
Least that solves that issue
Try adding the new mods 1 at a time.

Also, you did stop the server, change server.properties, then start the server, right?

**Comment by Valeqs** [comment]
https://imgur.com/GN2DKQ2

So now I created a new world in my old instance and as soon as a change gamemodes the render distance changes so it worked but it is only in creative possible, can I also get this in survival?

> Least that solves that issue Try adding the new mods 1 at a time.
> 
> Also, you did stop the server, change server.properties, then start the server, right?



> Least that solves that issue Try adding the new mods 1 at a time.
> 
> Also, you did stop the server, change server.properties, then start the server, right?

**Comment by Valeqs** [comment]
> Least that solves that issue Try adding the new mods 1 at a time.
> 
> Also, you did stop the server, change server.properties, then start the server, right?

I forgot to change it to 16 i didnt knew it only supports 16

**Comment by Caedis** [comment]
Oh, OH.

Try this [angelica-1.0.0-alpha42-beta.47+657645d883.jar.zip](https://github.com/user-attachments/files/16039851/angelica-1.0.0-alpha42-beta.47%2B657645d883.jar.zip)

Ignore the alpha42, its built off the beta branch.
Unzip it btw

**Comment by Valeqs** [comment]
> Oh, OH. > > Try this [angelica-1.0.0-alpha42-beta.47+657645d883.jar.zip](https://github.com/user-attachments/files/16039851/angelica-1.0.0-alpha42-beta.47%2B657645d883.jar.zip) > > Ignore the alpha42, its built from the beta branch. Unpacking it btw

no difference unfortunately. I replaced the 50alpha with this jar and still the same, only when im in creative in singeplayer it works.

> Oh, OH.
> 
> Try this [angelica-1.0.0-alpha42-beta.47+657645d883.jar.zip](https://github.com/user-attachments/files/16039851/angelica-1.0.0-alpha42-beta.47%2B657645d883.jar.zip)
> 
> Ignore the alpha42, its built off the beta branch. Unzip it btw

**Comment by Caedis** [comment]
Cool, im able to recreate it. Lemme see if i can find the cause

**Comment by Caedis** [comment]
Looks like its another mod that is causing it. Can't recreate it in the angelica dev env

**Comment by Caedis** [comment]
Found the issue. You can enable everything again.

Edit the config file "GregTech/Client.cfg" and change `B:RenderPollutionFog_true=true` to `B:RenderPollutionFog_true=false`

**Comment by Valeqs** [comment]
It worked thx for your help

> Found the issue. You can enable everything again.
> 
> Edit the config file "GregTech/Client.cfg" and change `B:RenderPollutionFog_true=true` to `B:RenderPollutionFog_true=false`

**Comment by OvermindDL1** [comment]
> What did you edit in Angelica, @OvermindDL1?
> Is it based on alpha or beta?

No edits in this one in the pictures, that was normal alpha52

**Comment by OvermindDL1** [comment]
> Found the issue. You can enable everything again.
> 
> Edit the config file "GregTech/Client.cfg" and change `B:RenderPollutionFog_true=true` to `B:RenderPollutionFog_true=false`

So was mine rendering correctly because I have a few hundred thousand pollution in my world?

**Comment by ah-OOG-ah** [comment]
> > Found the issue. You can enable everything again.
> > Edit the config file "GregTech/Client.cfg" and change `B:RenderPollutionFog_true=true` to `B:RenderPollutionFog_true=false`
> 
> So was mine rendering correctly because I have a few hundred thousand pollution in my world?

No, it's a bug. The pollution renderer was incorrectly capping render distance even when no pollution was present in the chunk - iirc Caedis made a PR to fix that

**Comment by OvermindDL1** [comment]
> > > Found the issue. You can enable everything again.
> > > Edit the config file "GregTech/Client.cfg" and change `B:RenderPollutionFog_true=true` to `B:RenderPollutionFog_true=false`
> > 
> > So was mine rendering correctly because I have a few hundred thousand pollution in my world?
> 
> No, it's a bug. The pollution renderer was incorrectly capping render distance even when no pollution was present in the chunk - iirc Caedis made a PR to fix that
> 

That's what I'm asking about, why was mine rendering fine then?  Standard GTNH pack with alpha 52 Angelica.

**Comment by Oninaig** [comment]
Is this still an issue in angelica 1.0.0-beta4 on GTNH 2.6.1?
