### ISSUE TITLE
Implement Zoom Feature into Angelica

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#532]
### Your GTNH Discord Username

PlayfulPiano

### Feature Request

I know that the proper GTNH pack has the potential to implement zume to the modlist in 2.7.0 (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16436), but personally I feel that incorporating a zoom feature within angelica would be a better fit, especially for a full package optifine replacement outside of GTNH specifically.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
I plan to integrate zume at some point if we can do a jar in jar solution.  But not a huge priority currently

**Comment by PlayfulPiano** [comment]
Gotcha, ty

**Comment by mitchej123** [comment]
It's also in the beta issue

**Comment by Caedis** [comment]
ive been playing with zume and i kinda like it

**Comment by Alexdoru** [comment]
done
