### ISSUE TITLE
Holo glasses makes screen darker when looking at fiery ingot from twilight

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/Angelica#535]
### Your GTNH Discord Username

skproch

### Mod Version

angelica-1.0.0-alpha51

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Usual chest, when not using holo glasses: 

![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/381281f0-8960-4eda-9f19-106e950ce20a)

With holo glasses equipped:

![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/c04cfd58-fea1-451e-bc8f-f46b43d0d16c)

Also, it darkens the screen not only when you open a chest, but when just looking at the container with fiery ingot.

### Mod List or GTNH Pack Version

GTNH 2.6.0
Updated Angelica, HoloInventory

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by SKProCH** [comment]
Also, same effect with fiery sword

**Comment by Caedis** [comment]
Appears to be fixed in dev
![image](https://github.com/GTNewHorizons/Angelica/assets/18713839/25644dc1-1c09-4cc0-8a62-6b2fc3be4a19)
