### ISSUE TITLE
Performance degredation on 2nd gen intel + linux

### ISSUE THREAD

**Issue by Richard-Rogalski** [GTNewHorizons/Angelica#54]
### Your GTNH Discord Username

rrogalski

### Mod Version

1.0.0-alpha1

### Java Version

Java 8

### Bug Report

Performance degradation with angelica+unimixins versus just unimixins. 18fps average with angelica, 38fps average without.

System info:
```
CPU: Intel i5-2520M (4) @ 3.200GHz
GPU: Intel 2nd Generation Core Processor Family
Linux 5.15
```

According to Mitch I don't have `GL40.GL_DRAW_INDIRECT_BUFFER`, which would explain the log spam. The gpu also doesn't do indirect multidraw.

Full log: https://mclo.gs/TRUtOCR

### Mod List

( stated above )

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by mitchej123** [comment]
Hopefully fixed by #60

**Comment by Richard-Rogalski** [comment]
Progress!!! :D currently at ~30fps. Still lower FPS than vanilla, but it is playable.
https://mclo.gs/DphBoem
^ tons of messages like these:
```
[Angelica]: Naughty naughty, someone's making a texture binding in a display list!
```
despite unimixins and angelica being the only mods.. no _enabled_ resource packs either. (also, the default resource pack icon is missing heh)

**Comment by mitchej123** [comment]
Im going to disable those messages and fix some of rhem
