### ISSUE TITLE
UI darkening/flickering if logistic pipes are in inventory and GL State Cache is enabled

### ISSUE THREAD

**Issue by KnightosMaster** [GTNewHorizons/Angelica#540]
### Your GTNH Discord Username

Knightos

### Mod Version

1.0.0-alpha50

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Whenever I have any logistic pipes in my inventory the UI flickers between regular and "dark" mode.
Regular:
![24-07-03-15:43:38](https://github.com/GTNewHorizons/Angelica/assets/655652/a1cb2bbb-eceb-4f53-b86b-737113f742c4)
Dark:
![24-07-03-15:43:49](https://github.com/GTNewHorizons/Angelica/assets/655652/25279192-0be7-400d-93ee-cf8f0cbb0530)
I tried to capture a gif of the flickering but it's probably too fast for it.
Interestingly the flickering appears in different places in different cases.
If the item is in my hand, the UI is dark, but if I pull the chat up it starts flickering (along with the whole ui)
If the item is not my hand, the UI flickers, but if I pull the chat up that does not flicker, the chat itself is not dark but the UI stays dark.
If the item is not on the hotbar, nothing flickers and it is not dark.
#501 also holds true, and also shows to the Personal Dimension Portal, in fact all the items that are affected by the bug are dark in NEI, while others are not, you can see in the image below that it is darker than usual.
![24-07-03-15:53:09](https://github.com/GTNewHorizons/Angelica/assets/655652/0ca88805-9594-451b-bdd8-c5f5cc096ad5)
Other items like the Treasure Chest Tier 3 which you can see is not dark is not affected by default, but turns dark whenever a pipe is connected to it.
![24-07-03-15:54:57](https://github.com/GTNewHorizons/Angelica/assets/655652/a618e233-0d32-4b78-a75b-5a710d19be29)
![24-07-03-15:55:01](https://github.com/GTNewHorizons/Angelica/assets/655652/c20efc31-4b7c-46b3-a994-f7980a81afd5)

I am on Linux, using the NVidia driver 550.90.07, and am using X11.
Turning off the GL State Cache fixes all of the above issues.

### Mod List or GTNH Pack Version

GTNH 2.6.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Caedis** [comment]
@mitchej123 think this could be renderPass related?
https://github.com/search?q=repo%3AGTNewHorizons/LogisticsPipes%20renderPass&type=code

**Comment by Cleptomania** [comment]
This was fixed in Logistics Pipes
