### ISSUE TITLE
Security Craft v1.8.13 is incompatible with Angelica

### ISSUE THREAD

**Issue by Oegrux** [GTNewHorizons/Angelica#541]
### Your GTNH Discord Username

vextox

### Mod Version

1.0.0-alpha52

### Java Version

Java 21

### Graphics Card Vendor

AMD iGPU

### Bug Report

Security Craft v1.8.13 crashes with Angelica, it always crashes at the end of stage 2 when loading the game, giving this error:
  
Caught exception from securitycraft
cpw.mods.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: java.lang.IllegalAccessException: Can not set static final java.lang.String field net.minecraft.block.Block.__OBFID to null value

There's no GTNH fork or hodgepodge fix for this mod.
I've tried a few performance mods with it, archaicfix, lwjgl3ify, hodgepodge, coretweaks, it still crashes, it crashes even on a fresh install with only Angelica and Java 8

### Mod List or GTNH Pack Version

Angelica
GTNH Lib
UniMixins
Security Craft

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Caedis** [comment]
Please post your fml-client-latest file

**Comment by Cleptomania** [comment]
Closing for same reason as #548, this is a problem with SecurityCraft
