### ISSUE TITLE
Game crashes when casting in smeltery

### ISSUE THREAD

**Issue by PlayerZeroFour** [GTNewHorizons/Angelica#543]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

I hit the smeltery's faucet to make some glass. It also happens with the casting table.

### Crash Report

https://mclo.gs/CiLQSPE
https://mclo.gs/1ILkSut
It happened multiple times, so I included multiple crash logs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by PlayerZeroFour** [comment]
Hey, I moved the smeltery  controller so that it's now all within the same chunk and it still happens occasionally. I only have the issue with this smeltery, so maybe it's an issue with seared stone?

**Comment by mitchej123** [comment]
Is it within the same subchunk? Each chunk is broken into subchunks that are 16 tall.  

Needs a fix on tinkers to use a concurrent safe container since it can be modified while rendering :-/
