### ISSUE TITLE
ClientFixer + Angelica = Russian font does not work

### ISSUE THREAD

**Issue by Xisdar** [GTNewHorizons/Angelica#545]
### Mod Version

angelica-1.0.0-alpha50

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

A small mod that patches classes, the purpose of which was to introduce other fonts, like smooth fonts using ascii_fat.png and ascii.png textures. Usually compatible with all mods. Popular in RU - UA community.
ClientFixer-1.0.jar 
https://github.com/gamerforEA/Minecraft-ClientFixer/releases/tag/1.0
With angelica there is a moment, with it US font normally patched it is smooth becomes, but with RU is not, it is thin and not beautiful.
Interested in whether it is possible to fix it?
Here are examples:
Without angelica mod: https://imgur.com/8gLsy7d
From Angelica: https://i.imgur.com/sXmBu1K.png

### Mod List or GTNH Pack Version

GT New Horizons-2.6.1
ClientFixer-1.0.jar 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by GribanovIvan** [comment]
disable "enableFontRenderer"

**Comment by mitchej123** [comment]
1) Please actually search the issues like you claim to have
2) If someone could reach out to the author and see if he'd be willing to relicense it as LGPL or something LGPL compatible I'd happily include it in Angelica; Alternatively
3) Happy for an ASM/Mixin fix, upstream fix, or alternative implementation
