### ISSUE TITLE
Shader Parsing Issue

### ISSUE THREAD

**Issue by calreveraster** [GTNewHorizons/Angelica#57]
### Mod Version

1.0.0 Alpha 3

### Java Version

Java 8

### Bug Report

It looks like the shaders system for angelica either isn't parsing into the /program folders when looking for the necessary shader files or maybe isnt seeing the .glsl file extensions some newer packs use - or maybe a combination of both. 

Major packs such as BSL, complementary, etc. house .glsl base files in the /program folder and then the vsh/fsh files in world specific folders, instead of having them at the root of the shader pack.  Older versions of complementary have a dummy version of the file in the root of the shader pack as well and throw an include - that also, for some reason, does not seem to work. The result of that is a bunch of progressively smaller versions of the screen in the corner: 

![image](https://github.com/GTNewHorizons/Angelica/assets/90051037/9947cf09-65d2-4ccf-b9ab-60fb9fed6f72)

When activating a shaderpack such as the latest BSL pack, angelica throws a bunch of file not found exceptions for these files. 

Suggest having it parse into /programs for the base files of the shaderpack. 

Latest version of BSL and a slightly older version of complementary attached for folder structure / include structure clarity. 

[BSL_v8.2.07.1.zip](https://github.com/GTNewHorizons/Angelica/files/13768660/BSL_v8.2.07.1.zip)
[ComplementaryShaders_v4.7.zip](https://github.com/GTNewHorizons/Angelica/files/13768678/ComplementaryShaders_v4.7.zip)

### Mod List

UniMixins 0.1.15
Angelica 1.0.0 alpha 3 
CoreTweaks 0.3.3.2
gtnhlib 0.0.13
hodgepodge 2.4.3

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by mitchej123** [comment]
Are you sure you're not using the old shadersmod version?  Because that error hasn't been seen since then, and "Shaders Initialized" message is also long gone...

Plus we're focused on sodium/rendering issues for now... shaders have a lot of state leakage that needs to be cleaned up.

**Comment by mitchej123** [comment]
![2023-12-24_22 02 57](https://github.com/GTNewHorizons/Angelica/assets/1894689/3a6d9f7b-e44b-4d2d-b9d1-40e98b7e472c)

Shaders have issues, but BSL_v8.2.07.1 loads just fine...

**Comment by calreveraster** [comment]
The main difference I'm seeing here is that I'm on java 8 and not using LWJGL - is java 17 a prereq for Angelica?

**Comment by calreveraster** [comment]
> Are you sure you're not using the old shadersmod version? Because that error hasn't been seen since then, and "Shaders Initialized" message is also long gone...
> 
> Plus we're focused on sodium/rendering issues for now... shaders have a lot of state leakage that needs to be cleaned up.

Also, totally understand if this isn't priority, but it's what I'm most looking for due to a series of things I'm hoping to do with some shaders in the near future, so I figured I'd report it now before I forgot. I know you guys are hard at work dealing with the immediate fires, and I deeply appreciate the work you're putting in to make this happen.

**Comment by mitchej123** [comment]
![image](https://github.com/GTNewHorizons/Angelica/assets/1894689/7331031d-8c07-477e-b94a-80a9f0b781d8)

![image](https://github.com/GTNewHorizons/Angelica/assets/1894689/fef4a18c-fcf4-4125-8738-7612a625931f)


Post your log, you're not running the version you think you are.  The "Shaders initialized" message is 100% from the old shaders mod and was removed in the push to alpha.


Java 8 and lwjgl2 work, I just prefer 17+ and 3.

**Comment by calreveraster** [comment]
So I went ahead and downloaded alpha 4, and didnt see it, so I redownloaded alpha 3 and it didn't reoccur. I'm not sure what the situation was there, but I apologize for the false ticket. 

I've noticed a few things with the shaders so far, so I'll go through and see what I notice and open a separate ticket for them. Thank you again for the hard work, this is already looking fantastic.
