### ISSUE TITLE
Need a key to change shaders

### ISSUE THREAD

**Issue by Goldppx** [GTNewHorizons/Angelica#573]
### Feature Request

Iris has a keybind that directly opens the shader selection screen, which is handy, and I'm requesting that Angelica add one of these as well
This is very helpful for the masses to test the Shader function
![图片](https://github.com/user-attachments/assets/252689e8-96b2-45ca-99bd-90e24f2cd8a7)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Goldppx** [comment]
Sorry I don't speak English, so I use a translator. The translation may not turn out to be very polite

**Comment by ImPro396** [comment]
How do i open the shader selection screen? I didnt find it in the options

**Comment by Radk6** [comment]
> How do i open the shader selection screen? I didnt find it in the options

It's disabled by default. You have to enable it in angelica-modules.cfg

**Comment by Goldppx** [comment]
> How do i open the shader selection screen? I didnt find it in the options
at GTNH 2.6.111\config\angelica-modules.cfg
set enableIris=true

**Comment by ah-OOG-ah** [comment]
As of the latest betas, it should be enabled by default. If you're upgrading from an older version you'll still have to enable it manually, although we can't do anything about that.
