### ISSUE TITLE
Crashes when using a wrench to point at a Gregtech machine

### ISSUE THREAD

**Issue by Tree-er233** [GTNewHorizons/Angelica#58]
### Your GTNH Discord Username

tree_er

### Mod Version

1.0.0-alpha4

### Java Version

Java 21

### Bug Report

https://mclo.gs/4a9ikMZ
Examples include auto-taping maintenance hatch and steel frames box.

### Mod List

![image](https://github.com/GTNewHorizons/Angelica/assets/110247896/d1f205c3-bb21-4025-b88c-d4e16bda2aa8)
The Angelica version is alpha4, please ignore the version in the picture.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by mitchej123** [comment]
Ah. Of course someone used the double version.  Will add tomorrow

**Comment by boubou19** [comment]
@Tree-er233 you should never build your own version of the mod, it makes debugging harder if you report tickets from a custom build.

**Comment by Tree-er233** [comment]
> @Tree-er233 you should never build your own version of the mod, it makes debugging harder if you report tickets from a custom build.

![image](https://github.com/GTNewHorizons/Angelica/assets/110247896/a2703263-b7cc-4bb0-b720-2fca9b5c4ad3)

**Comment by boubou19** [comment]
@Tree-er233 yes, and i'm telling you that even if you tested it with alpha 4, the user should never use custom builds unless they got told to do so.

**Comment by Tree-er233** [comment]
> @Tree-er233 yes, and i'm telling you that even if you tested it with alpha 4, the user should never use custom builds unless they got told to do so.是的，我告诉你，即使你用 alpha 4 测试了它，用户也不应该使用自定义版本，除非他们被告知这样做。

Okay, I get it. Sorry for the trouble.
