### ISSUE TITLE
The 'shadowdistance' option can't be saved after rebooting the game

### ISSUE THREAD

**Issue by NealDeal34** [GTNewHorizons/Angelica#582]
### Mod Version

1.0.0-alpha2

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

Every time I try to change the shadowdistance to 8, it will be rewritten to 32 after rebooting the game

### Mod List or GTNH Pack Version

angelica-1.0.0-beta2
bugtorch-1.2.14-GTNH
CoreTweaks-1.7.10-0.3.3.2

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
![image](https://github.com/user-attachments/assets/cd5a6997-a1ec-403c-944a-c73b1f9051c8)
![image](https://github.com/user-attachments/assets/a41c653a-c806-4c2e-8956-40af0dc65585)


Please read what you're agreeing to when making an issue
