### ISSUE TITLE
Custom Skybox like optifine

### ISSUE THREAD

**Issue by Gemoon1** [GTNewHorizons/Angelica#585]
### Feature Request

We need a feature to custom the skybox

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Radk6** [comment]
MCPF has that feature and it's included in Angelica (just disabled by default).

**Comment by Cleptomania** [comment]
This will probably work when we get around to hooking up MCPF, so sometime before a stable release, but probably a lower priority than finishing work for shaders.
