### ISSUE TITLE
AngelicaShaders + Sildurs' Shaders = everything is black

### ISSUE THREAD

**Issue by Pilzinsel64** [GTNewHorizons/Angelica#59]
### Your GTNH Discord Username

Pilzinsel64@pilzinsel64

### Mod Version

1.0.0-alpha4

### Java Version

Java 8

### Bug Report

Thank you a lot for this mod! It is amazing to see such a progress in 1.7.10 still.

However, I've tested this mod first on our modpack (based on After Humans, LITW and updated the most mods to GTNH version) and then without any other mods, see the mod list below.

We usually use OptiFine as we love the the shader "Sildurs' Vibrant Shader" and never want to play without. This shader does not work at all (well it loads, but that's all). Everything is black, the see picture blelow.

As reference I tried the BSL shader you used in your preview screenshot, this one works fine.

The author (Sildurs) recommands Iris over OptiFine. I know Angelica has the base of the Iris shader in, so maybe you can take this shader as reference to get it to work. Probably just a minor thing that's missing for OpenGL, but I'm a nooob in that topic. :D

Thanks in advance!

Screenshot:
![2023-12-26_10 01 12](https://github.com/GTNewHorizons/Angelica/assets/23138465/1d02f12e-e8b4-4a61-aa81-63478f2dd9b4)

My Graphics card:
NVIDIA GeForce RTX 3060 Titanium

The shader we use:
[Sildur's Vibrant Shaders v1.29 High.zip](https://github.com/GTNewHorizons/Angelica/files/13770219/Sildur.s.Vibrant.Shaders.v1.29.High.zip)
[Sildur's Vibrant Shaders v1.29 High.zip.txt](https://github.com/GTNewHorizons/Angelica/files/13770220/Sildur.s.Vibrant.Shaders.v1.29.High.zip.txt)

### Mod List

mixingasm@0.3
gtnhmixins@2.2.0
angelica@1.0.0-apha4
mixinextras@0.1.15
FML@7.10.99.99
notfine@1.0.0-apha4
spongemixins@2.0.1
unimixins-compat@0.1.15
Forge@10.13.4.1614
mcpatcherforge@1.0.0-alpha
gtnhlib@0.0.13
unimixins@0.1.15
gasstation@0.5.1
hodgepodge@2.4.3
mixinbooterlegacy@1.2.1
embeddium@1.0.0-apha4,mcp@9.05
unimixins-mixin@0.1.15

Or as picture of the files (very latest versions each):
![grafik](https://github.com/GTNewHorizons/Angelica/assets/23138465/5e6ab25f-b5c5-4e5e-95ea-b12acd461490)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by mitchej123** [comment]
Known issue.  We're focusing on the Sodium backport related issues first, and then branching out into Shaders for the beta release.

BSL/Complementary are known to mostly "work".  Sues & Sildurs have issues.

That being said, even the ones that do work have state leakage issues. 



There's plenty of known issues with shaders so bug reports on them aren't very helpful yet.  Bug fixes, however, are very welcome.

**Comment by mitchej123** [comment]
The main target is to get Shaders in General, and then BSL & Complementary working first, then branch out into the other ones.

**Comment by Pilzinsel64** [comment]
Alright, thank you. I will keep this open anyway and test future versions sporadically and let you know when something has changed. I hope this will help you anyway when the time comes. :)

**Comment by calreveraster** [comment]
> Known issue. We're focusing on the Sodium backport related issues first, and then branching out into Shaders for the beta release.
> 
> BSL/Complementary are known to mostly "work". Sues & Sildurs have issues.
> 
> That being said, even the ones that do work have state leakage issues.
> 
> There's plenty of known issues with shaders so bug reports on them aren't very helpful yet. Bug fixes, however, are very welcome.

I went looking and it seems like there's quite a few things in Complementary / BSL that are quirky just because the custom uniforms that have been temporarily hardcoded in to get things going don't include all of the uniforms that are needed to get all the little bits and bobs of the shader to be clean - and custom uniforms from things like sildurs and seus don't exist there yet. 

Based on the output log, I have a feeling a lot of the quirks both there and in some of the others are going to improve dramatically once custom uniforms actually become a thing, and itll be hard to track what's really a bug and what is just a uniform that isnt in the hardcoded list until then.
