### ISSUE TITLE
Weird Screen tearing/flickering when using shaders

### ISSUE THREAD

**Issue by PhoenixCyanFire** [GTNewHorizons/Angelica#592]
### Mod Version

1.0.0 beta 4

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

Flickering when using complementary shaders

https://github.com/user-attachments/assets/5519c62b-7a51-4aff-92ba-c122567ef9e8

### Mod List or GTNH Pack Version

GTNH Nightly build's newest version (as of 10:58 AM 2024/08/06)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Please read the final checklist that you agreed to
