### ISSUE TITLE
Not smooth horizon

### ISSUE THREAD

**Issue by PlutoSmile0** [GTNewHorizons/Angelica#596]
### Your GTNH Discord Username

pluto_0000

### Mod Version

angelica-1.0.0-beta4

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

I checked all the settings but could not fix the problem
I don't have a smooth transition between the skybox and the horizon

![2024-08-08_18 27 04](https://github.com/user-attachments/assets/4d4a2903-4604-4692-8625-f4387ae1d1f1)

### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.17
angelica-1.0.0-beta4
Carpenters_Blocks_v3.3.8.1_MC_1.7.10
clientfixer-1.0
CodeChickenCore-1.2.1
gtnhlib-0.4.2
HBM-NTM-.1.0.27_X5036
nofog-1.7.10b1-1.0
notenoughitems-2.5.27-gtnh
OpenComputers-MC1.7.10-1.8.3-089dd28-universal
tlskincape_1.7.10-1.4

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [x] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Do you have Iris/Shaders module enabled?

**Comment by PlutoSmile0** [comment]
> Do you have Iris/Shaders module enabled?

No

**Comment by PlutoSmile0** [comment]
Oh...
Never mind...
I just removed NoFog mod

**Comment by mitchej123** [comment]
There's an issue with fog and shaders that manifests itself exactly like that... which is why I asked.  Good to know the no fog is the issue, but also helpful to know that it's not just shaders.... 🤔
