### ISSUE TITLE
Crash on startup Beta 4

### ISSUE THREAD

**Issue by Darkenlord1** [GTNewHorizons/Angelica#597]
### Your GTNH Discord Username

ljedamos

### Mod Version

1.0.0-beta4

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/xZ5XSLw

### Mod List or GTNH Pack Version

GTNH 2.6.1
With updated:
CodeChickenCore-1.3.6
NotEnoughItems
and some thaum mods related to boots

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Read the readme as to gtnhlib version requirements.

**Comment by Darkenlord1** [comment]
Read through, updated gtnhlib, and now it just freezes at 33% load with "ting!" sound as loading is finished
https://mclo.gs/gtQneGi

**Comment by Caedis** [comment]
Read the readme as to Amazing Trophies version requirements.
