### ISSUE TITLE
Game Crashes With Special K

### ISSUE THREAD

**Issue by cpt-Tony** [GTNewHorizons/Angelica#599]
### Mod Version

1.0.0-beta4

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

[2024-08-10-2.log](https://github.com/user-attachments/files/16571390/2024-08-10-2.log)
[2024-08-10-1.log](https://github.com/user-attachments/files/16571392/2024-08-10-1.log)

Game crashes when I launch it with Special K. More specifically, the game crashed when I tried to set the game to fullscreen, afterwords the games crashes after the mods load (I think).

EDIT: I just tested special k on a vanilla 1.7.10 world and it still crashed when I enabled fullscreen :'( , so it looks like it's probably not Angelica's fault. It would still be nice if someone could help me out, but no problem if not. (special k works fine in 1.20 btw)

### Mod List or GTNH Pack Version

Mods:
  [✔] +unimixins-all-1.7.10-0.1.17
  [✔] angelica-1.0.0-beta4
  [✔] CodeChickenCore-1.3.6
  [✔] gtnhlib-0.4.2
  [✔] HBM-NTM-.1.0.27_X5036
  [✔] hodgepodge-2.5.44-pre
  [✔] NotEnoughItems-2.6.23-GTNH-pre

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by cpt-Tony** [comment]
I just tested special k on a vanilla 1.7.10 world and it still crashed when I enabled fullscreen :'( , so it looks like it's probably not Angelica's fault. It would still be nice if someone could help me out, but no problem if not.

**Comment by OvermindDL1** [comment]
`Special K` what an unfortunate name....

Well the log says `org.lwjgl.LWJGLException: Could not make context current` so I'm guessing it probably doesn't work with the older OGL being used in 1.7.10 rather than the newer contexts that are used later, unsure if anything could be done about that (at least until angelica manages to rewrite all ancient OGL API as a layer on top of modern, which it's surprisingly doing slowly over time, so maybe someday?)...
