### ISSUE TITLE
Crash with Archimede's Ships + gasesFramework (beta4)

### ISSUE THREAD

**Issue by huihiuhuai** [GTNewHorizons/Angelica#600]
### Mod Version

1.0.0-beta4

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

Crash Report: 
[crash-2024-08-13_22.02.53-client.txt](https://github.com/user-attachments/files/16600820/crash-2024-08-13_22.02.53-client.txt)

FML Log: 
[Uploading latest.log…]()

### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.17
angelica-1.0.0-beta4
archimedesshipsplus-1.7.10-1.8.1
gasesFramework-1.7.10-1.2.4
gtnhlib-0.4.2
hodgepodge-2.5.42
movingworld-1.7.10-1.8.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by xdeadstokex** [comment]
You are using GTNH Lib:0.3.3, update it to gtnhlib-0.4.2

**Comment by xdeadstokex** [comment]
Also I recommend this ships mod https://www.curseforge.com/minecraft/mc-mods/ships-mod-unofficial, no airship but you can stand on the ship

**Comment by huihiuhuai** [comment]
Updated GTNH Lib.  Still get a crash https://pastebin.com/ymZYfK5h

**Comment by huihiuhuai** [comment]
> Also I recommend this ships mod https://www.curseforge.com/minecraft/mc-mods/ships-mod-unofficial, no airship but you can stand on the ship

This mod is more buggy in my testing.

**Comment by xdeadstokex** [comment]
I tested on my side and Archimede's Ships work fine, maybe it is something else that cause you crash
Yes, the cuchaz ship was not intended to let player use modded block entities (but most block will work fine if you dont interact with it), but it does let you stand on your ship, which is cool :D

**Comment by huihiuhuai** [comment]
[latest.log](https://github.com/user-attachments/files/16600237/latest.log)

**Comment by xdeadstokex** [comment]
Did you turn on Iris shader in angelia-moldule ?

**Comment by huihiuhuai** [comment]
> I tested on my side and Archimede's Ships work fine, maybe it is something else that cause you crash Yes, the cuchaz ship was not intended to let player use modded block entities (but most block will work fine if you dont interact with it), but it does let you stand on your ship, which is cool :D edit: my damn country block pastebin for some reason, can you drag log here ?

Yeah only Angelica + Archimede's Ships will not crash.

**Comment by xdeadstokex** [comment]
Archimede ship cause crash, the log tell me something related to Iris in angelia, but I did test with both shader and non shader, but the shader one is buggy and they wont fix it for now cause it is still in testing, oh welp :D

**Comment by xdeadstokex** [comment]
And littleMaidMobX-1.7.x_0.1.3a.jar may slow your world loading (it spam the log with message)

**Comment by huihiuhuai** [comment]
> And littleMaidMobX-1.7.x_0.1.3a.jar may slow your world loading (it spam the log with message)

How do i avoid that

**Comment by xdeadstokex** [comment]
Idk, either dont use it or accept a little slower loading (like 0.1s, not much, i did test it)
(you can fix it if you have source and know how to mod)

**Comment by huihiuhuai** [comment]
This issue is Iris related. I should reopen it when the Iris module is not disabled by default.

**Comment by huihiuhuai** [comment]
Installing lwjgl3ify fix it.
