### ISSUE TITLE
TX Loader isn't mentioned as a required dependency (with "injectQPRendering" enabled)

### ISSUE THREAD

**Issue by unilock** [GTNewHorizons/Angelica#602]
### Your GTNH Discord Username

unilock

### Mod Version

1.0.0-beta2 and above

### Java Version

Java 21

### Graphics Card Vendor

AMD/ATI

### Bug Report

https://gist.github.com/unilock/64efa29e21394e9589675b2b4bb29eae

### Mod List or GTNH Pack Version

Occurs with only Angelica + GTNHLib + UniMixins

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [ ] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by unicornbloods** [comment]
That dependency is news to me. I run it with only Angelica + GTNHLib + UniMixins fine on beta 4

**Comment by unilock** [comment]
Oh, it appears it's only required when the `injectQPRendering` option is enabled in Angelica's config.

**Comment by mitchej123** [comment]
Considering that's pulling models from modern, that makes sense.  Also that's disabled by default currently afaik.
