### ISSUE TITLE
 Strange boundaries of chunks on the water

### ISSUE THREAD

**Issue by PlutoSmile0** [GTNewHorizons/Angelica#609]
### Your GTNH Discord Username

pluto_0000

### Mod Version

angelica-1.0.0-beta4

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

When I load new chunks, the ocean looks a little strange (if you reload the chunks, the borders disappear)

### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.17
angelica-1.0.0-beta4
BetterFps_1.0.0
Carpenters_Blocks_v3.3.8.1_MC_1.7.10
ChickenChunks_1.7.10_Recommended
clientfixer-1.0
CodeChickenCore-1.2.1
gtnhlib-0.4.2
HBM-NTM-.1.0.27_X5061
notenoughitems-2.5.27-gtnh
OpenComputers-MC1.7.10-1.8.3-089dd28-universal
spark-1.10.19-forge1710

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by PlutoSmile0** [comment]
![2024-08-21_12 08 05](https://github.com/user-attachments/assets/26f91e71-9e5f-489b-8495-dacf51f7cf2b)
![2024-08-21_12 08 01](https://github.com/user-attachments/assets/769708ec-3f9e-43c8-b227-ff95450ad8aa)
I forgot screenshots

**Comment by markusezzzz** [comment]
Попробуй удалить BetterFps

**Comment by Ethryan** [comment]
> Попробуй удалить BetterFps

Keep it in English please.

**Comment by Majora320** [comment]
Maybe related to #434? Try disabling translucency sorting.

**Comment by xdeadstokex** [comment]
@PlutoSmile0 BetterFPS may cause you this problem, bcs I only encountered this problem when I turn the Iris module on.
(Also dont use BetterFps, it cause problems, like a lot)

**Comment by Oninaig** [comment]
@PlutoSmile0 I am having the same issue but without BetterFPS installed 
![image](https://github.com/user-attachments/assets/8d1730f2-040d-4cfc-96fc-d79e6de8b9b6)

**Comment by xdeadstokex** [comment]
@Oninaig Do you have Iris module on or off ?

**Comment by xdeadstokex** [comment]
@TheVitya
[angeconfig.zip](https://github.com/user-attachments/files/17353257/angeconfig.zip)
try my config, I dont have the problem

**Comment by mitchej123** [comment]
![image](https://github.com/user-attachments/assets/b55f6938-b275-4006-a0c0-610bada72b21)
