### ISSUE TITLE
Getting `NoClassDefFound` Exception on latest beta

### ISSUE THREAD

**Issue by mainrs** [GTNewHorizons/Angelica#613]
### Mod Version

1.0.0-beta4

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

I had to update GTNHlib to `0.4.8` to include this mod into GTNH. However, the game doesn't launch and loading ends with the exception below:

https://mclo.gs/phXqaGx

### Mod List or GTNH Pack Version

GTNH 2.6.1 PrismLauncher zip install.

Custom mods installed on top include the ones below. However, the bug also happens once I disable these.

- EntityCulling
- Just Enough Calculations
- Navigator
- Notes

The only one that was enabled for the backtrace I uploaded was notes.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Caedis** [comment]
Updating Amazing Trophies as well

**Comment by mainrs** [comment]
> Update Amazing Trophies as well

Out of pure curiosity, how can it be that a completely unrelated mod being on an older version causes these issues? It doesn't appear inside the stack trace as far as I can tell.

**Comment by Caedis** [comment]
> 	Caused by: java.lang.NoClassDefFoundError: com/gtnewhorizons/angelica/mixins/interfaces/IModelCustomExt
    at glowredman.amazingtrophies.model.ModelWrapper$ModelCustomWrapperExt.<init>(ModelWrapper.java:42)

**Comment by mainrs** [comment]
> > Caused by: java.lang.NoClassDefFoundError: com/gtnewhorizons/angelica/mixins/interfaces/IModelCustomExt
> > at glowredman.amazingtrophies.model.ModelWrapper$ModelCustomWrapperExt.(ModelWrapper.java:42)

Nevermind. I take my words back :) that is for the help!
