### ISSUE TITLE
Inventory and UI render issue when holding Logistics Pipes

### ISSUE THREAD

**Issue by Oninaig** [GTNewHorizons/Angelica#623]
### Your GTNH Discord Username

oninaig

### Mod Version

1.0.0-beta4

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

1.) Items from the Logistics Pipes mod are very transparent in the UI.
2.) When holding a logistic pipe, the inventory UI will flicker rapidly.

See attached video.

https://github.com/user-attachments/assets/f9e9e6d9-d07d-47e7-99ad-77c79be70c37

No shaders, just angelica with default options.

This does not appear to be the same issue as https://github.com/GTNewHorizons/Angelica/issues/345

### Mod List or GTNH Pack Version

GTNH 2.6.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by recurrsivedev** [comment]
+1, uploading my own video as this requester's seems corrupted. 
I also notice that logistics pipes mess with the UI coloring when they are in a chest that you are looking at (also in the video)

https://github.com/user-attachments/assets/cab973f6-b09c-4050-ba58-a1b524668f6f

**Comment by Cleptomania** [comment]
This is fixed in the GTNH fork of logistics pipes I believe. 

https://github.com/GTNewHorizons/LogisticsPipes/pull/69
