### ISSUE TITLE
Crash when rendering ProjectRed circuits in 1.0.0-alpha4

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/Angelica#63]
### Your GTNH Discord Username

SKProCH

### Mod Version

1.0.0-alpha4

### Java Version

Java 21

### Bug Report

https://mclo.gs/bgU9jAC

### Mod List

[✔] +unimixins-all-1.7.10-0.1.14
  [🖿] 1.7 (folder)
  [✔] AdvancedSolarPanel-1.7.10-3.5.1a
  [✔] adventurebackpack-1.0.17-GTNH
  [✔] ae2fc-1.1.74-gtnh
  [✔] ae2stuff-0.6.0-GTNH
  [✔] AFSU-1.7.10-1.2.6-GTNH
  [✔] alchgrate-1.0.3-GTNH
  [✔] amazingtrophies-1.1.4
  [✔] AmunRa-GC-0.5.0
  [✘] angelica-1.0.0-alpha2.jar (disabled)
  [✔] angelica-1.0.0-apha4
  [✔] AngerMod-1.7.10-0.6.3
  [✔] AppleCore-3.2.12
  [✔] appliedenergistics2-rv3-beta-292-GTNH
  [✔] archaicfix-0.5.0
  [✔] ArchitectureCraft-1.8.6
  [✔] Aroma1997Core-1.7.10-1.0.2.16
  [✔] AromaBackup-1.7.10-0.1.0.0
  [✔] AsieLib-0.5.4
  [✔] Automagy-1.7.10-0.28.2
  [✔] Avaritia-1.46
  [✔] Avaritiaddons-1.6.0-GTNH
  [✔] backpack-2.2.12-GTNH
  [✔] bartworks-0.8.23
  [✔] battlegear2-1.3.0
  [✔] Baubles-1.0.3
  [✔] bdlib-1.7.10-1.9.8-GTNH
  [✔] beebetteratbees-0.3.1-GTNH
  [✔] BetterAchievements-1.7.10-0.1.3
  [✔] BetterBuildersWands-0.10.1-GTNH
  [✔] bettercrashes-1.3.5-GTNH
  [✘] BetterFoliage-MC1.7.10-2.0.17.jar (disabled)
  [✔] betterloadingscreen-1.5.3-GTNH
  [✔] betterp2p-1.1.20
  [✔] BetterQuesting-3.4.7-GTNH
  [✔] BiblioCraft[v1.11.7][MC1.7.10]
  [✔] BiblioWoods[BiomesOPlenty][v1.9]
  [✔] BiblioWoods[Forestry][v1.7]
  [✔] BiblioWoods[Natura][v1.5]
  [✔] binnie-mods-2.2.4
  [✔] BiomesOPlenty-1.7.10-2.1.0.2308-universal
  [✔] BlockLimiter-1.7.10-0.55
  [✔] blockrenderer6343-1.0.6
  [✔] BloodArsenal-1.2.11
  [✔] BloodMagic-1.4.3
  [✔] Botania-1.10.3-GTNH
  [✔] BotanicHorizons-1.0.19-GTNH
  [✔] BrandonsCore-1.7.10-1.0.0.13-GTNH
  [✔] bugtorch-1.2.12-GTNH
  [✔] buildcraft-7.1.38
  [✔] buildcraft-compat-7.1.16
  [✔] BuildCraftOilTweak-1.7.10-1.0.4
  [🖿] carpentersblocks (folder)
  [✔] CarpentersBlocks-3.4.1-GTNH
  [✔] catwalks-1.7.10-2.1.4-GTNH
  [✔] chisel-2.12.3-GTNH
  [✔] chiseltones-1.7.10-1.0.4-GTNH
  [✔] CodeChickenCore-1.2.0
  [✔] CoFHCore-[1.7.10]3.1.4-329
  [✔] CompactKineticGenerators-1.7.10-1.0
  [✔] Computronics-1.7.1-GTNH
  [✔] controlling-2.0.1
  [✔] CookingForBlockheads-1.2.16-GTNH
  [✔] CraftPresence-2.2.5-1.7.10
  [✔] CraftTweaker-3.2.13
  [✔] creativecore-1.3.31-GTNH
  [✔] CropLoadCore-1.7.10-0.1.10
  [✔] CropsPP-1.5.12
  [✔] custommainmenu-1.10.3
  [✔] defaultkeys-1.1.6
  [✔] defaultserverlist-1.7.10-1.4.0
  [✔] defaultworldgenerator-1.7.10-0.2
  [✔] Draconic-Evolution-1.2.1-GTNH
  [✔] DummyCore-1.17.0
  [✔] duradisplay-1.1.7
  [✔] DynamicSurroundings-1.7.10-1.0.6.4
  [✔] EMT-1.3.8
  [✔] endercore-0.2.19
  [✔] EnderIO-2.5.9
  [✔] EnderStorage-1.7.10-1.4.12
  [✔] EnderZoo-1.7.10-1.0.23
  [✔] EnhancedLootBags-1.1.0
  [✔] eternalsingularity-1.1.2
  [✔] extrautilities-1.2.13a
  [✘] fastcraft-1.25.jar (disabled)
  [✔] findit-1.1.0
  [✔] FloodLights-1.7.10-1.2.9
  [✔] Forbidden.Magic-0.6.7-GTNH
  [✔] Forestry-4.7.1
  [✔] forgelin-1.9.7-GTNH
  [✔] ForgeMultipart-1.4.1
  [✔] ForgeRelocation-1.7.10-0.0.3
  [✔] ForgeRelocationFMP-1.7.10-0.0.4
  [✔] fw-1.3.0-mc-1-7-10-backport.5+f89c1ca538
  [✔] gadomancy-1.2.0
  [✔] galacticgreg-1.0.10
  [✔] Galacticraft-3.0.75-GTNH
  [✔] GalaxySpace-1.2.15-GTNH
  [✔] gendustry-1.7.10-1.6.5.5-GTNH
  [✔] ggfab-0.3.9
  [✔] GoodGenerator-0.7.17
  [✔] GraviSuite-1.7.10-2.0.3
  [✔] gravisuiteneo-1.0.20
  [✔] gregtech-5.09.44.110
  [✔] GT.Scanner.Mod-1.7.2
  [✔] gtneioreplugin-1.1.3
  [✔] GTNewHorizonsCoreMod-2.2.55
  [✔] gtnhintergalactic-1.2.9
  [✔] gtnhlanth-0.11.9
  [✔] gtnhlib-0.0.13
  [✔] GTNH-TC-Wands-1.3.1
  [✔] GT-PlusPlus-1.10.54
  [✔] GTTweaker-2.0.5
  [✔] HardcoreDarkness-MC1.7.10-1.7
  [✔] HardcoreEnderExpansion-1.7.10-1.9.7-GTNH
  [✔] harvestcraft-1.1.4-GTNH
  [✔] Healer-1.2.1
  [✔] HelpFixer-1.7.10-1.1.0
  [✔] hodgepodge-2.4.3
  [✔] holoinventory-2.3.2-GTNH
  [✔] HungerOverhaul-1.7.10-1.0.4-GTNH
  [✔] hydroenergy-1.1.1
  [🖿] ic2 (folder)
  [✔] IC2 Crop Plugin Version 1.7.10-1.3.1
  [✔] IC2NuclearControl-2.5.1
  [✔] ifu-1.9.6
  [✔] IguanaTweaksTConstruct-2.3.0
  [✔] industrialcraft-2-2.2.828a-experimental
  [✔] InfernalMobs-1.7.9-GTNH
  [✔] InGameInfoXML-2.8.5
  [✔] INpureCore-1.1.5-GTNH
  [✔] inventorytweaks-1.6.1
  [✔] IronChest-6.0.74
  [✔] IronChestMinecarts-1.7.10-1.0.8
  [✔] irontanks-1.7.10-1.2.6
  [✔] JABBA-1.3.1
  [✔] journeymap-1.7.10-5.1.4p6-fairplay
  [✔] JustEnoughCalculation-1.7.10-3.8.5
  [✔] kekztech-0.9.6
  [✔] kubatech-0.13.12
  [✔] littletiles-1.2.9-GTNH
  [✔] logisticspipes-1.0.8-GTNH
  [✔] lootgames-1.7.10-2.0.8
  [✔] LunatriusCore-1.7.10-1.1.7-GTNH
  [✔] lwjgl3ify-1.5.7
  [✔] magicbees-2.7.1-GTNH
  [✔] malisiscore-0.14.9
  [✔] malisisdoors-1.14.0-GTNH
  [✔] Mantle-0.3.7
  [✔] mobsinfo-0.1.13-GTNH
  [✔] ModTweaker2-0.9.10
  [✔] modularui-1.1.24
  [✔] MouseTweaks-2.4.9-GTNH
  [✔] mxrandom-0.2.0
  [✔] Natura-2.5.7
  [✔] naturescompass-1.7.10-1.3.6-GTNH
  [✔] NEIAddons-1.13.0
  [✔] NEICustomDiagram-1.5.14
  [✔] NEIIntegration-1.3.3
  [✔] neodymium-1.7.10-0.1.8.4+nomixin
  [✔] netherportalfix-1.7.10-1.1.2
  [✔] NodalMechanics-1.7.10-1.1.-6-GTNH
  [✔] NotEnoughEnergistics-1.4.6
  [✔] NotEnoughItems-2.4.13-GTNH
  [✔] nutrition-0.0.5
  [✔] oauth-1.7.10-1.06.1-GTNH
  [✔] OpenBlocks-1.8.3-GTNH
  [✔] OpenComputers-1.9.21-GTNH
  [✔] OpenGlasses-1.4.2-GTNH
  [✔] OpenModsLibs-1.7.10-0.10.6
  [✔] OpenModularTurrets-1.7.10-2.2.11-247
  [✔] openprinter-1.7.10-0.1.3-GTNH
  [🖿] OpenSecurity (folder)
  [✔] opensecurity-1.7.10-1.0.120-GTNH
  [✔] Opis-1.3.9-mapless
  [✔] Opticubes-1.7.10-1.0.0
  [✘] OptiFine_1.7.10_HD_U_E7.jar (disabled)
  [✔] overloadedarmorbar-1.0.3
  [✔] Pam's Harvest the Nether 1.7.10a
  [✔] personalspace-1.0.28
  [✔] PlayerAPI-1.4.3
  [✔] ProjectBlue-1.1.12-GTNH
  [✔] ProjRed-4.8.1-GTNH
  [✔] Railcraft-9.15.3
  [✔] RandomThings-2.4.6
  [✔] RemoteIO-1.7.10-2.4.8
  [✔] roguelike-1.7.10-1.5.3-GTNH
  [✔] RWG-alpha-1.3.9-pre
  [✔] Schematica-1.9.4-GTNH
  [✔] ServerUtilities-2.0.7
  [✔] SGCraft-1.7.10-1.3.13-GTNH
  [✔] sharewhereiam-2.0.2
  [✔] sleepingbag-1.7.10-0.1.4
  [✔] SoundFilters-0.8_for_1.7.X
  [✔] SpecialMobs-3.4.3
  [✔] SpiceOfLife-2.1.1-carrot
  [✔] SSP-1.1.2-GT-NH-Mod
  [✔] StevesAddons-1.7.10-0.10.27
  [✔] StevesCarts-1.7.10-2.0.2
  [✔] StevesFactoryManager-1.1.7-GTNH
  [✔] StorageDrawers-1.12.2-GTNH
  [✔] StorageDrawersBop-1.7.10-1.11.17-GTNH
  [✔] StorageDrawersForestry-1.7.10-1.11.17-GTNH
  [✔] StorageDrawersMisc-1.7.10-1.11.18-GTNH
  [✔] StorageDrawersNatura-1.7.10-1.11.17-GTNH
  [✔] structurecompat-0.4.0
  [✔] structurelib-1.2.9
  [✔] SuperTic-1.7.10-1.2.5
  [✔] Tainted-Magic-7.6.3-GTNH
  [✔] tcinventoryscan-1.7.10-1.0.12-GTNH
  [✔] tcneiadditions-1.2.2
  [✔] tcnodetracker-1.7.10-1.1.7
  [✔] TConstruct-1.10.13-GTNH
  [✔] TecTech-5.3.23
  [✔] TGregworks-1.7.10-GTNH-1.0.25
  [✔] Thaumcraft-1.7.10-4.2.3.5a
  [✔] Thaumcraft4Tweaks-1.5.18
  [✔] ThaumcraftMobAspects-1.7.10-1.0.0-GTNH
  [✔] thaumcraftneiplugin-1.7.10-1.7a
  [✔] ThaumcraftResearchTweaks-1.0.6
  [✔] Thaumic Machina-1.7.10-0.2.1
  [✔] Thaumic-Based-1.5.6
  [✔] thaumicboots-1.1.0
  [✔] thaumicenergistics-1.5.4-GTNH
  [✔] Thaumic-Exploration-1.2.0-GTNH
  [✔] ThaumicHorizons-1.4.2
  [✔] thaumicinsurgence-0.2.7
  [✔] ThaumicTinkerer-2.8.5
  [✔] TiCTooltips-1.3.0
  [✔] Tinkers-Defense-1.2.1d
  [✔] TMechworks-0.3.0
  [✔] TooMuchLoot-1.7.10-4.1.0-GTNH
  [✔] torohealth-1.0.4
  [✔] Translocator-1.1.2.21
  [✔] TravellersGear-1.7.10-1.16.6
  [✔] travellersgearneo-1.0
  [✔] TwilightForest-2.5.1
  [✔] txloader-1.6.3
  [✔] Universal-Singularities-8.6.7
  [✔] visualprospecting-1.2.1
  [✔] Waila-1.6.5
  [✔] WailaHarvestability-1.7.10-1.1.10-GTNH
  [✔] WAILAPlugins-0.3.0
  [✔] WanionLib-1.8.4
  [✔] WarpTheory-1.2.17-GTNH
  [✔] Wawla-1.7.10-1.1.3-GTNH
  [✔] WirelessCraftingTerminal-1.10.1
  [✔] witchery-1.7.10-0.24.1
  [✔] WitcheryExtras-1.1.14
  [✔] WitchingGadgets-1.3.6-GTNH
  [✔] WR-CBE-1.7.10-1.4.8
  [✔] YAMCore-0.5.86
  [✔] Ztones-1.7.10-2.2.2

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by SKProCH** [comment]
On 1.0.0-alpha2 everything seems like running fine

**Comment by SKProCH** [comment]
Also, seems like after crash catched by NotEnoughtCrashes game window dimmed.
Original: ![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/dc89f089-b779-43cd-b73a-19163e784ec1)
After crash: 
![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/e96b5a7a-61de-4e35-a77f-7a779e330eea)

**Comment by embeddedt** [comment]
Crash should be fixed in alpha 5.

**Comment by mitchej123** [comment]
>  I have searched the issues and haven't found a similar issue.

I literally just closed an issue with the same problem and it was fixed in alpha 5.

**Comment by SKProCH** [comment]
> > I have searched the issues and haven't found a similar issue.
> 
> I literally just closed an issue with the same problem and it was fixed in alpha 5.

Oh, sorry. I'll test an alpha 5 rn.

**Comment by SKProCH** [comment]
Alpha 5 working fine. Thanks.
