### ISSUE TITLE
Server connection 

### ISSUE THREAD

**Issue by Biskupsky** [GTNewHorizons/Angelica#630]
### Mod Version

Beta 5

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

After adding angelica my friend cannot join server (LAN). It keeps showing "logging in" and I see on chat just "<player> left the game.
What I found in latest.log when he tried to join:
[22:13:18] [Server thread/INFO]: Silvercappuccino lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(14) + length(83314253) exceeds writerIndex(1283): UnpooledHeapByteBuf(ridx: 14, widx: 1283, cap: 1283)], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[22:13:18] [Server thread/INFO]: Silvercappuccino left the game

### Mod List or GTNH Pack Version

Mods list attached 
![56](https://github.com/user-attachments/assets/35f207a8-7b2f-4c00-8c9b-a6526f2e90a0)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
LAN mode isn't supported.  If this is a dedicated server please respond back and I'll reopen

**Comment by Biskupsky** [comment]
We dont use server, always played LAN
How can I play it now?

**Comment by Biskupsky** [comment]
I would really aprreciate your help here, for months I modified all mods parameters to be proportional for better render thanks to angelica 😬😬😬 if important - our packs are tottaly same (mods, config etc)

**Comment by mitchej123** [comment]
I'd recommend running a dedicated server as a separate process on your machine.  LAN mode is too buggy, we're not going to support it.

**Comment by Biskupsky** [comment]
Ah that's the problem, idk at all how to do it properly with mods :v and will have to use my computer still as server, cuz there is no way to buy server with 60gb of space for world :v I guess

**Comment by Biskupsky** [comment]
Do you recommend any hosting for best stabilization of modded server ? With heavy mods and heavy world (needs a lot of space)

**Comment by Glease** [comment]
you can run the server right on your own PC, provided you have enough RAM available. We have a guide on our wiki explaining how to do so https://wiki.gtnewhorizons.com/wiki/Server_Setup_(Windows,_Local_Host)

**Comment by Biskupsky** [comment]
I have 48gb of ram so I guess getting server close to be so efficient would cost milions 🥹🥹 guess PC my last option

**Comment by Biskupsky** [comment]
Yeah ok, but isn't it tutorial dedicated for GTNH modpack? Need universal one keeping Angelica on board 
Honestly never hosted outside LAN and that's gonna be challanging for me :v

**Comment by Biskupsky** [comment]
I made some casual java server with mods but in console of the server I can see same issue with "logging in" as my friend got when joining by LAN

**Comment by mitchej123** [comment]
Angelica isn't a server side mod and shouldn't be on the server.  If he's having the same problem it's not angelica.

**Comment by Biskupsky** [comment]
Nah this time I couldnt join server
Used my VPN IP: server port 
It loggs but I got same issue code line like my friend on LAN with "logging in"

**Comment by Biskupsky** [comment]
Im struggling to make it work, cuz world is not in use for many days 😂 and have no clue how to make it work without LAN

**Comment by Biskupsky** [comment]
You think deleting angelica from mods from server might help ? Thats strange it doesnt work

**Comment by mitchej123** [comment]
If angelica is on the server, 100% remove it.  If this fixes things please report back as it should do nothing on the server.  If removing it has no impact, then it's not an Angelica issue.

**Comment by Biskupsky** [comment]
It doesnt 
I joined server based on VPN ip without client and server Angelica and still same issue :/ help

**Comment by mitchej123** [comment]
This is not the appropriate place to ask for help for non angelica related problems.  Go to legacy modding for generic 1.7.10 support, or gtnh discord for NH support

**Comment by Biskupsky** [comment]
Ook

**Comment by Biskupsky** [comment]
I made server (based on your GTNH ready one) and it still doesnt work. latest log from server:
https://mclo.gs/60RsASN
Doesnt matter if it creates new world or I put my main world that I used to play earlier

**Comment by Lyfts** [comment]
@Biskupsky You launched a vanilla server which you of course can't join from a modded client.  I don't see how this is even remotely related to Angelica though.

**Comment by mitchej123** [comment]
I agree, I don't believe this to be an angelica issue...
