### ISSUE TITLE
crash with Serene Seasons

### ISSUE THREAD

**Issue by iamsoNewBee** [GTNewHorizons/Angelica#637]
### Your GTNH Discord Username

0

### Mod Version

0

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

as the title

### Mod List or GTNH Pack Version

0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by brandyyn** [comment]
No crash report or log will get you no help. I use Angelica and Serene Seasons together with no problems.

**Comment by iamsoNewBee** [comment]
Then why I still crash like this
