### ISSUE TITLE
Torch light 

### ISSUE THREAD

**Issue by Iguals** [GTNewHorizons/Angelica#654]
### Your GTNH Discord Username

igualscoco

### Mod Version

1.0.0beta7

### Java Version

Java 8

### Graphics Card Vendor

Nvidia RTX 3060Ti

### Bug Report

How do you solve the problem of softening the torches on the ground? I haven't found any on discord or github 
If duplicate post I'm sorry 
Thank you for your help 
![image](https://github.com/user-attachments/assets/a2b8e86b-8f04-4fa0-9c25-9f2a599988db)

### Mod List or GTNH Pack Version

GTNH 2.6.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Caedis** [comment]
Enable smooth lighting

**Comment by Iguals** [comment]
Thank you for your reply, but smooth light is already activated in the settings

**Comment by xdeadstokex** [comment]
@Iguals judging by your image, did u have Iris shader on ? Currently that is a problem with shader, I try alot of way to fix it but to no avail.

**Comment by Iguals** [comment]
Yes Iris in enable, I use ComplementaryShaders_v4.6
![image](https://github.com/user-attachments/assets/a3d939b4-9709-47ff-80ab-1bcf6a5f18c8)

**Comment by mitchej123** [comment]
![Screenshot_20241013-100215](https://github.com/user-attachments/assets/81b95d38-a696-4d75-be2b-b6e81b12baf4)
