### ISSUE TITLE
Angelica breaks Netherlicious Spectral Dew texture

### ISSUE THREAD

**Issue by Shahelion** [GTNewHorizons/Angelica#656]
### Mod Version

1.0.0-beta6

### Java Version

Java 8

### Graphics Card Vendor

AMD/ATI

### Bug Report

With Angelica present, the Spectral Dew fluid has no texture, instead using the black and magenta checkerboard. Fluid block items in the inventory are fine, as are the buckets. It's just in-world that isn't working. 
![2024-10-12_10 24 32](https://github.com/user-attachments/assets/90043074-96bb-496d-a73c-df3785f757ff)
![2024-10-12_10 25 27](https://github.com/user-attachments/assets/f9656a95-e27b-4fea-ba05-c1ded819f340)

### Mod List or GTNH Pack Version

Reproducible with just Angelica and Netherlicious. Was not an issue with Angelica beta5.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by brandyyn** [comment]
problem is you have sodium fluid renderer enabled, disable it.
