### ISSUE TITLE
Angelica - Low FPS When running on AMD GPU (7900 XTX)

### ISSUE THREAD

**Issue by Alexhupp** [GTNewHorizons/Angelica#662]
### Your GTNH Discord Username

Military Grade Chicken Nugget

### Your Pack Version

2.6.1

### Your Server

SP/Any

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Upon launching into the game and joining a world I expected to find no issues and be able to relatively easily play and just enjoy the game.

### The Reality

Upon launching into the game and joining a world I found that my FPS was absolute dog water, sitting directly at 1, after consulting those in the GTNH Discord for help we have found that I was not running on my CPU's limited IGPU and that it was running on my full GPU, even through that it was still showing my FPS as 1.
![image](https://github.com/user-attachments/assets/dace80a1-2581-4a49-a0b8-8ce0d0e195ce)
![image](https://github.com/user-attachments/assets/4d4e67db-cf81-46a6-9b96-a5cfbd0798e8)

### Your Proposal

> I don't know what exactly to propose here however this seems like a big issue to have FPS issues on AMD gpu's in this case a newer gpu from amd.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Zenovis** [comment]
Just wanted to chime in. I have a 7800xt and It run just fine. With Shaders I go from 80fps on optifine -> 160+ on Angelica.
Perhaps something else is going on, or its directly related to the 7900 xtx.

**Comment by Alexhupp** [comment]
I don't know, but I straight up cannot run even with the latest version after updating mods on 2.6.1 higher than 1 FPS on angelica, without it and even with Optifine I get proper performance.

**Comment by Radk6** [comment]
No issues on my 7800 XT either. One thing I noticed about your screenshot is that you seem to have outdated GPU drivers. It says `23.40.28.240312`, while mine say `24.9.1.240926`. 

There is a chance Windows overwrote the drivers with some old/generic ones and that could be why you're getting bad performance.

**Comment by mitchej123** [comment]
Try updating the drivers.  The included sodium engine is very driver (and version) dependent

**Comment by Alexhupp** [comment]
Will try

**Comment by Alexhupp** [comment]
That did seem to be the issue, A weird one to encounter but oh well, it is solved.

**Comment by mitchej123** [comment]
It's bad enough, at least for intel drivers, Sodium for 1.20.x added intel driver version detection to inform users via an annoying popup...

**Comment by mitchej123** [comment]
Which is odd, it's using standard multi draw functionality 🤷

**Comment by Deolute** [comment]
I'm late to chime in, but I have similar reproducible issue with RDNA2 + 7700k with latest drivers. Turning off chunk multi-draw restores to old 2.6.1 performance, from low 40fps to 140 (cap).
