### ISSUE TITLE
Connected Textures implementation for full optifine replacement?

### ISSUE THREAD

**Issue by timb8g** [GTNewHorizons/Angelica#670]
### Feature Request

Hi Guys,

is there an effort to implement a connected texture module in angelica?

With angelica my setup is running way smoother than with optifine, but without connected textures I cant live :)

By the way, I have not found another connected textures mod for MC 1.7.10. Maybe I am wrong. Do you know if there is an alternative for optifine?

Have a nice day

Tim

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by BlueHero233** [comment]
Angelica doesnt yet have a dedicated button to turn CTM on and off at will but there is MCPF (mcpatcher forge, which you shoulda read about before ticking that box)
Its a config in angelica mod options “mcPatcherForgeFeatures”
You have to turn it true and restart your instance to take effect
Note that any visual bugs, rendering errors and related crashes when you have this feature turned on will be shelved, as ctm compatibility isnt top of priority atm, here be dragons
