### ISSUE TITLE
[Shaders]: Tileentities does not cast shadows

### ISSUE THREAD

**Issue by Darek505** [GTNewHorizons/Angelica#688]
### Your GTNH Discord Username

darek505

### Mod Version

1.0.0-beta13

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Shaders

Yes: Please put relevant information about shaderpack in the report(what shaderpack, any special settings of note, etc)

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Bug Report

Shaders used: BSL_v8.2.09 | ComplementaryReimagined/Unbound_r5.3

![2024-10-29_22 38 46](https://github.com/user-attachments/assets/858b4ed6-c973-41c0-9432-f73dfc8b17ef)

![2024-10-29_22 39 32](https://github.com/user-attachments/assets/1adb3bd5-fdda-4c9e-8825-7b2c199d41c7)

### Mod List or GTNH Pack Version

  [✔] +unimixins-all-1.7.10-0.1.18
  [✔] angelica-1.0.0-beta14
  [✔] gtnhlib-0.5.18

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Cleptomania** [comment]
For number 2 here, that is from separateAo, see #685

**Comment by ah-OOG-ah** [comment]
> For number 2 here, that is from separateAo, see #685

The blocky lighting issue is visible, yes, but what he's talking about are the shadows cast by the grass/torch - they're much larger than the blocks in question should be casting.

**Comment by czerwonogrodzki** [comment]
Regarding issue 4 - it seems like TAA antialiasing is affected, both in BSL and Complementary; using only FXAA works fine

**Comment by Darek505** [comment]
A few new bugs I could find:

version used - `1.2) - 3.2)` - 1.0.0-beta14,
`4.2)` - https://github.com/GTNewHorizons/Angelica/commit/538b38898ca82d450913f4243f0e35cfe422a03f (probably known?)



1.2) Enchanted items in hand do weird things with water:

<details>

<summary></summary>

https://github.com/user-attachments/assets/7735c3d6-c50a-472b-bd47-5b1fd35fb8c9


https://github.com/user-attachments/assets/8e51ede4-5a7c-447e-8485-7d995e6a43cc


https://github.com/user-attachments/assets/03c813e7-e40a-4b51-a661-5d8cb9ae0b9c



</details>

2.2) FOV changes as if underwater, but camera is not in water (very close in fact):

<details>

<summary></summary>

https://github.com/user-attachments/assets/8ff6cb8e-c107-4ce0-a799-76776208f7d2

![2024-10-30_21 21 53](https://github.com/user-attachments/assets/8f88dd2d-61ed-4933-a9a6-f6cd4aa30e51)
![2024-10-30_21 21 56](https://github.com/user-attachments/assets/4392ba96-a798-4a21-94c1-7ee7a7d3b2bd)


</details>

3.2) Hitting a mob with a glowing texture (spider, enderman) does weird things with rendering (forced vanilla skybox, broken alpha):

<details>

<summary></summary>


https://github.com/user-attachments/assets/194b975d-2b41-4092-93a3-a6de02c6dd0a


</details>

4.2) (probably known?) BSL only: happens after https://github.com/GTNewHorizons/Angelica/commit/538b38898ca82d450913f4243f0e35cfe422a03f, day is considered night:


<details>

<summary></summary>

https://github.com/user-attachments/assets/5b90d32b-33d7-4e00-88f8-03ea749f83c5



</details>

**Comment by ah-OOG-ah** [comment]
Can you split these up into multiple bugs reports? It makes it much easier to find and close issues.

**Comment by Darek505** [comment]
I noticed that this doesn't work on some tileentities from other mods, like hbm's ntm:

![2024-10-31_21 45 25](https://github.com/user-attachments/assets/1a7de894-53ef-4401-b11b-2d2800dfacae)


some tileentities cast shadows, but most don't
