### ISSUE TITLE
Failed to create shader rendering pipeline

### ISSUE THREAD

**Issue by Guy-that-exists** [GTNewHorizons/Angelica#692]
### Mod Version

1.0.0-beta14

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Shaders

Yes: Please put relevant information about shaderpack in the report(what shaderpack, any special settings of note, etc)

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Bug Report

[fml-client-latest.log](https://github.com/user-attachments/files/17564948/fml-client-latest.log)
I used BSL Original v8.3, I didn't change the configs of the shader or the mod

### Mod List or GTNH Pack Version

Angelica 1.0.0-beta14
GTNH Lib 0.5.18
UniMixins 0.1.19

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by ah-OOG-ah** [comment]
This will be fixed in a future version of BSL. For now, if you really want to use 8.3 you'd have to edit the shader yourself or find someone who can.

**Comment by Cleptomania** [comment]
BSL 8.3 has an incompatibility with Angelica in its current release. This has been fixed by BSL and will be in their next release(I’m not sure when that is planned for).

We are not at this time planning to add a patch for the thing that was broken in Angelica. In the meantime, BSL 8.2 should work fine
