### ISSUE TITLE
[Shaders]: "Incomplete" blocks such as grass, torch, saplings, etc. cast a "full" shadow, which can actually be larger than the block itself

### ISSUE THREAD

**Issue by Darek505** [GTNewHorizons/Angelica#695]
### Your GTNH Discord Username

darek505

### Mod Version

1.0.0-beta14

### Bug Report

Shaders used: BSL_v8.2.09 | ComplementaryReimagined/Unbound_r5.3

![2024-10-29_22 49 51](https://github.com/user-attachments/assets/311b23db-6246-40c6-8bb7-1f39ac8ce62f)
![2024-10-29_22 49 55](https://github.com/user-attachments/assets/3b5ab9a7-ec49-456e-b672-d38fe7ffedf5)

![2024-10-29_22 46 14](https://github.com/user-attachments/assets/799ead9a-a6cf-42d7-835d-c8267b556def)
![2024-10-29_22 47 13](https://github.com/user-attachments/assets/f52e7fe0-fad8-40cf-8cd7-b4fcc16687b1)

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Shaders

Yes: Please put relevant information about shaderpack in the report(what shaderpack, any special settings of note, etc)

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Mod List or GTNH Pack Version

[✔] +unimixins-all-1.7.10-0.1.18
[✔] angelica-1.0.0-beta14
[✔] gtnhlib-0.5.18

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by ah-OOG-ah** [comment]
I meant one bug per bug report :laughing:

**Comment by Darek505** [comment]
That is, 8 reports?

**Comment by ah-OOG-ah** [comment]
Yes, because we can also close them one by one instead of waiting until every part is resolved :stuck_out_tongue:. It's how GH issues are designed.
