### ISSUE TITLE
Non full height snow blocks aren't rendered correctly

### ISSUE THREAD

**Issue by Marvun** [GTNewHorizons/Angelica#71]
### Your GTNH Discord Username

ichheissemarvin

### Mod Version

1.0.0-alpha7

### Java Version

Java 19

### Bug Report

Snow blocks that don't have the full height and have adjacent snow blocks, have no textures on the side, so you can look through them.
https://github.com/GTNewHorizons/Angelica/assets/56234595/455f12db-d26e-484f-b99e-1dac3cb40d02

### Mod List or GTNH Pack Version

GTNH 2.5.1 with the updated mod version for angelica +
![image](https://github.com/GTNewHorizons/Angelica/assets/56234595/9cec082a-b56f-4777-ba84-dedde062ecc3)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by Caedis** [comment]
Can you add those additional mods 1 at time to see which causes it?
Also check without any of them to make sure its not Angelica itself.

**Comment by Marvun** [comment]
> Can you add those additional mods 1 at time to see which causes it? Also check without any of them to make sure its not Angelica itself.

I deactivated all four of them in multimc, but the bug still persists. 
And btw i deactivated fastcraft too, since it isn't compatible anyway.

**Comment by mitchej123** [comment]
Try with alpha11

**Comment by Marvun** [comment]
Can confirm, it is fixed with alpha11.
