### ISSUE TITLE
Crash with connected blocks mod lord of the rings 1.7.10

### ISSUE THREAD

**Issue by firstkalik** [GTNewHorizons/Angelica#714]
### Your GTNH Discord Username

firstkalik

### Mod Version

angelica-1.0.0-beta15

### Bug Report

[crash-2024-11-01_17_25_06-client.txt](https://github.com/user-attachments/files/17601790/crash-2024-11-01_17_25_06-client.txt)

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Shaders

No

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Mod List or GTNH Pack Version

	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.3.7} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	ClientFixer{1.0} [ClientFixer] (minecraft.jar) 
	UCHIJA	unimixins{0.1.17} [UniMixins] (+unimixins-all-1.7.10-0.1.17 (1).jar) 
	UCHIJA	unimixins-mixin{0.1.17} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.17 (1).jar) 
	UCHIJA	unimixins-compat{0.1.17} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.17 (1).jar) 
	UCHIJA	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.17 (1).jar) 
	UCHIJA	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.17 (1).jar) 
	UCHIJA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.17 (1).jar) 
	UCHIJA	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.17 (1).jar) 
	UCHIJA	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.17 (1).jar) 
	UCHIJA	mixinextras{0.1.17} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.17 (1).jar) 
	UCHIJA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UCHIJA	DamageIndicatorsMod{3.3.2} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.3.2.jar) 
	UCHIJA	mcpatcherforge{1.0.0-alpha} [MCPatcherForge] (angelica-1.0.0-beta15.jar) 
	UCHIJA	notfine{1.0.0-beta15} [NotFine] (angelica-1.0.0-beta15.jar) 
	UCHIJA	archaicfix{0.7.4} [ArchaicFix] (archaicfix-0_7_4.jar) 
	UCHIJA	gtnhlib{0.5.2-pre} [GTNH Lib] (gtnhlib-0.5.2-pre.jar) 
	UCHIJA	angelica{1.0.0-beta15} [Angelica] (angelica-1.0.0-beta15.jar) 
	UCHIJA	embeddium{1.0.0-beta15} [Embeddium] (angelica-1.0.0-beta15.jar) 
	UCHIJA	AppleCore{3.3.2} [AppleCore] (AppleCore-3_3_2.jar) 
	UCHIJA	BetterSigns{1.6.4.B ported} [BetterSigns] (better_signs.jar) 
	UCHIJA	BetterHorseHud{1.0} [Better Horse Hud] (BetterHorseHud-1.7.10-1.0.jar) 
	UCHIJA	xModBlocker{1.0} [xModBlocker] (Blocker-client.jar) 
	UCHIJA	bugtorch{1.2.13} [BugTorch] (bugtorch-1_2_13.jar) 
	UCHIJA	carbonconfig{1.1.3} [Carbon Config Library] (CarbonConfig-1.7.10-1.2.4 (1).jar) 
	UCHIJA	chunkpregenerator{1.8} [Chunk Pregenerator] (Chunk_Pregenerator_V1_7_10-1_8_1.jar) 
	UCHIJA	customnpcs{1.9-beta2} [CustomNPC+] (CustomNPCs- Ver 1.jar) 
	UCHIJA	elegant_networking{3.14} [ElegantNetworking] (elegant-networking-1.7.10-3.14.jar) 
	UCHIJA	entityculling{@VER@} [EntityCulling] (entityculling-1.6.4-mc1.7.10 (1).jar) 
	UCHIJA	fastleafdecay{1.1} [Fast Leaf Decay] (fastleafdecay-1.7.10.jar) 
	UCHIJA	fullbright{Client} [§cFullbrightFixed] (Fullbright_Fixed.jar) 
	UCHIJA	GameOfTronesMenu{1.1.1} [GameOfTronesMenu] (GameOfThronesMainMenu-1.0.jar) 
	UCHIJA	gammaanticheat{1.0} [§cgammaanticheat] (Gamma-Anti-Cheat-Client (1).jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152-1.7.10.jar) 
	UCHIJA	librariescore{1.0.0} [LibrariesCore] (LibrariesCore-1.0.jar) 
	UCHIJA	lotr{v1.11} [§6LOTR+] (LOTR+RU Update 1.11-v25.10.24-18.44.58.jar) 
	UCHIJA	lotrclient{1.3.0} [§6LOTR Client] (LOTR_Client (1).jar) 
	UCHIJA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore_1.7.10_1.1.2.21_universal.jar) 
	UCHIJA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJA	NBTEdit{1.7.2.2} [In-game NBTEdit] (nbtedit_1.7.10 (1).jar) 
	UCHIJA	neodymium{0.3.3-unofficial} [Neodymium Unofficial] (neodymium-mc1_7_10-0_3_3-unofficial.jar) 
	UCHIJA	overlaymod{1.1.1} [overlaymod] (overlaymod-1.0-client.jar) 
	UCHIJA	reportsystem{1.1.1} [reportsystem] (reportmenu-1.0-clientObf.jar) 
	UCHIJA	Schematica{1.7.6.131} [Schematica] (Schematica_1.7.10_1.7.6.131_universal.jar) 
	UCHIJA	screenshotsmod{1.0} [screenshotsmod] (Simple Screenshot Viewer.jar) 
	UCHIJA	simplefpsmod{1.0} [§6SimpleFps] (SimpleFps (1).jar) 
	UCHIJA	spark{1.10.35} [spark] (spark-1.10.19-forge1710.jar) 
	UCHIJA	stablefps{1.0} [StableFPS+] (StableFPS+.jar) 
	UCHIJA	tabmod{1.1.1} [tabmod] (TabMod-1.0-clientObf.jar) 
	UCHIJA	weaponmaster_ydm{4.2.4} [YDMs Weaponmaster] (weaponmaster_ydm-forge-1_7_10-4_2_4.jar) 
	UCHIJA	WGEnter{1.0} [WGEnter] (WGEnterClient.jar) 
	UCHIJA	world-tooltips{1.2.3} [World-Tooltips] (world-tooltips-1.7.10-1.2.3-79.jar) 
	UCHIJA	worldedit{6.1.1} [WorldEdit] (worldedit_forge_mc1.7.10_6.1.1_dist.jar) 
	UCHIJA	worldedit-cui{1.0} [WorldEdit Client User Interface] (WorldEditCUI-1.7.10-1.0.0.jar) 
	UCHIJA	zoomermod{1.0} [§czoomermod] (Zoomer - Simple Zoom.jar) 
	UCHIJA	epic_name_change{1.0} [epic_name_change] (ClientName.jar) 
	UCHIJA	preloader{1.0} [preloader] (loader.jar) 
	UCHIJA	helper{1.0} [LuxinfineHelper] (LuxinfineHelper-1.7.10-client.jar) 
	UCHIJA	neirecipehandlers{1.1.0-BETA} [NEI Recipe Handlers] (neiRecipeHandlers-1_1_0-BETA.jar) 
	(LuxinfineHelper) Loaded coremods: 19 plugins loaded:
   -> Name: 'FMLCorePlugin', Depends: '[]', Priority: '0' (forge-1.7.10-10.13.4.1614-1.7.10.jar)
   -> Name: 'FMLForgePlugin', Depends: '[]', Priority: '0' (forge-1.7.10-10.13.4.1614-1.7.10.jar)
   -> Name: 'CCCDeobfPlugin', Depends: '[]', Priority: '0'
   -> Name: 'CarbonConfigHooks', Depends: '[]', Priority: '1002' (CarbonConfig-1.7.10-1.2.4 (1).jar)
   -> Name: 'ClientFixer', Depends: '[]', Priority: '1001' (ClientFixer.jar)
   -> Name: 'CodeChickenCorePlugin', Depends: '[]', Priority: '0' (CodeChickenCore-1_3_7.jar)
   -> Name: 'FldLoadingPlugin', Depends: '[]', Priority: '1001' (fastleafdecay-1.7.10.jar)
   -> Name: 'FMLPlugin', Depends: '[]', Priority: '0' (InventoryTweaks-1.59-dev-152-1.7.10.jar)
   -> Name: 'ExampleHookLoader', Depends: '[]', Priority: '0' (LibrariesCore-1.0.jar)
   -> Name: 'LoadingPlugin', Depends: '[]', Priority: '2147483567' (loader.jar)
   -> Name: 'LOTRLoadingPlugin', Depends: '[]', Priority: '1001' (LOTR+RU Update 1.11-v25.10.24-18.44.58.jar)
   -> Name: 'helper', Depends: '[]', Priority: '2147483647' (LuxinfineHelper-1.7.10-client.jar)
   -> Name: 'NEICorePlugin', Depends: '[]', Priority: '0' (NotEnoughItems-1.7.10-1.0.5.120-universal.jar)
   -> Name: 'AllCore', Depends: '[]', Priority: '0' (+unimixins-all-1.7.10-0.1.17 (1).jar)
   -> Name: 'AngelicaTweaker', Depends: '[]', Priority: '0' (angelica-1.0.0-beta15.jar)
   -> Name: 'AppleCore', Depends: '[]', Priority: '1100' (AppleCore-3_3_2.jar)
   -> Name: 'ArchaicCore', Depends: '[]', Priority: '0' (archaicfix-0_7_4.jar)
   -> Name: 'BugTorchEarlyMixins', Depends: '[]', Priority: '0' (bugtorch-1_2_13.jar)
   -> Name: 'GTNHLibCore', Depends: '[]', Priority: '-1000' (gtnhlib-0.5.2-pre.jar)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by mitchej123** [comment]
LuxinfineHelper needs compat on their side.  We had a discussion in discord and it's ARR & obfuscated and potentially being commercially sold.  I have no interest in supporting this combination.

**Comment by mitchej123** [comment]
If you can reproduce the issue without that mod, please upload the entire fml-client-latest.log
