### ISSUE TITLE
Snow layer blocks don't have a hitbox

### ISSUE THREAD

**Issue by Marvun** [GTNewHorizons/Angelica#72]
### Your GTNH Discord Username

ichheissemarvin

### Mod Version

1.0.0-alpha7

### Java Version

Java 19

### Bug Report

Besides not rendering correctly as stated in #71, it seems like snow layer blocks also don't have a correct hitbox, since i can just walk through them. 
https://github.com/GTNewHorizons/Angelica/assets/56234595/618c3ca5-00c2-482e-ade2-03a0efda9048

### Mod List or GTNH Pack Version

GTNH 2.5.1 with the updated mods for angelica

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by mitchej123** [comment]
Try again with alpha11

**Comment by Marvun** [comment]
Can confirm, it is fixed with alpha11.
