### ISSUE TITLE
Tile entities, entities and some transparent blocks such as water cause distortion

### ISSUE THREAD

**Issue by MichalLasocha** [GTNewHorizons/Angelica#74]
### Your GTNH Discord Username

rawhav0kk

### Mod Version

1.0.0-alpha7

### Java Version

Java 21

### Bug Report

When irisi shaders are enabled, entities and tile entities do not render correctly, being misplaced and deformed. There are no logs of value that I was able to find, however it is tied to the camera position, and from 126.5,0 to 13.1,0 ( to simplify my explanation ill refer to yaw as X and pitch as Y )
It also occurs for every X value with Y of 90 (looking straight down) and does not occur at all when Y is equal to 0. Screen resolution, aspect ratio and FOV do not affect the issue. I assume there is some kind of miscalculation of a perspective going on. 
![4](https://github.com/GTNewHorizons/Angelica/assets/75432277/13b5002d-7bea-46e6-a7f8-210635d4be51)
![3](https://github.com/GTNewHorizons/Angelica/assets/75432277/bf2a0bbe-cc6b-4ea0-90e2-2bc16a436541)
![2](https://github.com/GTNewHorizons/Angelica/assets/75432277/c48151bd-75ed-4b4b-9e1a-0dded55652c4)
![1](https://github.com/GTNewHorizons/Angelica/assets/75432277/0d5aa441-3e93-4bc0-b8ab-a2bde1fef1f1)

### Mod List or GTNH Pack Version

GTNH 2.5.1 (with FTBLib and FTBUtils, fastcraft disabled, hodgepoge, chickenlib updated to the latest version) 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by calreveraster** [comment]
Can confirm, also seeing this happen - it also seems (for me) to occur significantly *more* often on newer java versions 

when running on java 8, this happens far, far less (i've only seen it twice so far despite extensive testing). On java 17 it happens almost every time.
