### ISSUE TITLE
Use Chunk Multi-Draw might not work properly

### ISSUE THREAD

**Issue by Arborsm** [GTNewHorizons/Angelica#75]
### Your GTNH Discord Username

Arbor

### Mod Version

1.0.0-alpha7

### Java Version

Java 17

### Bug Report

*  Install Angelica makes fps down below 50 and less, but turned off the `Use Chunk Multi-Draw` seems fix it.
* Hardware: AMD 5700XT AMD R5-4600H
![33e520b1272d3ab241672baa5d42ba2a](https://github.com/GTNewHorizons/Angelica/assets/44860537/96f8cc89-b4a3-4a09-accb-c35822178232) 
![0c512892ac0f3fc6df69b3a1e205c3ac](https://github.com/GTNewHorizons/Angelica/assets/44860537/3ff0f05c-1dd3-46c3-a559-e437c13c267a)

### Mod List or GTNH Pack Version

GTNH 2.5.1 (fastcraft disabled, hodgepoge, chickenlib updated to the latest version)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by Arborsm** [comment]
![image](https://github.com/GTNewHorizons/Angelica/assets/44860537/49d442de-3e9a-4d7b-a93b-81d557c507fc)
![image](https://github.com/GTNewHorizons/Angelica/assets/44860537/6ff34d43-1a5e-4267-9e0a-3cfb57c49595)

**Comment by embeddedt** [comment]
One of the provided comparison screenshots shows FastCraft being enabled, and the other screenshot shows the renderer being in multidraw mode, not oneshot.

**Comment by AlotOfBlahaj** [comment]
same problem on RX6600XT
