### ISSUE TITLE
Most items appear too bright / completely white

### ISSUE THREAD

**Issue by Ableytner** [GTNewHorizons/Angelica#755]
### Your GTNH Discord Username

ableytner

### Mod Version

1.0.0-beta22

### Bug Report

When using shaders, most items abruptly change brightness when looking at the sun and appear completely white when looking at reflective blocks. This doesn't seem to affect blocks in item form and tinkers tools, but every other item. The bug appears in the overworld and personal dimension. 
This problem didn't appear in GTNH-nightly744 (angelica1.0.0-beta20)
Shaders: ComplementaryNeon (Sampsa's shaders)

https://github.com/user-attachments/assets/b6dfb35f-81ab-4620-b531-35e78ab0fccd

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Shaders

Yes: Please put relevant information about shaderpack in the report(what shaderpack, any special settings of note, etc)

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Mod List or GTNH Pack Version

GTNH-nightly753

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by travismking** [comment]
https://github.com/GTNewHorizons/Angelica/issues/758 

is the same, downgrading to beta 20 fixes
