### ISSUE TITLE
When using shaders, held items turn into white box when looking at placed blocks

### ISSUE THREAD

**Issue by Red00** [GTNewHorizons/Angelica#758]
### Your GTNH Discord Username

Jeen

### Mod Version

angelica-1.0.0-beta23.jar

### Bug Report

Using shaders, when holding most items (tinkers tools do not seem affected), and looking at a block placed in the world, the item in hand turns into bright a white square. Only seems to happen when close to block, when WALIA comes up. Pointing at a distance does not have an effect. (see screenshots).

Shaders tested:
Complementary Shaders 4.6 Sampsa NeonRP
Complementary Unbound 5.3

![2024-11-27_17 12 26](https://github.com/user-attachments/assets/ff225a16-1657-4094-aa36-e82c66354836)
![2024-11-27_17 12 32](https://github.com/user-attachments/assets/eda4d19a-36de-442f-a609-3b969f32ce49)

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Shaders

Yes: Please put relevant information about shaderpack in the report(what shaderpack, any special settings of note, etc)

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Mod List or GTNH Pack Version

GTNH 2.7.0-RC-1
Issue is not present in angelica-1.0.0-beta20.jar, and copying that jar to RC1, removed the issue, so it is isolated to angelica-1.0.0-beta23.jar

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by PlayfulPiano** [comment]
can also reproduce using ladders

**Comment by travismking** [comment]
confirmed with both BSL and Tea shaders. Downgrading to beta 20 fixes the issue
