### ISSUE TITLE
The game and waila graphic color difference in same setting

### ISSUE THREAD

**Issue by Chococar-NSW** [GTNewHorizons/Angelica#78]
### Your GTNH Discord Username

chococar

### Mod Version

1.0.0-alpha7

### Java Version

Java 21

### Bug Report

I use Prism launcher copy my GTNH 2.5.1 instance and update mod for angelica(the setting is same).
You can the difference this two picture.

Original:
![OR](https://github.com/GTNewHorizons/Angelica/assets/79390577/c5be9b97-b105-42b3-86e3-f680236df137)

Angelica:
![Angelica](https://github.com/GTNewHorizons/Angelica/assets/79390577/be77d8b3-3a8c-4095-8bc7-4d1f595364a3)

The image with angelica is slightly brighter than original.
And walia with angelica is darker.

### Mod List or GTNH Pack Version

GTNH 2.5.1 with the updated mod version for angelica

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by ALongStringOfNumbers** [comment]
Funnily enough, I have seen the opposite.

After using Angelica, my WAILA text has become brighter:
![image](https://github.com/GTNewHorizons/Angelica/assets/31759736/177c991e-5ed0-4cf1-b307-50aa244ce683)


Whereas before it looked dimmer, like the second image in the original issue.

This was using Angelica, alpha 7, on 2.4.0, with all required dependencies updated

**Comment by Chococar-NSW** [comment]
And another I can't is a bug but the font in setting menu has shadow.
![image](https://github.com/GTNewHorizons/Angelica/assets/79390577/e5f2ccc6-6e81-4018-89e7-2d7c8e1522a0)
I really can't tell is annoying but is unadaptable in short time.

**Comment by SKProCH** [comment]
> Funnily enough, I have seen the opposite.
> 
> After using Angelica, my WAILA text has become brighter: ![image](https://private-user-images.githubusercontent.com/31759736/293077806-177c991e-5ed0-4cf1-b307-50aa244ce683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMzM0NjUsIm5iZiI6MTcwNDAzMzE2NSwicGF0aCI6Ii8zMTc1OTczNi8yOTMwNzc4MDYtMTc3Yzk5MWUtNWVkMC00Y2YxLWIzMDctNTBhYTI0NGNlNjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE0MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMzgzMDAwOTQ1MWJhMGRhY2ZmMDUxMzFiNDEzYWQxNjk1NGZjMjk1OTU1NzU0YzdhYjQwMmU5YTIzZTgzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BD4teOTpr9dpqGvh5W6P6UE0oJOeu6lEPfyyBQtQGiw)
> 
> Whereas before it looked dimmer, like the second image in the original issue.
> 
> This was using Angelica, alpha 7, on 2.4.0, with all required dependencies updated

I actually like the brighter one.

**Comment by mitchej123** [comment]
Try again with the latest alpha (28+) and reopen if still an issue

**Comment by Chococar-NSW** [comment]
Original:
![OG](https://github.com/GTNewHorizons/Angelica/assets/79390577/41dbdf95-0b44-4d34-ba6e-a7b5c1303bb9)
Angelica:
![Angelica](https://github.com/GTNewHorizons/Angelica/assets/79390577/d3771670-2973-4377-8036-eebbd7224dc2)

Walia still have problem with alpha-28

**Comment by Chococar-NSW** [comment]
By the way, I can't reopen this issue.
