### ISSUE TITLE
there is only the mod and the 2 cores, but why is it counting as duplicated and my minecraft isn't running? what should i do?

### ISSUE THREAD

**Issue by GlauberBlox** [GTNewHorizons/Angelica#794]
### Mod Version

1.0.0-beta26

### Bug Report

![image](https://github.com/user-attachments/assets/dd213210-8941-4c68-8f7b-282b6ff456c7)

### Java Version

Java 8

### Graphics Card Vendor

AMD

### Shaders

No

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Mod List or GTNH Pack Version

Dragon Block C
Angelica
gtnhmixins
unimixins

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by huihiuhuai** [comment]
you only want unimixns for mixins.

**Comment by GlauberBlox** [comment]
oh ok thx!
