### ISSUE TITLE
Improper Biome Blending with Grass Blocks

### ISSUE THREAD

**Issue by Switchamafuck** [GTNewHorizons/Angelica#803]
### Mod Version

1.0.0-Beta27

### Bug Report

Grass blocks do not biome blend on their sides, but only on their tops, causing a color mismatch.

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Shaders

No

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Mod List or GTNH Pack Version

  [✔] [1.7.10]MoVillages-1.4.2
  [🖿] 1.7 (folder)
  [✔] AbyssalCraft-1.7.10-1.9.1.3-FINAL
  [✔] ActuallyAdditions-1.7.10-r21
  [✔] AdvancedBackups-forge-1.7.10-3.6.4
  [✔] ae2fc-1.3.50-gtnh
  [✔] ae2stuff-0.8.5-GTNH
  [✔] akashictome-1.1.9
  [✔] alreadydecoratingfix-1.0a
  [✔] angelica-1.0.0-beta27
  [✔] AOBD-2.9.2
  [✔] AOBDOC-1.0.5
  [✔] AppleCore-3.3.4
  [✔] appliedenergistics2-rv3-beta-478-GTNH
  [✔] archaicfix-0.7.4
  [✔] ASMFixes-1.0
  [✔] autooredictconv-1.7.10-1.3.1
  [✔] BadMobs-1.0.1-1.7.10
  [✔] battlegear2-1.4.1
  [✔] BaublesExpanded-2.1.4
  [✔] bdlib-1.9.5.1-mc1.7.10
  [✔] BetterAchievements-0.3.0
  [✔] BetterBuildersWands-0.12.0-GTNH
  [✔] BetterBurning-1.7.10-0.4.2
  [✔] bettercrashes-1.4.0-GTNH
  [✔] BetterFoliage-MC1.7.10-2.0.17
  [✔] betterp2p-1.3.0
  [✔] BetterPing-1.7.10-1.0
  [✔] BetterPlacement-MC1.7.10-1.0.0-1
  [✔] biggerpacketsplz-upto1.7.10-1.2
  [✔] BiomesOPlenty-1.7.10-2.1.0.2308-universal
  [✔] blockrenderer6343-1.2.16
  [✔] Bookshelf-1.7.10-1.0.4.187
  [✔] Born in a Barn 1.7.x
  [✔] bugtorch-1.2.14-GTNH
  [✔] CarbonConfig-1.7.10-1.2.4
  [✔] Careful Cast Corrector-2.0
  [✔] ChestTransporter-1.7.10-2.0.6
  [✔] chisel-2.15.2-GTNH
  [✔] Chunk-Pregenerator-1.7.10-4.4.9
  [✔] CleanView-1.7.10-v2
  [✔] ClimateControl-0.9.3-GTNH
  [✔] CodeChickenCore-1.3.10
  [✔] CoFHCore-[1.7.10]3.1.4-329
  [✔] controlling-2.1.2
  [✔] CoreTweaks-1.7.10-0.3.3.2-nomixin
  [✔] CosmeticArmorReworked-1.7.10-v7
  [✔] craftingtweaks-mc1.7.10-1.0.88
  [✔] CraftTweaker-1.7.10-3.1.0-legacy
  [✔] DimensionalDoors-2.2.6-1.7.10
  [✔] Ding-MC1.7.10v2
  [✔] DisenchanterMod-[1.7.10]1.6
  [✔] DWA_a1
  [✔] Dynamic.Lights-1.3.9abugfix2024
  [✔] EasyConfigButton-1.0
  [✔] EasyLAN-v1.5-[1.7.10]
  [✔] enderbatteries-MC1.7.10-0.1-5
  [✔] endercore-0.4.6
  [✔] endercrop-1.7.10-1.2
  [✔] EnderIO-2.8.22
  [✔] EnderStorage-1.6.4
  [✔] EnderTanks-rev16-beta1
  [✔] etfuturum-2.6.2
  [✔] EvilCraft-1.7.10-0.9.13
  [✔] ExtraFixes-1.7.10-1.2.4b
  [✔] ExtraTiC-1.7.10-1.4.6
  [✔] extrautilities-1.2.12
  [✔] falsepatternlib-mc1.7.10-1.5.5
  [✔] Farseek-1.7.10-2.0.1
  [✔] fgtXray-1.7.10-1.0.8
  [✔] FlatBedrock-1.0.2
  [✔] FloodLights-1.4.1
  [✔] FoamFix-1.7.10-universal-1.0.4
  [✔] forgelin-1.10.0-GTNH
  [✔] GraveStone Mod 0.7.10.3
  [✔] greggen-mc1.7.10-0.0.3
  [✔] gtnhlib-0.5.22
  [✔] HardcoreDarkness-MC1.7.10-1.7
  [✔] HardcoreEnderExpansion-1.12.0-GTNH
  [✔] HBM-NTM-GUPDATE-TESTING
  [✔] hodgepodge-2.5.84
  [✔] iChunUtil-4.2.3
  [✔] IguanaTweaksTConstruct-2.5.0
  [✔] InGameInfoXML-2.8.13
  [✔] inventorytweaks-1.7.0
  [✔] IronBackpacks-1.7.10-1.2.20
  [✔] IronChest-6.0.87
  [✔] ItemBlacklist-1.7.10-1.2.0.8
  [✔] IvToolkit-1.2.1
  [✔] JAOPCA-1.7.10-W.0.6.27
  [✔] JustEnoughCalculation-1.7.10-4.2
  [✔] kleeslabs-mc1.7.10-1.2.9
  [✔] laggoggles-mc1.7.10-4.16.1
  [✔] Login_Shield-1.7.10-2-gf6e21a7
  [✔] LumySkinPatch-1.0.13
  [✔] LunatriusCore-1.2.1-GTNH
  [✔] lwjgl3ify-2.1.5
  [✔] malisisdoors-1.17.4-GTNH
  [✔] Mantle-0.4.2
  [✔] MCA-1.7.10-5.2.2-universal
  [✔] mdecore-1.0
  [✔] Mekanism-Community-Edition-1.7.10-9.10.42-Core
  [✔] MobDismemberment-4.0.0
  [✔] mobsinfo-0.4.7-GTNH
  [✔] ModTweaker2-0.9.6
  [✔] MoneyMod 1.7.10 1.0.0
  [✔] MouseTweaks-2.4.18-GTNH
  [✔] Natura-2.7.5
  [✔] netherportalfix-mc1.7.10-1.1.0
  [✔] NotEnoughEnergistics-1.6.4
  [✔] notenoughIDs-2.1.6
  [✔] NotEnoughItems-2.6.52-GTNH
  [✔] NotEnoughKeys-1.7.10-3.0.0b45-dev-universal
  [✔] NotEnoughResources-1.7.10-0.1.0-128
  [✔] OpenBlocks-1.10.2-GTNH
  [✔] OpenComputers-MC1.7.10-1.8.6-b0b022a-universal
  [🖿] opendisks (folder)
  [✔] OpenDisks-MC1.7.10-0.1.0.4
  [✔] OpenGlasses-1.0.46
  [✔] OpenLights-MC1.7.10-OC1.4-0.1.0.22
  [✔] OpenModsLibs-0.10.9
  [🖿] OpenSecurity (folder)
  [✔] OpenSecurity-1.7.10-1.0-117
  [✔] OpenSensors-MC1.7.10-1.0-5
  [✔] OreExcavation-1.1.134
  [✔] OreTweaker-1.0.2-1.7.10
  [✔] overloadedarmorbar-1.1.0
  [✔] p455w0rdslib-1.0.5
  [✔] Pam's HarvestCraft 1.7.10Lb
  [✔] Pam's Temperate Plants 1.7.2b
  [✔] primitivemobs-1.0c-1.7.10
  [✔] Psychedelicraft-1.5.2
  [✔] RadixCore-1.7.10-2.1.3-universal
  [✔] RandomThings-2.5.3
  [✔] ReAuth-1.7.10-Forge-4.0.7
  [✔] RebornCore-1.1.0.15-universal
  [✔] RecurrentComplex-0.9.7.1.2_Unoffical
  [✔] RTG-1.1.3-GTNH
  [✔] ServerUtilities-2.0.85
  [✔] ShetiPhianCore-1.7.10-3.0.0
  [✔] sit-1.7.10-v1.1
  [✔] Snad-1.7.10-1.6.01.31a
  [✔] SpecialAI-1.2.0
  [✔] SpecialMobs-3.6.2
  [✔] squidless-1.7.10-0.6.1
  [✔] Streams-1.7.10-0.3.4
  [✔] structurelib-1.3.6
  [✔] tabfaces-0.0.17-mc1.7.10
  [✔] TConstruct-1.12.16-GTNH
  [✔] thermalcasting-0.0.3
  [✔] ThermalDynamics-[1.7.10]1.2.1-172
  [✔] ThermalExpansion-[1.7.10]4.1.5-248
  [✔] ThermalFoundation-[1.7.10]1.2.6-118
  [✔] ThermalSmeltery-Redux-v1.1
  [✔] TiCTooltips-1.3.1
  [✔] tinker_io-1.7.10-release 1.5.0
  [✔] TipTheScales-1.7.10-3.0.0.2
  [✔] tumbleweed-1.7.10-0.2
  [✔] UniDict-1.7.10-2.9.2
  [✔] -unimixins-all-1.7.10-0.1.19
  [✔] Waila-1.8.2
  [✔] WailaHarvestability-mc1.7.10-1.1.6
  [✔] WAILAPlugins-0.6.0
  [✔] waterhooks-1.2.1
  [✔] Wawla-1.3.0-GTNH
  [✔] Waystones-mc1.7.10-1.0.12
  [✔] WirelessCraftingTerminal-1.11.7
  [✔] worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist
  [✔] Xaeros_Minimap_21.10.43_Forge_1.7.10
  [✔] XaerosWorldMap_1.14.1.33_Forge_1.7.10

![2024-12-18_16 34 39](https://github.com/user-attachments/assets/c29f10eb-4396-4025-ba5a-68e4885db220)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kurrycat2004** [comment]
this is a vanilla thing iirc. its the difference between the three quality settings, first one blends nothing, second one only top, third one top and sides

**Comment by kurrycat2004** [comment]
though iirc the check whether its a side is literally whether the texture name is "grass_side", which means it could break for custom textures/other grass blocks

**Comment by Switchamafuck** [comment]
> this is a vanilla thing iirc. its the difference between the three quality settings, first one blends nothing, second one only top, third one top and sides

youre right im retarded

**Comment by Fabboz** [comment]
this could be loamy dirt from biome or plenty at that biome
