### ISSUE TITLE
Angelica Crash on CurseForge launcher / likely culprit is LWJGL 2.9.1 (CurseForge Launcher default)

### ISSUE THREAD

**Issue by calreveraster** [GTNewHorizons/Angelica#82]
### Mod Version

1.0.0 Alpha 8 

### Java Version

Java 8

### Bug Report

Angelica crashes upon loading world when launched using the CurseForge launcher. 

CurseForge Launcher (both the overwolf version and the new standalone launcher) do not let you edit the LWJGL version and use 2.9.1. 

On other launchers such as prism/multiMC, this is an editable portion of the system. 

That said - on CurseForge, when angelica is launched, Minecraft will load successfully, but when attempting to load into the world, the game crashes. Crash report is attached. 

I did some digging on this - made sure the launch arguments were identical, etc, -  and it appears the only difference between curse and multimc/prism is that curse defaults to lwjgl 2.9.1 whereas the others use 2.9.4 nightly. 

[crash-2023-12-27_17.17.21-server.txt](https://github.com/GTNewHorizons/Angelica/files/13781886/crash-2023-12-27_17.17.21-server.txt)

### Mod List or GTNH Pack Version

Angelica 1.0.0 alpha 8
GTNHlib 0.0.13 
unimixins 0.1.15

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by mitchej123** [comment]
This looks like it's running on a server.  It's a transformer that should be a NOOP on the server side.

**Comment by joshricker** [comment]
I can confirm the issue is lwjgl 2.9.1. In prism with 2.9.4 I can launch it just fine, but if i change it to 2.9.1 I crash on start up. Interestingly I can use alpha 1 with 2.9.1. 
[crash-2023-12-28_02.22.44-client.txt](https://github.com/GTNewHorizons/Angelica/files/13784628/crash-2023-12-28_02.22.44-client.txt)

**Comment by calreveraster** [comment]
> This looks like it's running on a server.  It's a transformer that should be a NOOP on the server side.

This was running in a single player instance, no server.

**Comment by joshricker** [comment]
I had enableIris=true, with it off i can launch with 2.9.1. I can only launch it with shaders on if I use 2.9.4.

**Comment by mitchej123** [comment]
This particular issue looks easy enough, guard against no such field errors when probing for opengl45 support; however in general I think requiring 2.9.4 is fine; given we already support 2.9.4 and 3+ for lwjgl.

**Comment by mitchej123** [comment]
hmm, I already put in a guard against this... but of course `NoSuchFieldError` doesn't extend Exception apparently :facepalm:

**Comment by calreveraster** [comment]
> This particular issue looks easy enough, guard against no such field errors when probing for opengl45 support; however in general I think requiring 2.9.4 is fine; given we already support 2.9.4 and 3+ for lwjgl.

I would agree if a major launcher didn't railroad you into 2.9.1 - when it comes to CurseForge launcher, there is absolutely no way to change which library version you use. 

Which feels like bad implementation (because really, it is) - but it's still a widely used launcher. So you'd probably need to list curseforge launcher in incompatibilities if you went the route of requiring 2.9.4

**Comment by mitchej123** [comment]
> I would agree if a major launcher didn't railroad you into 2.9.1 - when it comes to CurseForge launcher, there is absolutely no way to change which library version you use.
> 
> Which feels like bad implementation (because really, it is) - but it's still a widely used launcher. So you'd probably need to list curseforge launcher in incompatibilities if you went the route of requiring 2.9.4

CF also ships with an OLD OLD java full of issues.  I'm not going out of my way to break compat, but I'm not going to bend over backwards to ensure it.

**Comment by boubou19** [comment]
soon(tm) we will have lwjgl3 on CF, just that the project is at its very begining. We will advertise for it when it'll be ready. Be patient or use another launcher to play modded 1.7.10.

**Comment by calreveraster** [comment]
> soon(tm) we will have lwjgl3 on CF, just that the project is at its very begining. We will advertise for it when it'll be ready. Be patient or use another launcher to play modded 1.7.10.

I use Prism launcher, personally. I'm just advising that if you're going to choose to not support 2.9.1, you'll need to add CurseForge to the list of incompatibilities, because the average person has no way to see what version of lwjgl that CF uses. 

I'm also not suggesting you go out of your way to support it; merely that if you choose not to, that the incompatibility is communicated in a way those who aren't programmers will be able to interpret.

**Comment by calreveraster** [comment]
> > I would agree if a major launcher didn't railroad you into 2.9.1 - when it comes to CurseForge launcher, there is absolutely no way to change which library version you use.
> > Which feels like bad implementation (because really, it is) - but it's still a widely used launcher. So you'd probably need to list curseforge launcher in incompatibilities if you went the route of requiring 2.9.4
> 
> CF also ships with an OLD OLD java full of issues. I'm not going out of my way to break compat, but I'm not going to bend over backwards to ensure it.

There is a CF-specific command line argument to address the java version; there isn't one to address the lwjgl version, though. On CF I can use the latest java 8 version with no issues. 

It's not nearly as intuitive as prism launcher, but it is possible.
