### ISSUE TITLE
Crash on startup with alpha8 

### ISSUE THREAD

**Issue by DannyParker0001** [GTNewHorizons/Angelica#84]
### Mod Version

angelica-1.0.0-alpha8-git.1+b065c18a79-dirty.jar

### Java Version

Java 21

### Bug Report

Linux, OpenJDK 21.u35-3
alpha8 release doesnt work, alpha7 works fine.
[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/13783344/fml-client-latest.log)
[crash-2023-12-28_15.09.44-client.txt](https://github.com/GTNewHorizons/Angelica/files/13783345/crash-2023-12-28_15.09.44-client.txt)

### Mod List or GTNH Pack Version

GTNH 2.5.1
CodeChickenLib-1.2.0.jar
hodgepodge-2.4.3.jar
CodeChickenCore-1.2.0.jar
lwjgl3ify-1.5.7.jar
angelica-1.0.0-alpha8.jar and angelica-1.0.0-alpha8-git.1+b065c18a79-dirty.jar

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by mitchej123** [comment]
Use alpha 7 for now, the transformers for thread safe block bounds need a bit more testing
