### ISSUE TITLE
Game crashes after pressing F5 or F1 while Iris is enabled

### ISSUE THREAD

**Issue by WizardJoker** [GTNewHorizons/Angelica#87]
### Mod Version

1.0.0-alpha8

### Java Version

Java 17

### Bug Report

[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/13787011/fml-client-latest.log)
[crash-2023-12-28_21.55.34-client.txt](https://github.com/GTNewHorizons/Angelica/files/13787012/crash-2023-12-28_21.55.34-client.txt)
Game crashes after pressing F5 or F1 if "enableIris" is set to true.

### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.15.jar
angelica-1.0.0-alpha8.jar
lwjgl3ify-1.5.7.jar

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by mitchej123** [comment]
Ok please stop with the shader issues. They are not ready for testing

**Comment by mitchej123** [comment]
We're testing the sodium backport in the alpha... we'll test shaders when they're read in the beta.

**Comment by mitchej123** [comment]
There's still plenty of already known issues to clean up before enabling them; that's why they're off by default.
