### ISSUE TITLE
Crash when viewing MobsInfo in NEI.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#92]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

1.0.0-alpha9

### Java Version

Java 21

### Bug Report

When viewing the recipe of a flint pickaxe (tinkers), and tried to check the MobsInfo page, it led to a crash.
[crash-2023-12-28_16.34.20-client.txt](https://github.com/GTNewHorizons/Angelica/files/13789600/crash-2023-12-28_16.34.20-client.txt)

### Mod List or GTNH Pack Version

GTNH 2.5.1
Matmos v36
DynamicSurroundings v1.0.6.4
ItemPhysicLite 1.1.5
FPSReducer 1.10.3
Angelica 1.0.0-alpha9

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Lol, it's an invalid matrix mode; GL_MODELVIEW_MATRIX is meant for getting the modelview matrix, not setting it - GL_MODELVIEW is the correct value.  I can handle it and redirect it to the correct call in angelica going forward.
