### ISSUE TITLE
Holding Shift while in an inventory darkens the game screen.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#95]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

1.0.0-alpha10

### Java Version

Java 21

### Bug Report

While holding down "shift" when in an inventory, the game's screen darkens. 

https://github.com/GTNewHorizons/Angelica/assets/3158887/63d0f863-7b97-45ae-826f-0d2bfb595f98

### Mod List or GTNH Pack Version

GTNH 2.5.1
Matmos v36
DynamicSurroundings v1.0.6.4
ItemPhysicLite 1.1.5
FPSReducer 1.10.3
Angelica 1.0.0-alpha10

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by PlayfulPiano** [comment]
Actually the darkness seems to only happen when mousing over non-food items, unsure now if this is angelica or something with one of hungeroverhaull/spiceoflife.

**Comment by 1652518008** [comment]
I met it also.
After checking, I found it is because Thaumcarft is trying to show item aspects and it darkens the game screen.
To vertify it, you can change
```
# Item aspects are hidden by default and pressing shift reveals them. Changing this setting to 'true' will reverse this behaviour and always display aspects unless shift is pressed.
    B:display_aspects=false
```
in config\Thaumcraft.cfg.

**Comment by PlayfulPiano** [comment]
> I met it also. After checking, I found it is because Thaumcarft is trying to show item aspects and it darkens the game screen. To vertify it, you can change
> 
> ```
> # Item aspects are hidden by default and pressing shift reveals them. Changing this setting to 'true' will reverse this behaviour and always display aspects unless shift is pressed.
>     B:display_aspects=false
> ```
> 
> in config\Thaumcraft.cfg.

Can confirm it's thaumcraft causing the issue, but it's reversing the behavior not disabling the darkening entirely.

**Comment by A-UNDERSCORE-D** [comment]
confirming this here as well
