### ISSUE TITLE
Some angles cause Signs to not render.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#99]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

1.0.0-alpha10

### Java Version

Java 21

### Bug Report

![image](https://github.com/GTNewHorizons/Angelica/assets/3158887/3841cc49-873a-4a06-9f02-05a091b8cc6b)

https://github.com/GTNewHorizons/Angelica/assets/3158887/bbe4cb61-a0a7-4ae9-babc-723421c548cf

### Mod List or GTNH Pack Version

GTNH 2.5.1
Matmos v36
DynamicSurroundings v1.0.6.4
ItemPhysicLite 1.1.5
FPSReducer 1.10.3
Angelica 1.0.0-alpha10

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
Try with alpha 28+ and reopen if still an issue

**Comment by PlayfulPiano** [comment]
Rendering seems fixed as of latest.

**Comment by PlayfulPiano** [comment]
Never mind, still occurring as of alpha28

https://github.com/GTNewHorizons/Angelica/assets/3158887/81e8ade0-f79a-4359-886f-e40d10ee3fa8
